### ISSUE TITLE
Legal issues

### ISSUE THREAD

**Issue by vlisivka** [probonopd/AppImageKit#101]
> Like Linux itself, AppImageKit is Open Source. Use it to package your open or commercial applications.

Please, put legal notice for authors about consequences of bundling of open source libraries with their proprietary apps. Currently, you are helping authors of proprietary apps to steal open source libraries.

Please, don't use our GPL'ed libraries in your proprietary bundles and don't encourage others to steal them either.

**Comment by probonopd** [comment]
Looks like you are confusing something: an AppImage is merely an ISO file with a small binary header; the application contained inside the ISO is not linked against any libraries. So to be best of my knowledge, the licensing of the binary header has no influence over the contents of the ISO file (= the AppImage) at all. It is like if you would distribute open source and closed source software on the same CD-ROM.

**Comment by vlisivka** [comment]
Quote from GPL license version 2:

> You may not copy, modify, sublicense, or distribute the Program except as expressly provided under this License. Any attempt otherwise to copy, modify, sublicense or distribute the Program is void, and will automatically terminate your rights under this License.

Please, don't distribute our open libraries with your proprietary code and don't encourage others.

**Comment by probonopd** [comment]
http://www.gnu.org/licenses/old-licenses/gpl-2.0-faq.en.html#MereAggregation
