### ISSUE TITLE
[Idea] AppImage OS 

### ISSUE THREAD

**Issue by kskarthik** [probonopd/AppImageKit#102]
I just came across [Rancher OS](http://rancher.com/rancher-os) which is a minimal docker based which weighs only 20MB. Is there any possibilities of applying the same to appimages ? Need your opinion. 

*Meanwhile, I just made a small blueprint of the appimage os* :sweat_smile:  
![app](https://cloud.githubusercontent.com/assets/11899221/13387717/8cedaecc-dedf-11e5-898e-b25ea668a4e0.png)

**Comment by probonopd** [comment]
Check out SystemImageKit... One OS = one file. Works nicely when you have your apps as AppImages.

**Comment by kskarthik** [comment]
Okay, thanks

**Comment by kskarthik** [comment]
Reopened this to avoid someone comes out with a similar idea filing a new issue.
