### ISSUE TITLE
[Suggestion] for AppImage format 

### ISSUE THREAD

**Issue by kskarthik** [probonopd/AppImageKit#106]
I observed that app names end as .appimage, It doesn't look good :( will you simplify the extension as **.app** Isn't it simple ?

**Comment by probonopd** [comment]
Well the format is called AppImage and there is no need to have a certain file name extension, so you are free to name yours like you want :-)

**Comment by kskarthik** [comment]
Oh! That's great :)

**Comment by kskarthik** [comment]
@probonopd I forgot ! At the end of the day these are just .run files ;) any name doesn't matter

**Comment by shoogle** [comment]
Just so you know, .app is already used by a few other packaging formats, including Mac packages.
