### ISSUE TITLE
AppImageAssistant shows an exclamation mark icon

### ISSUE THREAD

**Issue by mauriliodc** [probonopd/AppImageKit#107]
AppImageAssistant at the end of the procedure shows an  an exclamation mark.
The resultant appimage, btw, works.

[error image](http://i.imgur.com/9FNoMuG.png)

From the shell:
`Running command:
['python', '/tmp/.mount_wjaOT3/package', '/home/user/Test.AppDir', u'/home/user/Test']
child done
/tmp/.mount_wjaOT3/AppImageAssistant:209: GtkWarning: IA__gtk_assistant_set_page_header_image: assertion 'child != NULL' failed
  self.set_page_header_image(vbox, gtk.gdk.pixbuf_new_from_file(application_icon))
/tmp/.mount_wjaOT3/AppImageAssistant:227: GtkWarning: IA__gtk_assistant_set_page_title: assertion 'child != NULL' failed
  self.set_page_title(icon, "An error has occured")
`

**Comment by probonopd** [comment]
You are getting a GTK error which is a cosmetic error. Thanks for reporting this. I haven't really used the GUI in a long time. Someone should rewrite it in GTK 3 ;-)

**Comment by probonopd** [comment]
AppImageAssistant hast been replaced by `appimagetool`. Use it instead.
