### ISSUE TITLE
How self-contained are AppImages?

### ISSUE THREAD

**Issue by lbssousa** [probonopd/AppImageKit#108]
Which host system resources exactly are needed for an AppImage to run (I mean, those ones which just can't be bundled in an AppImage)?

Kernel minimal version?
System shell?
Glibc minimal version?
Other libs/resources? Which ones?

**Comment by RazZziel** [comment]
> Kernel minimal version?
> Glibc minimal version?

Not sure, depends on the compiler that generated the runtime header on the AppImage

> System shell?

Depends on the application enclosed in the AppImage, but any shell should be enough

> Other libs/resources? Which ones?

The main dependency we have right now IIRC is libfuse

**Comment by lbssousa** [comment]
> The main dependency we have right now IIRC is libfuse

After ldd'ing some AppImages, I've found the following other dependencies, but I'm not yet sure why are they needed:
* libpthread
* libdl
* GLib
* Zlib
* PCRE libs

**Comment by probonopd** [comment]
Check out `runtime.c` and `AppRun.c` to see the runtime requirements. AppRun.c can be replaced by a shell script or directly by your executable if you want to, so the dependencies boil down to the ones used by `runtime.c`.
