### ISSUE TITLE
mutli-arch AppImage

### ISSUE THREAD

**Issue by ericfont** [probonopd/AppImageKit#119]
It may be beneficial for some use cases to have option to create a universal AppImage which has binaries & libs for a multitude of architectures.  So could have both i386, x86-64, armv6, armv7, armv8, and whatever else all coexisting such that their binaries are in seperate directories, while any machine-independent code is in a seperate dir.  Then have the AppRun executable select which one.

**Comment by RazZziel** [comment]
This would be trully awesome, but right now it's impossible since the runtime embedded in the ISO header is an ELF itself, tied to an architecture. The [FatELF](https://icculus.org/fatelf/) initiative was promising, but it was aborted.

I guess the only alternative would be to replace the header with a BASH script, but then we'd have the issue that we'd depend on the base system to contain the tools needed to mount the AppImage on the fly. We could embed a tool like `fuseiso` in the bash script, and unpack it on the fly, but we'd need to embed a fuseiso for each architecture, and space in the ISO header runtime is very limited.

**Comment by ericfont** [comment]
I'm looking at fuseiso.c and it seems simple enough that it could be written in bash script itself...

**Comment by RazZziel** [comment]
Really? Dude that would be **awesome**.

There's other little stupid potential problem though: at least in the Gnome2 days, Nautilus (and maybe other file managers) didn't execute packages with BASH headers directly, giving the user the option to either run the package (allright) or "edit" the package (wtf) instead. I don't know if this is a problem anymore.

**Comment by ericfont** [comment]
maybe if most of fuseiso.c gets implemented as bash, then maybe the remaining parts that need to be in c will be small enough to fit as machine code for each architecture.  Also, note that i486 through x86-64 machines can execute i386 code, and that armv7 & armv8 can execute subset of armv6 (if don't do anythings like floating point).

That second issue you bring up would be a problem.

**Comment by ericfont** [comment]
just thinking a little bit more.  Forget about packing Arms with x86es, just focus on one family.  Then I think it becomes more simpler, because fuseiso could be compiled as 32-bit only and run in 32-bit mode, and then the actual application would be a seperate process (?) which could run in x86-64 mode if on x86-64.

**Comment by RazZziel** [comment]
> Also, note that i486 through x86-64 machines can execute i386 code, and that armv7 & armv8 can execute subset of armv6 (if don't do anythings like floating point)

Sounds good. However, if your native bits are not 100% statically linked, right now the problem of 32bit AppImages in 64bit systems is that the runtime links to 32bit libfuse.so.2, which is a major PITA to install on 64bit systems (at least Ubuntu).

**Comment by ericfont** [comment]
Right.  I guess I won't know untill I try out making 100% statically link fuseiso.

**Comment by RazZziel** [comment]
Some further thoughts here: https://github.com/probonopd/AppImageKit/issues/45

**Comment by ericfont** [comment]
Regarding fitting libfuse.a inside header, I did a quick-and-dirty feasability check by checking out https://github.com/libfuse/libfuse and configured with --enable-static and CFLAGS='-Os', and bzip2-compressed libfuse.a, and found 65,343 bytes. Now I'm sure don't need all of libfuse.a, but I haven't studied the AppImageKit codebase at all to know what is needed.  Of course would need do decompress that.  But still seems too big to fit in header.  What is the exact bit budget for header?

**Comment by RazZziel** [comment]
According to https://github.com/probonopd/AppImageKit/issues/5#issuecomment-31119360, 32,768 bytes

**Comment by ericfont** [comment]
aha...well that is within the range of possibility...I'll have to look at which particular functions are needed.

**Comment by ericfont** [comment]
silly me, I notice that you guys have fuseiso.c in your repo, and that when I compile I see a 27,262 byte libfuseiso.a

**Comment by probonopd** [comment]
Unless FatELF gets mainstream adoption this won't be possible without resorting to a script as the ELF header. Which has its own set of problems (e.g., tends to get opened in text editors when the executable bit is not set). Hence closing for now.
