### ISSUE TITLE
How to run x86 AppImages on ARM using QEMU ?

### ISSUE THREAD

**Issue by kskarthik** [probonopd/AppImageKit#121]
I want to run an AppImage bundled app made for x86 on ARM board (raspberry pi 2) How can I do that ? I heard QEMU can do this job but the doc on the website is too complicated for me to understand. Please help me out.

**Comment by probonopd** [comment]
We have some activity here toward building native AppImages for ARM that can be run on the Raspberry Pi 2 and 3, that's probably much better in terms of performance than trying to run x86 binaries. What is your use case for x86 on arm?

**Comment by ericfont** [comment]
you DON'T want to emuale an x86 binary on a Raspberry.  QEMU has a significant order of magnitude slowdown.  you'd want to compile the binary for arm.
