### ISSUE TITLE
AppImageKit sets execute permission for all files in "lib" directory

### ISSUE THREAD

**Issue by shoogle** [probonopd/AppImageKit#127]
Packaging an AppDir with AppImageAssistant results in all files in the AppImage's usr/lib directory (including sub-directories) being given execute permission. This behaviour is redundant because libraries on Linux don't actually execute permission to be run. ~~It also happens even for files that are not libraries (e.g. Qt QML files) that happen to be in usr/lib or a sub-directory~~.

Edit: It actually only happens for .so files, possibly wherever they are within the AppImage (but of course they are most likely to be in usr/lib).

**Comment by shoogle** [comment]
Looking through the code I can't see whether this is caused during the packaging with AppImageAssistant or whether it happens at runtime as a result of some kind of mounting parameter.

**Comment by probonopd** [comment]
This is not intentional. Unfortunately I am also not aware of what causes this.

**Comment by crayxt** [comment]
AFAIK, all rpm based distros has +x flag on libraries. On deb-based, this is exactly the opposite.

**Comment by probonopd** [comment]
Interesting, didn't know that @crayxt

**Comment by probonopd** [comment]
Is this (still) an issue or can we close this ticket?

**Comment by crayxt** [comment]
@probonopd probably we can unset +x flag on libraries and see how it works on rpm-based distros. though I am not sure that this gives any improvement.

**Comment by probonopd** [comment]
Closing this, since I cannot see a problem with this. Feel free to reopen if you think this is a problem.
