### ISSUE TITLE
Find a way to make Python apps portable

### ISSUE THREAD

**Issue by RazZziel** [probonopd/AppImageKit#131]
Python apps are not really portable: the python interpreter is needed in the host system, along with pygtk2, and weird stuff happens on many distros like Archlinux or OpenSUSE (see https://github.com/probonopd/AppImageKit/issues/6)

Possibilities:
- **nuitka**: mentioned in https://github.com/probonopd/AppImageKit/pull/17#issuecomment-84081203, no luck with it so far
- **relocatable virtualenv**: interesting read: http://www.soasme.com/2016/03/26/relocatable-virtualenv
  - The article also mentions the **pip && wheel** possibility, but I if I understand correctly it would involve installing the dependencies from a .tar on every run, which sounds ugly

**Comment by probonopd** [comment]
Just putting python and its required modules and libs inside the AppImage should do the trick; as long as python is coming from an "old enough" host like CentOS 6.

**Comment by RazZziel** [comment]
Is there any example somewhere of a working AppImage that does it?

I tried to do it a while ago and failed (worked with perl and java, but not with python)

**Comment by mykolav** [comment]
Hi guys,

Admittedly, I haven't really had a chance to try it out.
But http://www.pyinstaller.org/ might be worth looking at.

The web page states that

>  Flexible packaging mode:
> **Single directory: build a directory containing an executable plus all the external binary modules (.dll, .pyd, .so) used by the program.**
> Single file: build a single executable file, totally self-contained, which runs without any external dependency.
> Custom: you can automate PyInstaller to do whatever packaging mode you want through a simple script file in Python.

So, maybe, a python app can be first processed by PyInstaller in the single directory packaging mode. And then the generated directory can be packed as an AppImage.

**Comment by probonopd** [comment]
This has been solved a long time ago, see https://github.com/probonopd/AppImages/blob/master/recipes/pythongtk3hello/Recipe for an example.

**Comment by probonopd** [comment]
The currently recommended cause of action is to also bundle python itself, and either set `binpatch: true` or `union: true` in the `.yml`file.

**Comment by aarmea-butterfly** [comment]
Is there an up-to-date example of this? The link no longer exists.

**Comment by TheAssassin** [comment]
@aarmea-butterfly you can try https://github.com/TheAssassin/linuxdeploy-plugin-conda, the latest and greatest way to make AppImages with Python. Not very well documented yet, so please visit us on IRC to allow us to guide you (#appimage on Freenode).

**Comment by deekb** [comment]
Mu Editor looks like its a\Appimage functions this way: [https://github.com/mu-editor/mu/releases/download/v1.1.1/Mu_Editor-1.1.1-x86_64.AppImage](url)
