### ISSUE TITLE
Super simple tutorial

### ISSUE THREAD

**Issue by hmaarrfk** [probonopd/AppImageKit#140]
I know this sounds a little crazy, and your quick description

> Download an application, make it executable, and run! No need to install. No system libraries or system preferences are altered.

is technically all you need to do and technically this is obvious if you run Windows or Mac. But this is so far from what I as a linux user is used to.

Here are the questions I had over the last few days when using AppImage:
1. Where do I download the application I need to run these? Do I need AppRun?
2. The Bintray website is a little confusing:
   * `Download` in `General` is typically empty.
   * The file you want to download is in `Files`
   * The big wrench that you seem to want to click on, doesn't have what you want either.

Honestly, it looks like you have lots of tutorials for devs, but for users, there isn't a "this is how to move away from rpm/deb". That single page would be nice with a tutorial on how to use your awesome software. An explanation of what the asc and zync files are would be nice too.

This is really awesome!!!

**Comment by probonopd** [comment]
Hi @hmaarrfk, thanks for your encouraging words! Indeed this GitHub repository is mainly targeted towards developers who want to provide their application as an AppImage. That is the idea: You download the application from the original (upstream) application author, as you would for Windows or Mac; without an intermediary between you and the author.

Here are some examples:

 * **CubicSDR** [Releases](https://github.com/cjcliffe/CubicSDR/releases)
 * **MuseScore** [Releases](https://musescore.org/en/download#AppImage) [Nightlies](https://bintray.com/musescore) [Pull Request](https://github.com/musescore/MuseScore/pull/2362) (thanks shoogle)
 * **StopGo** [32-bit and 64-bit releases](http://makerbox.org.nz/stopgo/) (thanks notklaatu)
 * **OpenShot** [releases and continuous builds](http://www.openshot.org/download/) (thanks jonoomph)
 * **Scribus** [1.5.1 Release](http://wiki.scribus.net/canvas/1.5.1_Release) (thanks jghali)
 * **Krita** 3 [pre-alpha](http://files.kde.org/krita/3/linux/) (no KDE needed!) (thanks boud)
 * **Subsurface** [releases](https://subsurface-divelog.org/downloads/) and [snapshots](https://subsurface-divelog.org/downloads/daily/) (thanks dirkhh)
 * **Pitivi** [snapshots](http://pitivi.ecchi.ca/bundles/) (thanks tvb)
 * **WorldForge** [releases](http://www.worldforge.org/index.php/downloads/)

That being said, to illustrate how to make AppImages, I am creating some as examples and upload them to https://bintray.com/probono/AppImages. To use them, click on an application, then on one of the available versions (normally the topmost = most recent one), then on "Files", then on the AppImage. After you have downloaded the AppImage, `chmod a+x` it and then run it. To update the AppImages provided by me, you can try to use the work-in-progress [AppImageUpdate](https://github.com/probonopd/AppImageKit/blob/master/AppImageUpdate.AppDir/README.md) which also can be downloaded from there. The `.asc` file contains a cryptographic signature that you can use to verify the corresponding file with `gpg`. The `.zsync` file is used by AppImageUpdate to determine which parts of the file need to be downloaded in a delta update.

**Comment by hmaarrfk** [comment]
Cool stuff.

Some of the programs seem to have missing dependencies. That is unfortunate (I'm thinking StopGo is telling me there isn't a function called `libvlc_new`).

I'll keep checking up on this. I use Fedora and found it quite annoying that many of the programs that are available for linux are simply not packaged in a sensible fashion. Your solution seems to address the biggest issues!!!!

**Comment by shivarajnaidu** [comment]
Hi @hmaarrfk , really glad with your sweet and short Q&A .
I have another question.. Would you please clarify that one too..
I have installed telegram for Linux ..it's also works just similarly appimage . if both formats are different .. Then what is difference between these two? 
And my main question is .Appimage applications could be updated with usual package management system used in respective Linux OS ? Why I am asking this is centralized package management system is one of the great feature in Linux.. That others don't have.. And what about multi user support?  Can I make it available for all users on system.. (Like if I install normal .deb/rpm application it would be available for all users on system)?

**Comment by probonopd** [comment]
> Some of the programs seem to have missing dependencies. That is unfortunate (I'm thinking StopGo is telling me there isn't a function called libvlc_new).

Please open individual tickets for these in the respective bugtrackers from where you downloaded the AppImage. In the case of StopGo, this would be https://github.com/notklaatu/stopgo/issues

**Comment by probonopd** [comment]
> I have installed telegram for Linux ..it's also works just similarly appimage . if both formats are different .. Then what is difference between these two? 

telegram for Linux is a statically compiled Qt application that has all resource files (e.g., graphics etc.) hardcoded inside the binary. To produce such an application, it has to be developed accordingly, specifically with this way of distributing it in mind. This is quite uncommon for regular Linux applications. AppImage, in contrast, is essentially a self-mounting ISO file which contains the application exectuable and any resources (graphics, icons, fonts, libraries, translations etc.). This allows "normal" Linux applications to be distributed in the "one app, one file" approach without having to hardcode all the resources inside the application executable (and hence, rewriting the code of the application).

> And my main question is .Appimage applications could be updated with usual package management system used in respective Linux OS ?

Sure, it could. But then it's no longer a "go to the app website, download, and run" operation. If you like traditional package management, then you could just stick with it. Traditional package management works great for system components but not so well for 3rd-party applications. You'd have to install a repo for each of those which can become a bit cumbersome (e.g., think of ppa or copr repos).

>  And what about multi user support? Can I make it available for all users on system..

Sure, e.g., copy the AppImage to `/opt` and `chmod a+x` it. Users can then run it from there.

**Comment by shivarajnaidu** [comment]
thanks @probonopd and sorry still i can't understand traditional package management with .appimage i am using fedora , if i have installed .appimage app then ,can i update the . appimage app simply just like any other linux app, by running `sudo dnf update && sudo dnf upgrage appname` ?  can use PPAs for appimage apps ?

**Comment by probonopd** [comment]
You could, if someone would package AppImages for use with yum and/or apt-get. This would be technically possible without any issue, but it would remove many of the advantages of AppImages, namely
- You would need to install repositories
- You would need root rights
- You could only have one version installed at each given time
- You would need to install AppImages (which takes additional time through an unpacking step)
- Someone would have to package each AppImage for the different distros
So I can't see any reason why you would want to do that.

**Comment by shivarajnaidu** [comment]
:+1: thanks for clarification. i asked this because centralized updating is simple way to update whole system... thinking difference between windows and linux way of software management. However, Appimage is awesome and very useful to share software packages between friends in offline..

**Comment by probonopd** [comment]
Yes, AppImages are not a replacement for but an addition to distribution packages.

**Comment by shoogle** [comment]
To respond to the OP (@hmaarrfk) I made this video explaining how to install an AppImage:
https://www.youtube.com/watch?v=btmK0Cg1DJs&t=38s

The video is for [MuseScore](https://musescore.org/), but everything from [00:25-02:30](https://www.youtube.com/v/btmK0Cg1DJs?start=25&end=151&vq=hd720) is general to all AppImages.

@probonopd, I would be happy to make a generic video for you if you like - perhaps when the desktop integration process has been firmly established.
