### ISSUE TITLE
Please test this appimage

### ISSUE THREAD

**Issue by kskarthik** [probonopd/AppImageKit#142]
Hello! I just made this app as appimage. This app named Modem Manager GUI which is an open source program used for managing usb 3g & 4g modems. 
* I built on Ubuntu 16.04 64bit
* Tested working on Kubuntu 16.04 64bit 

Since i don't have old systems & low bandwidth, please help me by testing this on the old os's you have.

Thank you :smiley: 

[ModemManagerGUI_x64.AppImage.tar.gz [2.3 MB]](https://github.com/probonopd/AppImageKit/files/266233/ModemManagerGUI_x64.AppImage.tar.gz)

**Comment by probonopd** [comment]
On Ubuntu 14.04 I get:

```
/home/me/Desktop/ModemManagerGUI_x64.AppImage: error while loading shared libraries: libgtkspell3-3.so.0: cannot open shared object file: No such file or directory
```
You need to bundle it.

**Comment by kskarthik** [comment]
Alright, i will try adding. Thanks for testing it.

**Comment by kskarthik** [comment]
Can you please tell me the reason why i am unable to execute this app after making it as appimage ?
![bgf](https://cloud.githubusercontent.com/assets/11899221/15293058/c488bc04-1ba3-11e6-98e5-9938a3c32015.png)

**Comment by probonopd** [comment]
Where is this AppImage from? Possibly it contains bugs.

Try:

```
sudo mount ./BlueGriffon.AppImage /mnt -o loop
/mnt/AppRun
```

Does that run?

**Comment by kskarthik** [comment]
I used the command. This is result. GUI isn't opening 
![bgf2](https://cloud.githubusercontent.com/assets/11899221/15293369/43fee2a0-1ba5-11e6-9519-f5a087b49ec7.png)

**Comment by probonopd** [comment]
Unmount any instance of the AppImage or reboot your system, then try the mount command again.
