### ISSUE TITLE
LightTable appimage 

### ISSUE THREAD

**Issue by kskarthik** [probonopd/AppImageKit#143]
I just made [light table](http://lighttable.com) code editor's latest appimage. I'm sharing this with you :smiley:  
It works on all distro's as i made it from statically linked archive which they provide on their website. 

Download here[53.5 MB]: https://www.dropbox.com/s/3fbofqvkn8ex55q/LightTable-0.8.1_x64.AppImage.tar.gz?dl=0

**Comment by probonopd** [comment]
:+1:

**Comment by probonopd** [comment]
Did you contact the Light Table team or open a PR?

**Comment by kskarthik** [comment]
i will :smiley:

**Comment by kskarthik** [comment]
i filed a issue now

**Comment by kskarthik** [comment]
@probonopd  i added appimage to their wiki https://github.com/LightTable/LightTable/wiki

**Comment by probonopd** [comment]
I'm not sure whether downloading AppImages from "random" Dropbox links is a good idea... I wouldn't recommend it, as it could be anything...

**Comment by kskarthik** [comment]
@probonopd  Will you upload that to appimage bintray please, so that i could link it from there :)

**Comment by probonopd** [comment]
The upload to Bintray is part of a fully automated build process for which I need your Recipe. Please clone the AppImages repository and add a Recipe.
