### ISSUE TITLE
Error during building AppImageKit and AppImageAssistant start. eOS Freya 0.3.2 x32

### ISSUE THREAD

**Issue by AnFlare** [probonopd/AppImageKit#147]
Hi to all.
First of all, my system: Elementary OS Freya 0.3.2 x32, based on Ubuntu 14.04
Tried to follow instructions about making an AppImage, but could not go farther then cmake & make AppImageKit. [Here](http://pastebin.com/siKyBgyB) are logs of Terminal during the process.

After that I tried to start AppImageAssistant just for a curiosity. But only errors happened (see in logs too)
Google gives me a hint to install _libcanberra-gtk-module_ and _gtk2-engines-pixbuf_ and after these manipulations some warnings disappeared. But anyways not all of them, these ones remain:
```
Gtk-Message: Failed to load module "pantheon-filechooser-module"
Attempt to unlock mutex that was not locked
Aborted (core dumped)
```
And AppImageAssistant doesn't start either.

I tried to start it without any gtk modules at all:
`env GTK_MODULES="" ./AppImageAssistant`
and first line disappear, but AppImageAssistant refuse to start anyway...

I believe AppImageAssistant don't start because of not building properly. So now I don't understand what to do and in what direction go to make all AppImageKit work.

**Comment by probonopd** [comment]
Hello @AnFlare you are running into some bug regarding the compatibility of the AppImageAssistant GUI. Please try running AppImageAssistant on the command line like this:

```
AppImageAssistant ./inputAppDir/ ./outputAppImage
```

See a full example [here](https://github.com/probonopd/AppImages/blob/master/recipes/leafpad/Recipe).

Does that work?

**Comment by AnFlare** [comment]
@probonopd So I need to start making an AppImage of some app without in-between AppImageKit tests? (is it even able to start, I mean) What if AIK was compiled improperly?

**Comment by probonopd** [comment]
Let's just say the GUI of AppImageAssistant is broken at the moment, please use the command line command in the meantime.

**Comment by AnFlare** [comment]
Yeup, I'll try in some days, thanks!

**Comment by AnFlare** [comment]
@probonopd I tried to build Filezilla AppImage and succeeded.  :+1:  But I can't make an AppImage for Deluge torrent client. Is it another story and this one should be closed now?

**Comment by probonopd** [comment]
Yes.

**Comment by lukedoomer** [comment]
sorry guys, where can I download the appimage version of filezilla?

**Comment by TheAssassin** [comment]
@lukedoomer please ask the authors of Filezilla to build an AppImage.

**Comment by ps3460** [comment]
@AnFlare How did you build this please? Mine keeps failing.
@TheAssassin Couldn't find anything on their website

**Comment by probonopd** [comment]
@ps3460 please open a feature request here:
https://trac.filezilla-project.org/

**Comment by TheAssassin** [comment]
@ps3460 if you need help building AppImages yourself, please join our IRC chat (#AppImage on Freenode).
