### ISSUE TITLE
Compile only what is needed to generate AppImages

### ISSUE THREAD

**Issue by probonopd** [probonopd/AppImageKit#15]
https://github.com/ifireball/btsync-app/issues/1#issuecomment-74029173:

I'd like to be able to build only what's needed for the 'package' script without the rest of the AppImageAssistant GUI. It would also be nice if there was a stand-alone release of that, so it could be packaged as a build tool in distros.

Pull requests are welcome.

**Comment by RazZziel** [comment]
What's the point here?
* To have direct access to the package command, without the *AppImageAssistant* GUI, for instance running `AppImageAssistant --package`? It could be done with a simple tweak of the `AppRun` script
* To have a minimal distribution of *AppImageAssistant*, to reduce size? *AppImageAssistant* is ~1.2MB so I think that shouldn't be a problem

**Comment by probonopd** [comment]
To provide an easy way for build processes of 3rd party apps to package the app in an automated way as an AppImage without having to build all of AppImageKit. But you are right, since the overhead is relatively small, it is not a major issue.

**Comment by RazZziel** [comment]
Looks like the `AppImageAssistant --package` kind of feature was already implemented in 2013 (1b6f9c45a27899563787acf9fe55829593adc0a9); I didn't know, that's useful.

If someone wants to make a minimal AppImageAssistant, or rather AppImagePackager, at first glance it looks like it would be a matter of isolating:
* [package](https://github.com/probonopd/AppImageKit/blob/master/AppImageAssistant.AppDir/package)
* [xdgappdir.py](https://github.com/probonopd/AppImageKit/blob/master/AppImageAssistant.AppDir/xdgappdir.py)
* [xdg/*](https://github.com/probonopd/AppImageKit/tree/master/AppImageAssistant.AppDir/xdg)
* And the xorriso binary, wherever it comes from

**Comment by RazZziel** [comment]
@ifireball do you think pull https://github.com/probonopd/AppImageKit/pull/32 solves this issue and it can be closed?

**Comment by probonopd** [comment]
`make runtime AppRun` seems to do the trick.
