### ISSUE TITLE
Telegram appimage

### ISSUE THREAD

**Issue by kskarthik** [probonopd/AppImageKit#150]
Just made it. You can download here https://www.dropbox.com/sh/r46jrd6t6k28myq/AAChgJdZT5yaB0d1bZt6OVCaa?dl=0

Reasons why i did appimage:
1. even though they follow a similar packing mechanism for their app, It sucks. updater binary comes seperate.
2. To show them appimage demo.

An issue will be raised on their repo with the same :wink:

**Comment by crayxt** [comment]
@kskarthik Could you provide your buildscript?

**Comment by probonopd** [comment]
Looking at their Travis CI scripts, they are using an Arch Linux chroot on Travis CI to build Qt as a static library and then use that to build the application. Very interesting. In any case, I will have a look at integrating AppImage generation into their continuous build setup.

**Comment by kskarthik** [comment]
@crayxt  no, i made it manually

**Comment by kskarthik** [comment]
> In any case, I will have a look at integrating AppImage generation into their continuous build setup.

@probonopd instead of modifying telegram's travis build, adding a script to build appimages from the created binary will be much easier, i think. That's how i created appimage for telegram. moved the two binaries into usr/bin
