### ISSUE TITLE
Appimage Runtimes Possibilities 

### ISSUE THREAD

**Issue by kskarthik** [probonopd/AppImageKit#151]
Some apps are very dependent on their runtimes (kde, gnome). Is there a chance that runtimes can be made as appimages & these apps can be packed along with them & get shipped ?

For Example: gedit + gnome runtime are present inside an appimage. gedit appimage depends on gnome runtime appimage.

Like now what we have electron for webapps. Apps can be shipped with their desired runtime inside an appimage (a little variation from xdg-app) This creates chance of more binary compatability with disto's. Of course, app size increases.

What are the possibilities ?

**Comment by probonopd** [comment]
What you describe is more or less the concept of [Flatpak](https://github.com/flatpak/flatpak). But that means that you need to keep track of dependencies and in fact quickly need another package manager. 

It is one key principle of AppImage to keep things easy by not allowing any dependencies that are neither assumed to be part of the base system nor bundled inside the AppImage. In this regard, we follow the iOS/Android model where an app always includes everything that is not part of the base system.

That is not a technical limitation, but a decision to keep things as simple as they are: Download an AppImage and it should run, without you needing to install anything else.

**Comment by kskarthik** [comment]
I'm not telling to install a runtime seperately. Instead, it should come inside an appimage like electron packs nodejs & webkit along with app

**Comment by probonopd** [comment]
Isn't that exactly what we are doing? For example, Krita comes with a Qt runtime.

**Comment by kskarthik** [comment]
oh!

**Comment by probonopd** [comment]
To be be precise, with the specific subset of the Qt that is needed for this particular app. Reduces download sizes...

**Comment by kskarthik** [comment]
puddletag dev has given up. He needs to link pyqt & some other specific python bin's for the app https://github.com/keithgg/puddletag/issues/288
