### ISSUE TITLE
Clarify file suffix requirements for AppImages

### ISSUE THREAD

**Issue by estan** [probonopd/AppImageKit#153]
Hi,

Sorry in advance if GitHub Issues is not the place for questions.

I have authored a small tool [1] for which I'd like to try out AppImage packaging (looks really neat!).

The tool is a documentation generator plugin for the `protoc` (Protocol Buffers) compiler.

Such plugins are standalone executables, and the `protoc` compiler discovers available plugins by searching `$PATH` and `$PWD` for executables named `protoc-gen-<format>` (or `protoc-gen-<format>.exe` on Windows). If a plugin `protoc-gen-foobar` is found, the `protoc` compiler gains a new `--foobar_out` flag for invoking the plugin. My plugin executable is thus named `protoc-gen-doc`, giving the user a `--doc_out` flag for `protoc`.

This leads me to my question (phew): I know that there's no formal spec for AppImage yet, but when one materializes, do you think it will mandate the `.appimage` or `.AppImage` file suffix for AppImages?

This would be a bit of a problem for me, since if I wanted my AppImage to be spec compliant, I'd have to name it `protoc-gen-doc.appimage`, and the user would consequently have to invoke it using the slightly strange `protoc --doc.appimage_out` command line syntax :/ And I'm not even sure `protoc` will allow dots in the plugin executable name.

So, what do you think? Will `.appimage` or `.AppImage` be a hard requirement?

Thanks in advance,
Elvis

PS. I guess this is vaguely related to #144. DS.

[1] https://github.com/estan/protoc-gen-doc

**Comment by probonopd** [comment]
I hope a suffix of any kind will not be needed for AppImage files (in fact they run well without any). And you are spot on regarding #144.

The idea is that if you put an AppImage in your `$PATH`, then it should behave like any other executable.

**Comment by estan** [comment]
Alright, good to know. Thanks!
