### ISSUE TITLE
[desktopintegration] Doesn't work with spaces

### ISSUE THREAD

**Issue by chrisnharvey** [probonopd/AppImageKit#164]
I've just built an AppImage with desktop integration. It works fine until I rename the AppImage to contain a space, this then stops the "Install" alert from showing up.

**Comment by probonopd** [comment]
If you have some spare time, please have a look whether you can fix it and send a pull request. Thanks!

**Comment by chrisnharvey** [comment]
Will do, thanks @probonopd
