### ISSUE TITLE
[AppImageMonitor] watchAppImages() does not look at extension

### ISSUE THREAD

**Issue by derixithy** [probonopd/AppImageKit#170]
When starting AppImageMonitor all files with bin or AppImage will be added to the menu.
Only after running AppImageMonitor and after copying/renaming/moving an app without extension it will be added to the menu.
Because inotify will send all files with CREATE and MOVED_To indiscriminantly to registerAppImage.sh, registerAppImage only checks if it is an executable or iso9660 image.

So somewhere in the watchAppImages function needs to be a fileextension check.

I'm not good with regular expressions so i won't attempt a fix.

**Comment by probonopd** [comment]
AppImageMonitor has been replaced by `appimaged`. Use it instead.
