### ISSUE TITLE
Clarification of "AppDirAssistant is no longer the recommended way to generate AppImages"

### ISSUE THREAD

**Issue by develar** [probonopd/AppImageKit#178]
Hi, I am going to support AppImage target in the electron-builder and have couple of questions.

In the `build.sh` I see 

> AppDirAssistant is no longer the recommended way to generate AppImages.

1. What I should use instead? Where are binaries?
2. Where can I grab AppRun? I see https://github.com/resin-io/etcher/tree/master/scripts/build/AppImages but where is official download? I don't see in the https://github.com/probonopd/AppImageKit/releases or bintray.

  In the wiki no info about it, only that [it should be](https://github.com/probonopd/AppImageKit/wiki/Creating-AppImages#manually-creating-an-appdir).

 (I understand that maybe I should build AppImageKit to get it, but you know, it is very inconvenient and insecure (e.g. possible question from user why electron-builder doesn't use official builds?)).

3. Is it possible to build AppImage (convert dir to AppImage) on MacOS? I assume format is simple and should be easy to port.

**Comment by develar** [comment]
1. Got it. `AppDirAssistant` is deprecated, but `AppImageAssistant` not.

**Comment by develar** [comment]
2. Found :) But why etcher use `x64`/`x86` variants instead of just x86? @jviotti could you please comment? It is just "because better" or are there strong reasons?

**Comment by probonopd** [comment]
> Where can I grab AppRun?

Currently https://github.com/probonopd/AppImageKit/releases/download/5/AppRun

**Comment by jviotti** [comment]
Hi @develar ,

> 2 . Found :) But why etcher use x64/x86 variants instead of just x86? @jviotti could you please comment? It is just "because better" or are there strong reasons? It seems #139 is the answer why.

Do you mean why we use `x86_64` instead of just `x64`? If so, its only a naming convention that we kept adhering to for historical reasons. Happy to rename to `x64` if that clarifies things for our users.

**Comment by probonopd** [comment]
Please use the architecture names used by `arch(1)`.

**Comment by develar** [comment]
@jviotti I mean why do you have to use special build (x64) instead of released official build, but after that I found issue https://github.com/probonopd/AppImageKit/issues/139 If I understand correctly, you need to build AppImage for both arch but AppImageAssistant doesn't support it.

**Comment by jviotti** [comment]
@develar Right, I've pre-compiled both AppRun and AppImageAssistant, and I run the build scripts on VMs on each release. https://github.com/probonopd/AppImageKit/pull/130 seems to be the answer.
