### ISSUE TITLE
MacOS AppImageAssistant

### ISSUE THREAD

**Issue by develar** [probonopd/AppImageKit#179]
Is it possible to build AppImage (convert dir to AppImage) on MacOS? I assume format is simple and should be easy to port.

It is not convenient for users to use Docker (on MacOS you can build anything — nsis, squirrel, all linux package formats).

**Comment by probonopd** [comment]
Interesting question. What would be the use case? Are you attempting some sort of cross-compile?

**Comment by develar** [comment]
> What would be the use case?

On MacOS you can build for any platform (nsis even doesn't require wine). Appimage is the only format that requires Linux. I am going to make Appimage default format for electron-builder linux target (instead of deb) but currently I have to use Docker.

> Are you attempting some sort of cross-compile?

Not yet, I will try.

**Comment by probonopd** [comment]
If you have everything that should go **into** the AppImage in a format that works on Linux then it could be possible to generate the AppImage on macOS.

You could use precompiled, binary versions of runtime and AppRun; and use the AppImageAssistant/package script on macOS. For that to work you need to have macOS versions of all the tools the package script uses - it looks like xorriso is available for macOS (e.g., in homebrew).

So it looks like it could be doable.

**Comment by develar** [comment]
@probonopd Ok, I don't need to use AppImageAssistant at all, cool.

One question about this [code](https://github.com/probonopd/AppImageKit/blob/master/AppImageAssistant.AppDir/package#L87):

```py
print("Embedding runtime...")
elf = os.path.realpath(os.path.dirname(__file__)) + "/runtime"
s = open(elf, 'rb')
f = open(destinationfile, 'rb+')
f.write(bytes(s.read()))
print("ok")
print("Embedding magic number 0x414901 at offset 8...")
f.seek(8)
f.write('\x41\x49\x01')
f.close()
s.close()
print("ok")
```

Am I right that you don't **prepend** runtime, but **overwrite** header of image?

**Comment by probonopd** [comment]
Correct. The ISO has blank space in the beginning which we fill with the ELF.

Btw, the code above should be able to run 1:1 on macOS.

**Comment by probonopd** [comment]
@develar did you figure out how to do this on macOS or do you need further help?

**Comment by develar** [comment]
@probonopd Yes, https://github.com/electron-userland/electron-builder/blob/master/src/targets/appImage.ts, thanks for quick answers. It is not yet finished, but will be ready soon.

**Comment by develar** [comment]
JFYI: electron-builder uses xorriso directly because I need to use `-map` functionality — as fpm supports and xorriso (but not app image python tool). i.e. app dir prepared on the fly without real copy (because we must not modify source dir). In any case it is not an issue because python tool is nothing more than just xorriso+embed runtime. So, it is ok. Thanks for so simple and cool format.
