### ISSUE TITLE
Wrong behavior of `appimageupdate`

### ISSUE THREAD

**Issue by cgalvarez** [probonopd/AppImageKit#180]
I've found some issues when making an AppImage self-updateable with the `appimageupdate` script:

1. The app updates, but an error from zsync is in the output: `zsync_curl: invalid option -- '#'`. I suppose [this line](https://github.com/probonopd/AppImageKit/blob/master/AppImageUpdate.AppDir/usr/bin/appimageupdate#L143) is causing that error. I am using the `zsync_curl` binary downloaded from [here](https://github.com/probonopd/zsync-curl/releases/download/_binaries/zsync_curl) mentioned in the [AppImageUpdate README](https://github.com/probonopd/AppImageKit/tree/master/AppImageUpdate.AppDir#example-how-to-make-your-app-self-updateable).
2. The update seems to run twice every time (from both, command line and Electron/Node.js). This is my usual output:
> zsync_curl: invalid option -- '#'
zsync_curl: invalid option -- '#'
Read meteor-app.AppImage. Target 100.0% complete.      **************************
Read meteor-app.AppImage. Target 100.0% complete.      **************************
Target meteor-app.AppImage
verifying download...checksum matches OK
used 42532864 local, fetched 0
Target meteor-app.AppImage
verifying download...checksum matches OK
used 42532864 local, fetched 0
> ...

  But that doesn't happen when I exec `zsync_curl` directly from the command line, so the problem is in `appimageupdate`.
3. **GPG check fires always** ([zync](https://github.com/probonopd/AppImageKit/blob/master/AppImageUpdate.AppDir/usr/bin/appimageupdate#L146) or [bintray-zsync](https://github.com/probonopd/AppImageKit/blob/master/AppImageUpdate.AppDir/usr/bin/appimageupdate#L176)), and the `appimageupdate` script expects to find a `.asc` file in the same location as the `.AppImage` and the `.AppImage.zsync`, so we should generate that file (I haven't read anything about it in the [AppImageUpdate README](https://github.com/probonopd/AppImageKit/tree/master/AppImageUpdate.AppDir#example-how-to-make-your-app-self-updateable)), because there seems to be no way to override that behavior through command line parameters. If `gpg` is present at the client, then this fills `stderr` if that `.asc` file is missing.
4. The **AppImage loses exec permissions** for ALL after the update finishes **using the script `appimageupdate`** (changed from 0755 to 600), no matter if update is internal (self-updateable) or extenal (manual from the command line).

  It should be done [here](https://github.com/probonopd/AppImageKit/blob/master/AppImageUpdate.AppDir/usr/bin/appimageupdate#L145), but that does not happen in my tests.

1) and 2) are issues, 3) should be documented, and 4) should be documented (warning users to restore them manually) or fixed.

PD: Don't know if it has to do with this, but I'm using Ubuntu Xenial 16.04.

**Comment by probonopd** [comment]
> The app updates, but an error from zsync is in the output

zsync_curl outputs `####` to display a progress indicator. The script uses the `tee` command to duplicate the output and convert the characters to one line each, in order for the GUI to pick up each new line and use those to move the GUI progress indicator. This whole thing is a bit of a hack, and I'd appreciate a cleaner implementation of the "communication" between the script and the GUI. So far I have found it to work though, so this is probably only a cosmetic issue?

> The update seems to run twice every time

The `tee` command duplicates the output, but that doesn't mean each command is actually ran twice. See the above for an explanation.

>  GPG check fires always (zync or bintray-zsync), and the appimageupdate script expects to find a .asc file in the same location as the .AppImage and the .AppImage.zsync

Correct, the updater not only downloads the .zsync and the .AppImage, but also the .asc GPG signature. This is a feature, not a bug - do you think the beavior should be different, and if so, why?

> The AppImage loses exec permissions

I noticed that too but I don't know the reason. Can you find a workaround or solution?

Please open one ticket for each topic in the future, that would make it easier to track things.

**Comment by probonopd** [comment]
As for an update GUI, maybe you'd want to write your own GUI around the appimageupdate script using Electron?

**Comment by cgalvarez** [comment]
> Please open one ticket for each topic in the future, that would make it easier to track things.

Sorry for that. Going to do it :wink: for the relevant ones.

> As for an update GUI, maybe you'd want to write your own GUI around the appimageupdate script using Electron?

I'm already using the auto-updater features of Electron, with the methods of Meteor Electron. It's already working, but I haven't sent the pull request yet.

**Comment by cgalvarez** [comment]
I've open a separate issue #181 and sent a pull request #182  for fixing the permissions issue.

**Comment by cgalvarez** [comment]
`zsync_curl` error has now its own issue #183 and pull request #184.

**Comment by cgalvarez** [comment]
The double output due to `tee` is not a problem at all, once I know that isn't executing twice the update.

> Correct, the updater not only downloads the .zsync and the .AppImage, but also the .asc GPG signature. This is a feature, not a bug - do you think the beavior should be different, and if so, why?

Meteor.js redirects to home (`/`) route, so `gpg_check` is downloading the HTML of the homepage and using it as `.asc`, that's why it is sending errors to `stderr` (I'm not serving any `.asc` file at this moment). So this is an issue of mine. Sorry for that.

Nevertheless, I think that the downloaded `.asc` file should be removed after the check, like `appimageupdate` does indeed with the `.zs-old` file. That's done in pull request #185.

**Comment by cgalvarez** [comment]
These issues have been fixed in separate issues & pull requests, so I'm going to close it.
