### ISSUE TITLE
How to run AppImageAssistant.AppDir/package without having to build?

### ISSUE THREAD

**Issue by estan** [probonopd/AppImageKit#193]
I'd like to run the `AppImageAssistant.AppDir/package` tool from my image build script, but would prefer not to have to build `AppImageKit` before I do so, since it requires me to install Git and various dependencies, and takes time. Fast turnaround time is important to me, especially while working out the kinks in my script.

There's an AppImage of `AppImageAssistant` here on GitHub under Releases, but AFAICT there's no way to run just the `package` tool in it? It would be great if maybe the `AppImageAssistant` script could take some flag to make it invoke the `package` tool?

Maybe I have missed something and it is indeed possible to run just the `package` tool from the AppImageAssistant AppImage, if so I'm happy to be corrected.

Thanks a lot for AppImage!

**Comment by shoogle** [comment]
You can run AppImageAssistant from the command line like this:

```bash
./AppImageAssistant <input-AppDir> <output-AppImage>
```
For example:
```bash
./AppImageAssistant MyProgram.AppDir MyProgram.AppImage
```
Use the `-h` option to see other available commands.

**Comment by estan** [comment]
Bah, I don't know how I missed that synopsis. Thanks!

**Comment by probonopd** [comment]
Well, since `package` is just a script, you could also just run it by itself, provided that you have its dependencies (live `xorriso` and `dd`) installed.

**Comment by estan** [comment]
Ah yes. That's what I'm doing now. And I also realized I need to build it anyway, not just use an AppImage, since I need the AppRun that gets build through `build.sh -> cmake`. What I've done is to move the pulling + building of AppImageKit from my build script to the Dockerfile I use to set up my build environment, that speeds things up a little.
