### ISSUE TITLE
64bit portability issue: runtime.c:210

### ISSUE THREAD

**Issue by marguerite** [probonopd/AppImageKit#194]
This prevent me from building AppImageKit on openSUSE Build Service.

[   58s] W: AppImageKit strict-aliasing-punning /home/abuild/rpmbuild/BUILD/AppImageKit-5~git20160701.2d1265c/md5.c:142, 143, 188, 189
[   58s] E: AppImageKit 64bit-portability-issue /home/abuild/rpmbuild/BUILD/AppImageKit-5~git20160701.2d1265c/runtime.c:210

**Comment by probonopd** [comment]
Thanks for reporting @marguerite - do you know how to fix this?

**Comment by probonopd** [comment]
Does this still happen with the latest version?

**Comment by marguerite** [comment]
No, it doesn't happen now.

**Comment by probonopd** [comment]
Thanks for confirming!
