### ISSUE TITLE
Binaries built on Ubuntu 16.04 refuse to mount

### ISSUE THREAD

**Issue by probonopd** [probonopd/AppImageKit#198]
When AppImageKit is compiled on Ubuntu 16.04 LTS (Xenial), the resulting binaries fail with:

```
./AppImageAssistant
Could not mount AppImage
Please see https://github.com/probonopd/AppImageKit/wiki/FUSE
```

The same source code, when compiled on Ubuntu 14.04.1 LTS (trusty), works flawless.

**Note** that you should never use recent OSes to compile AppImageKit as per the documentation, but nevertheless this bug should be fixed. Pull requests welcome.

**Update:** To test, set `sudo chmod 777 /dev/fuse` - does it work then? In this case, it might be a host system problem unrelated to building. Further analysis required.

**Comment by sbobovyc** [comment]
I am seeing the same issue. Looks like the mount point gets removed for some reason.

`execve("././AppImageAssistant", ["././AppImageAssistant"], [/* 65 vars */]) = 0
brk(NULL)                               = 0x2417000
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
mmap(NULL, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f42f8382000
access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
open("/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=219575, ...}) = 0
mmap(NULL, 219575, PROT_READ, MAP_PRIVATE, 3, 0) = 0x7f42f834c000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libfuse.so.2", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\260o\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=243832, ...}) = 0
mmap(NULL, 2339104, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f42f7f23000
mprotect(0x7f42f7f4d000, 2093056, PROT_NONE) = 0
mmap(0x7f42f814c000, 77824, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x29000) = 0x7f42f814c000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libpthread.so.0", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\360`\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=138744, ...}) = 0
mmap(NULL, 2212904, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f42f7d06000
mprotect(0x7f42f7d1e000, 2093056, PROT_NONE) = 0
mmap(0x7f42f7f1d000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x17000) = 0x7f42f7f1d000
mmap(0x7f42f7f1f000, 13352, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f42f7f1f000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libglib-2.0.so.0", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0`\250\1\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=1115136, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f42f834b000
mmap(NULL, 3212632, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f42f79f5000
mprotect(0x7f42f7b04000, 2093056, PROT_NONE) = 0
mmap(0x7f42f7d03000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x10e000) = 0x7f42f7d03000
mmap(0x7f42f7d05000, 1368, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f42f7d05000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libz.so.1", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\360\35\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=104824, ...}) = 0
mmap(NULL, 2199880, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f42f77db000
mprotect(0x7f42f77f4000, 2093056, PROT_NONE) = 0
mmap(0x7f42f79f3000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x18000) = 0x7f42f79f3000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0P\t\2\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=1864888, ...}) = 0
mmap(NULL, 3967488, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f42f7412000
mprotect(0x7f42f75d2000, 2093056, PROT_NONE) = 0
mmap(0x7f42f77d1000, 24576, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x1bf000) = 0x7f42f77d1000
mmap(0x7f42f77d7000, 14848, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0x7f42f77d7000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libdl.so.2", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0\240\r\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=14608, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f42f834a000
mmap(NULL, 2109680, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f42f720e000
mprotect(0x7f42f7211000, 2093056, PROT_NONE) = 0
mmap(0x7f42f7410000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x2000) = 0x7f42f7410000
close(3)                                = 0
access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
open("/lib/x86_64-linux-gnu/libpcre.so.3", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0>\0\1\0\0\0000\25\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=456632, ...}) = 0
mmap(NULL, 2552072, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0x7f42f6f9e000
mprotect(0x7f42f700c000, 2097152, PROT_NONE) = 0
mmap(0x7f42f720c000, 8192, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x6e000) = 0x7f42f720c000
close(3)                                = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f42f8349000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f42f8348000
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f42f8347000
arch_prctl(ARCH_SET_FS, 0x7f42f8348700) = 0
mprotect(0x7f42f77d1000, 16384, PROT_READ) = 0
mprotect(0x7f42f7f1d000, 4096, PROT_READ) = 0
mprotect(0x7f42f720c000, 4096, PROT_READ) = 0
mprotect(0x7f42f7410000, 4096, PROT_READ) = 0
mprotect(0x7f42f79f3000, 4096, PROT_READ) = 0
mprotect(0x7f42f7d03000, 4096, PROT_READ) = 0
mprotect(0x7f42f814c000, 73728, PROT_READ) = 0
mprotect(0x607000, 4096, PROT_READ)     = 0
mprotect(0x7f42f8384000, 4096, PROT_READ) = 0
munmap(0x7f42f834c000, 219575)          = 0
set_tid_address(0x7f42f83489d0)         = 20667
set_robust_list(0x7f42f83489e0, 24)     = 0
rt_sigaction(SIGRTMIN, {0x7f42f7d0bb90, [], SA_RESTORER|SA_SIGINFO, 0x7f42f7d173d0}, NULL, 8) = 0
rt_sigaction(SIGRT_1, {0x7f42f7d0bc20, [], SA_RESTORER|SA_RESTART|SA_SIGINFO, 0x7f42f7d173d0}, NULL, 8) = 0
rt_sigprocmask(SIG_UNBLOCK, [RTMIN RT_1], NULL, 8) = 0
getrlimit(RLIMIT_STACK, {rlim_cur=8192*1024, rlim_max=RLIM64_INFINITY}) = 0
brk(NULL)                               = 0x2417000
brk(0x2438000)                          = 0x2438000
futex(0x7f42f7d05428, FUTEX_WAKE_PRIVATE, 2147483647) = 0
mkdir("/tmp/.mount_cvTeNf", 0700)       = 0
pipe([3, 4])                            = 0
clone(child_stack=0, flags=CLONE_CHILD_CLEARTID|CLONE_CHILD_SETTID|SIGCHLD, child_tidptr=0x7f42f83489d0) = 20668
strace: Process 20668 attached
[pid 20667] close(4 <unfinished ...>
[pid 20668] set_robust_list(0x7f42f83489e0, 24) = 0
[pid 20667] <... close resumed> )       = 0
[pid 20668] close(3 <unfinished ...>
[pid 20667] read(3,  <unfinished ...>
[pid 20668] <... close resumed> )       = 0
[pid 20668] lstat("/proc", {st_mode=S_IFDIR|0555, st_size=0, ...}) = 0
[pid 20668] lstat("/proc/self", {st_mode=S_IFLNK|0777, st_size=0, ...}) = 0
[pid 20668] readlink("/proc/self", "20668", 4095) = 5
[pid 20668] lstat("/proc/20668", {st_mode=S_IFDIR|0555, st_size=0, ...}) = 0
[pid 20668] lstat("/proc/20668/exe", {st_mode=S_IFLNK|0777, st_size=0, ...}) = 0
[pid 20668] readlink("/proc/20668/exe", "/media/storage/AppImageKit/AppIm"..., 4095) = 44
[pid 20668] lstat("/media", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
[pid 20668] lstat("/media/storage", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
[pid 20668] lstat("/media/storage/AppImageKit", {st_mode=S_IFDIR|0775, st_size=4096, ...}) = 0
[pid 20668] lstat("/media/storage/AppImageKit/AppImageAssistant", {st_mode=S_IFREG|0755, st_size=1310720, ...}) = 0
[pid 20668] lstat("/media", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
[pid 20668] lstat("/media/storage", {st_mode=S_IFDIR|0755, st_size=4096, ...}) = 0
[pid 20668] lstat("/media/storage/AppImageKit", {st_mode=S_IFDIR|0775, st_size=4096, ...}) = 0
[pid 20668] lstat("/media/storage/AppImageKit/AppImageAssistant", {st_mode=S_IFREG|0755, st_size=1310720, ...}) = 0
[pid 20668] open("/media/storage/AppImageKit/AppImageAssistant", O_RDONLY) = 3
[pid 20668] lstat("/tmp", {st_mode=S_IFDIR|S_ISVTX|0777, st_size=20480, ...}) = 0
[pid 20668] lstat("/tmp/.mount_cvTeNf", {st_mode=S_IFDIR|0700, st_size=4096, ...}) = 0
[pid 20668] lstat("/tmp/.mount_cvTeNf", {st_mode=S_IFDIR|0700, st_size=4096, ...}) = 0
[pid 20668] lseek(3, 32768, SEEK_SET)   = 32768
[pid 20668] read(3, "\350}`\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\366\35@\0\0\0\0\0"..., 2048) = 2048
[pid 20668] lseek(3, 37392, SEEK_SET)   = 37392
[pid 20668] read(3, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 2048) = 2048
[pid 20668] lseek(3, 37632, SEEK_SET)   = 37632
[pid 20668] read(3, "\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 2048) = 2048
[pid 20668] lseek(3, 339968, SEEK_SET)  = 339968
[pid 20668] read(3, "\267\362\370\275xn\31\1\10,\212\326\357;\345\275\230\337\361\23\353H\273\274S\3\374cbf\34\313"..., 2048) = 2048
[pid 20668] lseek(3, 32768, SEEK_SET)   = 32768
[pid 20668] read(3, "\350}`\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\366\35@\0\0\0\0\0"..., 2048) = 2048
[pid 20668] lseek(3, 34816, SEEK_SET)   = 34816
[pid 20668] read(3, "\20\0\0\0\0\0\0\0\20\0\0\0\0\0\0\0\204\0\0\0\1\0\0\0\6\0\0\0\0\0\0\0"..., 2048) = 2048
[pid 20668] lseek(3, 36864, SEEK_SET)   = 36864
[pid 20668] read(3, "\377CD001\1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0"..., 2048) = 2048
[pid 20668] rmdir("/tmp/.mount_cvTeNf") = 0
[pid 20668] exit_group(5)               = ?
[pid 20667] <... read resumed> "", 1)   = 0
[pid 20668] +++ exited with 5 +++
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=20668, si_uid=1000, si_status=5, si_utime=0, si_stime=0} ---
open("/tmp/.mount_cvTeNf", O_RDONLY)    = -1 ENOENT (No such file or directory)
fstat(1, {st_mode=S_IFIFO|0600, st_size=0, ...}) = 0
write(1, "Could not mount AppImage\nPlease "..., 87Could not mount AppImage
Please see https://github.com/probonopd/AppImageKit/wiki/FUSE
) = 87
exit_group(1)                           = ?
+++ exited with 1 +++
`

**Comment by bartbes** [comment]
I'm not sure if this is the same issue, but I'll post anyway, since I've got some more information.

I got a broken AppImage built by someone using ubuntu 16.04.1, and I found out that it simply wasn't a valid iso file, the header `CD001` wasn't at position 32769 (according to `grep -o -a -b 'CD001'`), where it should be. I then extracted the launcher using `objcopy test.AppImage launcher` and noticed the launcher was too big to fit in those 32768 bytes, probably causing the issue in the first place. Trying to correct for this, by removing the launcher and adding the correct padding yielded a mountable, though unreadable iso image, presumably the actual data had been corrupted, and I just managed to find something that looked enough like an iso to get a directory listing.

I'm not sure what would cause the launcher's size to grow between ubuntu 14.04 and 16.04, but I guess it did. Note that the binary was stripped (and `strip -s` had no effect).

**Comment by probonopd** [comment]
Excellent observation @bartbes, thank you very much. Question now: How to get the runtime.c binary back to its original size. (Although, again, it shouldn't be built on such new systems anyway for portability reasons.)

**Comment by probonopd** [comment]
I can confirm that this is the case on Ubuntu 16.04:

```
sudo apt-get -y install git
git clone https://github.com/probonopd/AppImageKit.git
cd AppImageKit
./build.sh
ls -l runtime
-rwxrwxr-x 1 me me 35856 Aug 19 09:58 runtime
```

35856 > 32768 = Issue!

**Comment by thopiekar** [comment]
Works now, like mentioned in #221
