### ISSUE TITLE
Gnome integration

### ISSUE THREAD

**Issue by chrisnharvey** [probonopd/AppImageKit#20]
Hey,

Great work on AppImageKit, it is a brilliant way to make Linux apps simple for end-users.

I'm actually building a Linux distro based on the AppImage concept, which will use AppImages as the primary way to install applications.

I saw a video on YouTube, which I believe you created, please correct me if I'm wrong: https://www.youtube.com/watch?v=uNmYrxjTkek

I'm really interested in using this integration, but I can no longer find any reference to it on the portablelinuxapps.org website.

Is there anywhere I can find the gnome integration, and/or the source code for it?

**Comment by probonopd** [comment]
Indeed I have moved away from the concept of having to have some "runtime" component in the OS. Instead things like the app icon (and, possibly, .desktop files) could be handled at the first runtime of the AppImage. 

The integration from the video is appimaged, a python-based daemon, which is available at http://portablelinuxapps.org/packages/deb/appimaged/

**Comment by probonopd** [comment]
Possibly you might be interested in https://github.com/probonopd/SystemImageKit for the "system" part of your distribution too.

**Comment by Manouchehri** [comment]
@chrisnharvey There's also [CARE](http://reproducible.io/) which you might find interesting.

I would suggest using another distro's package repository and locating dependencies through that. Dependency hell isn't something you want to have to deal with.

**Comment by probonopd** [comment]
AppImages can be created from deb or rpm repositories, and "Dependency hell" is what AppImageKit is fighting against ;-) Using CARE to create the AppImage is also a possibility; but probably this will include more in the AppImage than necessary. What is really important is that you test your AppImage on a variety of (reasonably old) distros.

**Comment by chrisnharvey** [comment]
@probonopd SystemImageKit looks great, looks like we're both on the same page in terms of unnecessary OS/app complexity. I'm going to give it a go with Fedora 22 (beta) now. May I ask how updates work with SystemImageKit? Also, is it still possible to use a package manager like yum or apt-get using SystemImageKit?

@Manouchehri CARE certainly looks interesting, I'm going to read up on it to see if it can do what I'm hoping to achieve.

I'm basing my distro on Fedora 22. Mainly because of its wide range of packages and the Anaconda installer which in my opinion is the most user-friendly OS installer out there, and also because I certainly do not want to reinvent the wheel by building the OS from scratch when there are plenty of other distros out there that already have the required packages.

My main goal with my distro is to make it simple for end-users to install, use and maintain/update, but also flexible enough for developers to extend. Which is why I like the concept of keeping everything self-contained.

**Comment by probonopd** [comment]
With SystemImageKit you upgrade the distro by exchanging its ISO file. When Fedora 22 final comes out, you simply pop in the new ISO and boot that. Until then, you can put in the nightly ISO images. While it is still possible to use a package manager like yum or apt-get, any changes made by it will be discarded after a reboot. Something I like very much, because this way the system always stays in its original condition.

**Comment by chrisnharvey** [comment]
I too like this concept, it pretty much means that no matter what you do to your system, all will be fine after a reboot. Could I maybe, write a "System Update" app, which can download the latest ISO build from my server, then overwrite the iso file with the new one?

**Comment by chrisnharvey** [comment]
SystemImageKit works great on Fedora 22, however, the initial setup screen shows up every time I boot, and for some reason the setup does not adhere to the language I have set.

**Comment by probonopd** [comment]
Absolutely you could write a "System Update" app, which can download the latest ISO build. You could even use something like http://zsync.moria.org.uk (Ubuntu has zsync files for their nightly builds) so that you don' t have to download the entire ISO but only the parts that have changed. This can increase download/update speed and reduce bandwidth.

**Comment by probonopd** [comment]
> SystemImageKit works great on Fedora 22, however, the initial setup screen shows up every time I boot, and for some reason the setup does not adhere to the language I have set.

This is a bug, please file it with SystemImageKit

**Comment by chrisnharvey** [comment]
I'm closing this issue as my question was answered.

Thanks.

**Comment by chrisnharvey** [comment]
Hi, I'm still interested in using appimaged and building upon it.

I had appimaged working perfectly on my 32-bit Arch VM, but I'm having an issue with ```cmginfo``` on my 64-bit VM as ```cmginfo``` is compiled for x86.

Is there any source code or a 64-bit binary for ```cmginfo```?

**Comment by probonopd** [comment]
It has been some time... Perhaps it's somewhere on https://code.google.com/p/klikclient/source/browse/

**Comment by RazZziel** [comment]
Is `cmginfo` of any use nowadays?
The only appimaged I see in that repo is https://code.google.com/p/klikclient/source/browse/trunk/client/trunk/klikd/src/klikd.cpp, which seems to run "klik sync <directories>" each time a file is added, removed or modified.

@chrisnharvey, I love your idea, and as former writer of the klikd tool, I'd love to help, as far as my very limited time allows me. I've actually been toying with the idea of rescuing the little daemon from oblivion lately, even if just for personal use.
I also maintain http://PortableLinuxGames.org, so if you want some games in your distro let me know ;)

**Comment by RazZziel** [comment]
Basic bash script to watch a directory and create/remove desktop entries as modern AppImages are added or removed from ~/Applications: https://gist.github.com/RazZziel/fcc919803d1951a13ed4

Worksforme (TM), but it depends on inotify-tools and xdg-tools, so a second iteration should probably be closer to the metal to have fewer dependencies (specially inotify-tools).

The .desktop entry should ideally be created by the AppImage itself, using some kind of special parameter or environment variable (like `--icon`, but without being able to collide with the app parameters, I think we discussed that some time ago but I can't remember where), but that won't be compatible with current AppImages

**Comment by probonopd** [comment]
Agree @RazZziel

**Comment by RazZziel** [comment]
The script has been moved to https://github.com/RazZziel/PortableLinuxGames/blob/master/monitorAppImages.sh

**Comment by derixithy** [comment]
I'm trying to integrate this in my Porteus setup, link above does not work, but found a working one (for now?).
https://github.com/probonopd/AppImageKit/tree/master/AppImageMonitor.AppDir

Thank you all for your hard work on this awesome little tool.

**Comment by probonopd** [comment]
We are still working on it, contributions welcome. See my ticket on AppImageMonitor.

**Comment by probonopd** [comment]
> Is there any source code or a 64-bit binary for ```cmginfo```?

Thy `isoinfo`. It should do the same thing.
