### ISSUE TITLE
[desktopintegration] spaces in the Exec and TryExec are not escaped

### ISSUE THREAD

**Issue by develar** [probonopd/AppImageKit#200]
For `Exec` we must use quotes.
For `TryExec` quotes is not supported, so, space must be replaced  to `\s`.

https://askubuntu.com/questions/175404/how-to-add-space-to-exec-path-in-a-thumbnailer-descrption/175567

I spend hour to understand stupid unclear error `There was an error launching the application`.

No, I am not going to open PR now — in the electron-builder I reverted my latest change and now electron-builder uses package.json name (without spaces) instead of product name. It is better for Linux, I think.

**Comment by probonopd** [comment]
Thanks @develar for analyzing and reporting this.

**Comment by probonopd** [comment]
Point in case: If the AppImage has a name like `ser-player-1.5.2.glibc2.4-x86_64(1).AppImage` then it currently breaks:

```
/home/me/.local/share/applications/appimagekit-ser-player.desktop: error: value "/home/me/Downloads/ser-player-1.5.2.glibc2.4-x86_64(1).AppImage %U" for key "Exec" in group "Desktop Entry" contains a reserved character '(' outside of a quote
/home/me/.local/share/applications/appimagekit-ser-player.desktop: error: value "/home/me/Downloads/ser-player-1.5.2.glibc2.4-x86_64(1).AppImage %U" for key "Exec" in group "Desktop Entry" contains a reserved character ')' outside of a quote
Error on file "/tmp/.mount_8SuVY2/ser-player.desktop": Failed to validate the created desktop file
```
