### ISSUE TITLE
Molotov Appimage doesn't work

### ISSUE THREAD

**Issue by Paviluf** [probonopd/AppImageKit#201]
Hello,

Molotov AppImage doesn't work on my laptop. I don't know if the problem come from the laptop or from the AppImage. I don't have any error message or output in the terminal. Nothing appear on the screen too but the Molotov processes are running in the background. 

On my desktop the app work perfectly. The 2 computers are on Fedora 24 (both up to date). My desktop have a Nvidia (GT430 with the proprietary drivers) GPU and the laptop (HP Chromebook 14) have an Intel CPU / iGPU.

http://www.molotov.tv/download

Is there a way to have some debug message ?

Thanks !

**Comment by probonopd** [comment]
Please report this bug to Molotov, not to AppImageKit. I do not know about Molotov. Thanks. 
Reopen this if the Molotov developers think this is caused by AppImageKit.
