### ISSUE TITLE
AppImageAssistant GUI broken on some systems

### ISSUE THREAD

**Issue by Jackz-123** [probonopd/AppImageKit#202]
I created an AppDir which contains all the necessary folders and files and while trying to create the AppImage using AppImageAssistant, I get the following error:

`/tmp/.mount_pOLu3J/AppImageAssistant:209: GtkWarning: IAgtk_assistant_set_page_header_image: assertion 'child != NULL' failed
self.set_page_header_image(vbox, gtk.gdk.pixbuf_new_from_file(application_icon))
/tmp/.mount_pOLu3J/AppImageAssistant:227: GtkWarning: IAgtk_assistant_set_page_title: assertion 'child != NULL' failed
self.set_page_title(icon, "An error has occured")`

What is this??

**Comment by probonopd** [comment]
Please invoke the AppImageAssistant like this:

```
./AppImageAssistant /path/to/input/AppDir /path/to/output/AppImage
```

**Comment by Jackz-123** [comment]
Ohh!! Thankyou..So it doesn't work with the AppImageAssistant GUI?

**Comment by probonopd** [comment]
GUI seems broken on some systems

**Comment by probonopd** [comment]
python-gtk should be properly bundled in the AppImage

**Comment by probonopd** [comment]
AppImageAssistant hast been replaced by `appimagetool`. Use it instead.
