### ISSUE TITLE
AppImageAssistant failing to open shared libncurses on Fedora

### ISSUE THREAD

**Issue by ePirat** [probonopd/AppImageKit#204]
Installing from Source or starting the AppImage for AppImageAssistant results in the following error on Fedora 24:

```
$ ./AppImageAssistant 
Traceback (most recent call last):
  File "/tmp/.mount_8Ep42L/AppImageAssistant", line 87, in <module>
    import  gtk, vte
ImportError: libncurses.so.5: cannot open shared object file: No such file or directory
```

I was able to work around this by symlinking /usr/lib64/libncurses.so.6 to /usr/lib64/libncurses.so.5

**Comment by probonopd** [comment]
https://github.com/probonopd/AppImageKit/issues/202
