### ISSUE TITLE
Failed to load Pepper Flash plugin in an Electron app bundled in an AppImage

### ISSUE THREAD

**Issue by lbssousa** [probonopd/AppImageKit#206]
Please consider the following sample project: https://github.com/hokein/electron-sample-apps/tree/master/pepper-flash-plugin

I've cloned it, copied Flash plugin to app folder, completed the remaining steps to be able to build it with electron-builder and built it with AppImage target.

However, when I try to run the AppImage, it doesn't load the plugin. Instead, it renders a message like "Unable to load the plugin"

Here is the output of my `ldd libpepflashplayer.so` command:
```
        linux-vdso.so.1 (0x00007ffe073bb000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007fb3837f1000)
        librt.so.1 => /lib64/librt.so.1 (0x00007fb3835e9000)
        libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007fb383260000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fb382f5c000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fb382d45000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fb382b27000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fb382785000)
        /lib64/ld-linux-x86-64.so.2 (0x00005640c7d3a000)
```

Should I bundle some of these libs into my AppImage?

**Comment by probonopd** [comment]
As a general rule, you should bundle all except [these](https://github.com/probonopd/AppImages/blob/master/excludelist) libraries.

For further debugging, can you post a link to a GitHub repo where you have "cloned it, copied Flash plugin to app folder, completed the remaining steps to be able to build it with electron-builder"?

**Comment by develar** [comment]
@probonopd Actually it is not tool or AppImage issue — https://github.com/electron-userland/electron-builder/issues/644#issuecomment-237650292

**Comment by probonopd** [comment]
Which probably means that if you want to bundle it, you would have to edit the generated AppImage manually: 
1. Unpack it
2. Change its contents as you like
3. Repack as an AppImage
