### ISSUE TITLE
AppRun bash implementation segfaults

### ISSUE THREAD

**Issue by ePirat** [probonopd/AppImageKit#207]
The AppRun written in bash that is used for Chromium does not seem to work well, is this expected?
When I bundle my app using the bash implementation of AppRun, and start the resulting AppImage on another machine (running a higher version of the OS than what I used to build my app) it segfaults.

Everything works fine using the binary implementation of AppRun.

**Comment by probonopd** [comment]
It is expected that the custom AppRun for Chromium does not work for other, non-Chromium apps. Please either use the binary AppRun instead or write your own version in bash or any other language if you have special needs.
