### ISSUE TITLE
ImportError: libpng12.so.0: file not found [Solved]

### ISSUE THREAD

**Issue by tele1** [probonopd/AppImageKit#21]
Binary used from
http://portablelinuxapps.org/
on Fedora Mate 64bit

$ ./"AppDirAssistant 0.3.3-64bit"
Traceback (most recent call last):
  File "./bin//appimager", line 16, in <module>
    import AppImageKit, AppImageKit.AppDir, AppImageKit.timesavers, 

AppImageKit.xxdg.DesktopEntry, AssistantKit # Needs to be bundled
    File "/tmp/.mount_ECcD3T/usr/bin/AssistantKit/__init__.py", line 1, in <module>
    import os, sys, gtk, vte, threading
   ImportError: libpng12.so.0: file not found
  [@localhost Pobrane]$ uname -a
  Linux localhost.localdomain 3.17.4-301.fc21.x86_64 #1 SMP Thu Nov 27 19:09:10 UTC 2014   x86_64 x86_64 x86_64 GNU/Linux

**Comment by Manouchehri** [comment]
You need to install libpng12.

https://duckduckgo.com/?q=libpng12.so.0

**Comment by tele1** [comment]
Yes, this is true, exist in "Yum Extender, so I can install.
