### ISSUE TITLE
libfuse2 is not present in common docker images

### ISSUE THREAD

**Issue by phillipao** [probonopd/AppImageKit#211]
I'm testing an AppImage (created on CentOS 6) on docker images, but the official ubuntu and debian images are missing libfuse2 and libglib-2.0. Should AppRun statically compile those libs, or are these images too niche? It would be nice for the runtime to rely only on packages present in the debian [base system](https://www.debian.org/doc/debian-policy/ch-binary.html#s3.7). (tbh I don't know much about all of this, and it could be that these docker images don't meet the minimal base system. But I looked at the required and important lists at least and didn't see fuse in there).

**Comment by probonopd** [comment]
A working FUSE setup is a requirement to run AppImages directly, and I know no way around this (at least, without requiring root rights). If FUSE is not an option, then you can a) extract the contents of the AppImage, e.g., using libarchive (it is an ISO), or b) loop-mount it, and execute the `AppRun` executable contained therein.

This is explained on https://github.com/probonopd/AppImageKit/wiki/FUSE. Please reopen this ticket if the explanation is unclear or if you know how to achieve the same result without the need for FUSE at runtime.

**Comment by phillipao** [comment]
Yes, that's clear, thanks. I can accept if you say that it needs FUSE and that there's nothing that can be done about it (though I do still wonder whether static linking is an option). The problem with the workaround is that it's exactly the kind of prerequisite that I'm hoping to avoid by going with AppImage.

I'm using an Ubuntu 14.04, and it looks like FUSE was preinstalled on that. I suspect that I'm going to find that it's also there on the Debian desktop image. And if that's the case, then I can probably just accept that, and maybe a Debian desktop Docker image can be created.

**Comment by probonopd** [comment]
Yes, as far as I know all modern desktop distributions come with FUSE installed and enabled.

Just having/statically linking libfuse is not enough as it isn't sufficient for a working FUSE setup.

**Comment by shoogle** [comment]
@phillipao you raise a good point about having a Docker image equivalent to the Debian (or CentOS) LiveISO. I think this is something we should look into creating as a development environment for creating AppImages. There is no general "Linux base system", so we should create one by taking the common default packages from the major distributions and putting them into a single Docker image. Debian would be a good choice due to its support for many architectures.
