### ISSUE TITLE
Website: add http://discourse.appimage.org/

### ISSUE THREAD

**Issue by probonopd** [probonopd/AppImageKit#214]
People seem to like our forum at http://discourse.appimage.org/ so let's add it to the homepage. @kskarthik want to integrate it?

**Comment by kskarthik** [comment]
yes :smiley:

**Comment by kskarthik** [comment]
Hey! how about adding discourse (community) link in nav bar too ? 

![com](https://cloud.githubusercontent.com/assets/11899221/17772491/ccb5eaf2-6566-11e6-9237-df7b1c9d8c53.png)

**Comment by probonopd** [comment]
Great idea, go ahead!

**Comment by kskarthik** [comment]
Also, please choose a different background since the current one is dominating the appimage logo. I applied one. look at it & tell me ur opinion

![bgn](https://cloud.githubusercontent.com/assets/11899221/17798542/b4f8d9b8-65ef-11e6-8e46-1c8387c09459.png)
