### ISSUE TITLE
Gtk library incompatibility triggers crash in Fedora 24 and Ubuntu 16.04

### ISSUE THREAD

**Issue by markummitchell** [probonopd/AppImageKit#217]
Hello,
Thanks for the great framework. It has been very helpful.

I build an AppImage (markummitchell/engauge-digitizer) in Centos 6. In Fedora 24 and Ubuntu 16.04 the AppImage crashes due to gtk library conflicts. In ubuntu the message is '../libunity-gtk-module.so: undefined symbol: g_settings_new'.

An easy workaround, using a different style if the default fails, would be the following steps:

myapp.AppImage
if [ $? -ne 0 ; then
  myapp.AppImage -style=plastique
fi

Is there a way to do these steps, or some equivalent, in an AppImage?
-MarkM

**Comment by probonopd** [comment]
Thanks for the hint. You could change usr/bin/engauge.wrapper like this:

```
atexit()
{
if [ $NUMBER_OF_ARGS -eq 0 ] ; then
  exec "${BIN}" -style=plastique
else
  exec "${BIN}" "${args[@]}" -style=plastique
fi
}
```

**Comment by markummitchell** [comment]
This script snippet for engauge.wrapper works for Fedora (no hang but broken menus) and Ubuntu (outright crash) due to Qt problems with GTK on those systems.

Thanks again!
-------------------------------------------------------------------------------------------------
# Retry if first execution crashes - we assume it is the gtk library crash
# in Ubuntu. Fedora does not crash but just shows corrupted menus. Both OSes
# are fixed by using a different style
atexit()
{
set +e
if [ -e /etc/os-release ]; then
    if grep -q Fedora /etc/os-release; then
	echo Fedora operating system may require -style=plastique added to the command line for the menus to work correctly
    fi
fi

if [ $NUMBER_OF_ARGS -eq 0 ] ; then
  (exec "${BIN}") || (exec "${BIN}" -style=plastique)
else
  (exec "${BIN}" "${args[@]}") || (exec "${BIN}" "${args[@]}" -style=plastique)
fi
}
