### ISSUE TITLE
return os.stat(filename).st_ctime

### ISSUE THREAD

**Issue by tele1** [probonopd/AppImageKit#22]
Fedora Mate 21   64bit
binary download from
http://portablelinuxapps.org/

$ ./"AppDirAssistant 0.3.3-64bit"
Traceback (most recent call last):
  File "./bin//appimager", line 263, in <module>
    main()
  File "./bin//appimager", line 249, in main
    then = datetime.datetime.fromtimestamp(os.path.getctime(filefortime))
  File "/usr/lib64/python2.7/genericpath.py", line 64, in getctime
    return os.stat(filename).st_ctime
OSError: [Errno 2] file not found: '/usr/bin/ld'

**Comment by Manouchehri** [comment]
Can you paste the output of this?

`file $(which ln)`

**Comment by tele1** [comment]
$ file $(which ln)
/usr/bin/ln: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=6adc4b033beac0e1ce5ae7233398868be1b3c439, stripped

**Comment by tele1** [comment]
create symlink ?

**Comment by tele1** [comment]
Depedency is missing , but I don't know what.
However I installed cmake and cmake-fedora with cmake dependecy and now binary working

$ ./"AppDirAssistant 0.3.3-64bit"
0
[<class '__main__.WelcomePage'>, 'Welcome']
Preparing <WelcomePage 'Welcome'>

**Comment by Manouchehri** [comment]
This is probably more of a question for Fedora rather than AppImageKit. Generally there's a common "dev" group of packages that you'll have to install before attempting to compile/run anything aside from pre-packaged software. 

For Fedora/Red Hat/CentOS, I believe you need to do this.

`yum groupinstall 'Development Tools'`
