### ISSUE TITLE
Add stars button to homepage

### ISSUE THREAD

**Issue by probonopd** [probonopd/AppImageKit#226]
https://ghbtns.com/
@kskarthik want to have a go? I'd say rather large and rather somewhere at the top right?

**Comment by kskarthik** [comment]
Top right sounds good replacing the github cat icon

**Comment by probonopd** [comment]
Yes, or maybe you have a better idea.

**Comment by kskarthik** [comment]
ok. I will send you a demo soon :-)

**Comment by kskarthik** [comment]
@probonopd  here you go :) https://rawgit.com/kskarthik/AppImageKit/gh-pages/index.html

**Comment by probonopd** [comment]
Thanks. Not really working tho, linking to wrong project...

**Comment by kskarthik** [comment]
it should work https://github.com/kskarthik/AppImageKit/commit/1b0372e85ba3b72c60e9db6e43a65917f3f0787f

**Comment by kskarthik** [comment]
force refresh your browser @probonopd it will work

**Comment by probonopd** [comment]
Still gives me https://github.com/twbs/bootstrap/ - maybe a CDN thing?

**Comment by kskarthik** [comment]
Try again now.. I have no such issue

**Comment by probonopd** [comment]
Works now. Maybe it is a bit too large, what do you think?

**Comment by kskarthik** [comment]
PR https://github.com/probonopd/AppImageKit/pull/227
