### ISSUE TITLE
Unable to launch AppImageAssistant on x64 Ubuntu 16.04 XFCE & Fedora 24 LXDE

### ISSUE THREAD

**Issue by kskarthik** [probonopd/AppImageKit#228]
I got this following error on both the distro's 

`Traceback (most recent call last):
  File "/tmp/.mount_BlxWKe/AppImageAssistant", line 87, in <module>
    import  gtk, vte
ImportError: No module named gtk`

I think it's lack of gtk lib. Better to statically link it.

**Comment by probonopd** [comment]
https://github.com/probonopd/AppImageKit/issues/202

**Comment by kskarthik** [comment]
@probonopd i am getting `Error executing 'start.sh'; return code: -1` from a built appimage. I am trying to invoke a script start.sh in  usr/bin/firefox which fires up ./firefox-bin binary in the same folder 

I tried this method you described

**Comment by probonopd** [comment]
Probably unrelated to this ticket, please open a new one
