### ISSUE TITLE
Remove GUI from AppImageAssistant

### ISSUE THREAD

**Issue by probonopd** [probonopd/AppImageKit#229]
Now that AppImageKit is geared toward upstream application developers to produce upstream packaged AppImages in continuous build workflows, I will remove the GUI from AppImageAssistant unless someone really cares about it and steps up to maintain it. Currently it is not properly bundled and broken as a result for many systems, rarely used, and has not been worked on in years.

**Let me know if you object to this. Otherwise I will remove the GUI.**

**Comment by probonopd** [comment]
- https://github.com/probonopd/AppImageKit/issues/202
- https://github.com/probonopd/AppImageKit/issues/85
- https://github.com/probonopd/AppImageKit/issues/6
- https://github.com/probonopd/AppImageKit/issues/107

**Comment by kskarthik** [comment]
nice decision, GUI is causing problems. CLI is good enough & more lightweight too ;-)

**Comment by LeCharlatan** [comment]
I don't see any objection. I used GUI when start to use AppImageKIT but now I rather like commands use, so GUI became some kind of useless :)

**Comment by probonopd** [comment]
The current AppImageKit will eventually be replaced by what is currently in the [appiamgetool](https://github.com/probonopd/appimagetool) repository. As you can see, `appimagetool` offers more advanced functionality (e.g., embedded digital signatures, squashfs-based type 2 AppImages), but no GUI anymore.

**Comment by probonopd** [comment]
AppImageAssistant has been replaced by `appimagetool`. Use it instead.
