### ISSUE TITLE
Replace xorriso by tiny C program using libarchive

### ISSUE THREAD

**Issue by probonopd** [probonopd/AppImageKit#230]
Given that libarchive can write zisofs, why not use that. Would help us get rid of the large xorriso dependency.

https://github.com/libarchive/libarchive/issues/780
https://github.com/libarchive/libarchive/wiki/FormatISO9660#Writing_ISO9660_images

**Comment by develar** [comment]
`xorriso` supports file mapping (if we build app image from different sources) (and `move`, https://github.com/electron-userland/electron-builder/blob/master/src/targets/appImage.ts#L53), does lib archive support it?

**Comment by develar** [comment]
It will be great if electron-builder will use app image tool to build, but currently file mappings are not supported and, so, electron-builder uses `xorriso` directly.

**Comment by probonopd** [comment]
I am working on appimagetool, and it is still a work-in-progress. What do you need file mappings for?

**Comment by develar** [comment]
> What do you need file mappings for?

Tool (`electron-builder`) should not modify original application source. Source for all formats is the same. Pack it once, and then build in various distributable formats in parallel.

So, AppImage specific desktop file or icon or any other specific for format files, located in the temp directory. Or, even more — file name is different.

```ts
"-map", path.join(__dirname, "..", "..", "templates", "linux", "AppRun.sh"), "/AppRun",
```

```ts
 "-move", `/usr/bin/${appInfo.productFilename}`, appExecutableImagePath,
```

```ts
for (let [from, to] of (await this.helper.icons)) {
      args.push("-map", from, `/usr/share/icons/default/${to}`)
    }
```

FPM suppors file mappings — https://github.com/jordansissel/fpm/wiki/Source:-dir#mapping-requires-fpm--0440

snap supports file mappings — http://snapcraft.io/docs/reference/plugins/dump

**Comment by probonopd** [comment]
Copying everything to a `/tmp` location would not be an option?

**Comment by develar** [comment]
> would not be an option?

* space requirement
* time requirement
* another source of errors (file copying)

For me it looks like a dirty hack. File mappings is a core concept for me — we build app from different sources. Copying all files to stage dir only because tool doesn't support it — only as workaround.

**Comment by probonopd** [comment]
On the plus side, people could test and/or customize the AppDir that way before it gets converted into an immutable AppImage.

**Comment by probonopd** [comment]
`AppImageAssistant` and its use of `xorriso` are replaced by `appimagetool` and `mksquashfs`, respectively.
