### ISSUE TITLE
Error launching shell script 

### ISSUE THREAD

**Issue by kskarthik** [probonopd/AppImageKit#232]
i am getting Error executing 'start.sh'; return code: -1 from a built appimage. I am trying to invoke a script start.sh in usr/bin/firefox which fires up firefox-bin binary in the same folder

I tried this method you described to launch shell scripts from appimage

This is the below code i used in start.sh

#!/bin/sh
HERE=$(firefox $(readlink -f "${0}"))
echo "${HERE}" 

"${HERE}/firefox-bin" --no-remote --devtools --profile ./profile

but still i get error launching it. Please help me

**Comment by probonopd** [comment]
Rather than trying to rewrite a Firefox-provided script, why don't you use the `AppRun` from AppImageKit and let that launch firefox from `usr/bin/`?
