### ISSUE TITLE
Improve the AppImageMonitor

### ISSUE THREAD

**Issue by PHPJosh** [probonopd/AppImageKit#235]
I have a few ideas for better integration into the system AppImageMonitor is running on and here is a few of them I plan on working on for my distro and if you like them I  can shoot a pull request once they are done.

1.) The desktop files that it creates should use the currently used Icon theme if it detects a Icon for said app in the theme. if not it should use the .diricon if no other Icon is supplied.

2.) The AppImageMonitor should have an flag to watch an users Download folder and ask if the user wants to install the AppImage to /Applications or ~/Applications folders and if the user decides to install to /Applications should ask for a root or sudo password and set the permissions so only root users can delete these Appimages.

3.) Create service files for various distros so it can be started on boot without much effort on the users part. I have already made a systemd service for my distro and it starts on boot and acts very much like a daemon that runs in the background. 

4.) make AppImageMonitor compatible with any future changes to the kit as for one I know probonopd is planning to swap to squashfs and some other changes so we should start preparing AppImageMonitor for these changes coming as AppImageMonitor is a good thing to keep in the kit for packagers and Distro vendors that may want to intergrate the Kit into other distros.

anymore Ideas would be cool for everyone here

**Comment by probonopd** [comment]
AppImageMonitor has been replaced by `appimaged`. Use it instead.
