### ISSUE TITLE
Sandbox / automatic launcher

### ISSUE THREAD

**Issue by chrisnharvey** [probonopd/AppImageKit#236]
I have been using the AppImage sandbox for a little while now, and I love the idea of being able to sandbox AppImages so I can try them out before I give them executable permissions.

I have modified it slightly to ask me (with zenity) if I want to run the AppImage sandboxed, or give it executable permissions. This way I don't have to manually mark the AppImage executable. I just double click it, and it asks "Do you want to run this AppImage in a sandbox?", clicking yes runs it with bubblewrap, and clicking no marks it executable and launches it normally (removing the step of having to manually mark it executable).

Is this something you'd be interested in adding? If so, I'm happy to submit a PR with my changes.

**Comment by probonopd** [comment]
Well, isn't that a bit too easy to inadvertedly run insecure code from the web? At the very least, the option to run without the sandbox should check the gpg signature first.

**Comment by PHPJosh** [comment]
honestly sand boxing in a integrated environment like for instance the distro i am working on should be default regardless as I am going to have appimages run sandboxed with firejail by default. idk either an app should be sand boxed or not must users would be annoyed to have an app ask them every time to run sand boxed or not

**Comment by probonopd** [comment]
Yes, that's how I see it too, sandboxed by default but the user can select to trust an application so much as to run it outside of the sandbox if he actively chooses to do so.

**Comment by chrisnharvey** [comment]
Agreed, but what about apps that need slightly higher privileges? For example, currently, if I run the Leafpad AppImage with bubblewrap, I can't write any files to disk, which completely defeats the point in the app.

How do you see something like this working?

**Comment by probonopd** [comment]
You could have a directory for each app where it would have read and write access, kinda like what iOS does.

**Comment by chrisnharvey** [comment]
Could there not be some way to allow AppImages to request more access (such as access to the filesystem). Otherwise, for apps like code editors just wouldn't work.

For example, I use the Atom code editor and the GIMP image editor (both as AppImages) for creating websites and apps. If I were to run these sandboxed with no access to the file system, then I would have to store all my website code in the Atom app directory, and the images in the GIMP app directory, or use my file manager to copy the files back and forward for editing. This would be a usability nightmare.

I really like the idea of sandboxing applications for security, but at the moment it seems like we can either sandbox an application and restrict its access to everything, or make the app executable and give it complete access. Shouldn't there be some sort of middle-ground, where an app can request additional access. Like how iOS does with its "Do you want to allow this app to access the camera", "Do you want this app to have access to your location" and so on.

Just wondering what your thoughts are on this?

**Comment by probonopd** [comment]
This is called "portals" and the Gnome/Flatpak guys are working on it, but it needs support from the app which needs to be coded specially. Not aware of a solution for e.g., Qt and other apps. This is very much in development, so I'd say "wait and see".

**Comment by chrisnharvey** [comment]
No problem. I'll close this issue for now then.
