### ISSUE TITLE
AppImageAssistant stacktrace

### ISSUE THREAD

**Issue by ScarlettGatelyClark** [probonopd/AppImageKit#237]
Running command:
['python', '/tmp/.mount_qpib7Z/package', '/home/scarlett/Downloads/build-skanlite-Desktop_Qt_5_7_0_GCC_64bit-Default/src', u'/home/scarlett/Downloads/build-skanlite-Desktop_Qt_5_7_0_GCC_64bit-Default/Application']
child done
/tmp/.mount_qpib7Z/AppImageAssistant:209: GtkWarning: IA__gtk_assistant_set_page_header_image: assertion 'child != NULL' failed
  self.set_page_header_image(vbox, gtk.gdk.pixbuf_new_from_file(application_icon))
/tmp/.mount_qpib7Z/AppImageAssistant:215: GtkWarning: IA__gtk_assistant_set_page_title: assertion 'child != NULL' failed
  self.set_page_title(vbox, "Done")
/tmp/.mount_qpib7Z/AppImageAssistant:216: GtkWarning: IA__gtk_assistant_set_page_type: assertion 'child != NULL' failed
  self.set_page_type(vbox, gtk.ASSISTANT_PAGE_SUMMARY)
/cdrom/casper/filesystem.squashfs
Traceback (most recent call last):
  File "/tmp/.mount_qpib7Z/AppImageAssistant", line 232, in testrun
    shutil.copyfile(os.path.join(os.path.dirname(sys.argv[0]), "unionfs-fuse"), "/tmp/unionfs-fuse")
  File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/tmp/.mount_qpib7Z/unionfs-fuse'
Traceback (most recent call last):
  File "/tmp/.mount_qpib7Z/AppImageAssistant", line 232, in testrun
    shutil.copyfile(os.path.join(os.path.dirname(sys.argv[0]), "unionfs-fuse"), "/tmp/unionfs-fuse")
  File "/usr/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: '/tmp/.mount_qpib7Z/unionfs-fuse'
scarlett@scarlett-neon:~/Downloads/build-skanlite-Desktop_Qt_5_7_0_GCC_64bit-Default/src$ /home/scarlett/AppImageKit/out/AppImageAssistant_5-118-g0c80c7d-x86_64.AppImage
/tmp/.mount_YMNy0u/AppImageAssistant:151: GtkWarning: Unable to locate theme engine in module_path: "adwaita",
  gtk.Assistant.**init**(self)
Checking whether /home/scarlett is an AppDir
Checking whether /home/scarlett is an AppDir
Checking whether /home/scarlett is an AppDir
Checking whether /home/scarlett/Downloads is an AppDir
Checking whether /home/scarlett is an AppDir
Checking whether /home/scarlett/Downloads is an AppDir
Checking whether /home/scarlett/Downloads is an AppDir
Checking whether /home/scarlett/Downloads/build-skanlite-Desktop_Qt_5_7_0_GCC_64bit-Default is an AppDir
Checking whether /home/scarlett/Downloads is an AppDir
Checking whether /home/scarlett/Downloads/build-skanlite-Desktop_Qt_5_7_0_GCC_64bit-Default is an AppDir
Checking whether /home/scarlett/Downloads/build-skanlite-Desktop_Qt_5_7_0_GCC_64bit-Default is an AppDir
Checking whether /home/scarlett/Downloads/build-skanlite-Desktop_Qt_5_7_0_GCC_64bit-Default/src is an AppDir
Application AppDir /home/scarlett/Downloads/build-skanlite-Desktop_Qt_5_7_0_GCC_64bit-Default/src with desktop file /home/scarlett/Downloads/build-skanlite-Desktop_Qt_5_7_0_GCC_64bit-Default/src/default.desktop, executable /home/scarlett/Downloads/build-skanlite-Desktop_Qt_5_7_0_GCC_64bit-Default/src/AppRun and icon /home/scarlett/Downloads/build-skanlite-Desktop_Qt_5_7_0_GCC_64bit-Default/src/default.png
Running command:
['python', '/tmp/.mount_YMNy0u/package', '/home/scarlett/Downloads/build-skanlite-Desktop_Qt_5_7_0_GCC_64bit-Default/src', u'/home/scarlett/Downloads/build-skanlite-Desktop_Qt_5_7_0_GCC_64bit-Default/Application']
child done
/tmp/.mount_YMNy0u/AppImageAssistant:209: GtkWarning: IA__gtk_assistant_set_page_header_image: assertion 'child != NULL' failed
  self.set_page_header_image(vbox, gtk.gdk.pixbuf_new_from_file(application_icon))
/tmp/.mount_YMNy0u/AppImageAssistant:215: GtkWarning: IA__gtk_assistant_set_page_title: assertion 'child != NULL' failed
  self.set_page_title(vbox, "Done")
/tmp/.mount_YMNy0u/AppImageAssistant:216: GtkWarning: IA__gtk_assistant_set_page_type: assertion 'child != NULL' failed
  self.set_page_type(vbox, gtk.ASSISTANT_PAGE_SUMMARY)
/cdrom/casper/filesystem.squashfs

However the Application is created and functions as expected!

**Comment by probonopd** [comment]
Did you see any GUI? (You shouldn't, when you use AppImageAssistant in CLI mode with exactly 2 arguments: the AppDir and the AppImage.)

**Comment by ScarlettGatelyClark** [comment]
yeah the gui was present. Now that we sorted that I was using appimageextract, which you fixed in docs, we should be good on this if I use CLI with correct AppImageAssistant. Closing. Thanks!

**Comment by PHPJosh** [comment]
ok think theres a bug in the bundle script after my pull request  with Arch fixes in it. apparently I didn't didn't do the else statement right so just swapped it to 3 if statements like the build script and tested in a VM should work will push the update to my fork and open a pull request

**Comment by PHPJosh** [comment]
nvm thats not the issue as from your log you are missing unionfs-fuse binary and thats not one the ones I skipped copying in the bundle script so I did the else statment right :P i too used to PHP and it confused me at first til i noticed that binary i didn't even skip on the Arch linux Builds

**Comment by probonopd** [comment]
Yes please do @PHPJosh

**Comment by PHPJosh** [comment]
look in log its a file i had skipped in the script for arch so its not the bundle script. some how its did not bundle the unionfs-fuse binary in his build

**Comment by PHPJosh** [comment]
I only removed the VTE libs from Arch Binarys

**Comment by probonopd** [comment]
AppImageAssistant hast been replaced by `appimagetool`. Use it instead.
