### ISSUE TITLE
VLC does not work on Centos 6.6

### ISSUE THREAD

**Issue by fanoI** [probonopd/AppImageKit#239]
This error is returned into the terminal:

./VLC-3.0.0.git4ff2515.glibc2.17-x86_64.AppImage: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by ./VLC-3.0.0.git4ff2515.glibc2.17-x86_64.AppImage)

**Comment by probonopd** [comment]
This AppImage requires at least glibc 2.17 as the title suggests, which CentOS 6 does not have. This AppImage was not made for CentOS 6 target systems.

**Comment by fanoI** [comment]
So AppImage does not resolve the Linux distribution fragmentation problem in the end...

**Comment by probonopd** [comment]
Whoever creates an AppImage has to choose which target systems to build for. Like on Windows, if the developer targets XP then it will run on XP, if not, then not.

**Comment by PHPJosh** [comment]
i would assume the older the base target system is the more distros it will run on

**Comment by probonopd** [comment]
Precisely!
