### ISSUE TITLE
.gitignore should exclude compiled PYC files

### ISSUE THREAD

**Issue by TC01** [probonopd/AppImageKit#24]
Hi,

While working on the ```mock-appdir``` tool (#23), I noticed that you aren't excluding the compiled Python files (*.pyc) from version control. For example, [this blob](https://github.com/probonopd/AppImageKit/blob/master/AppImageAssistant.AppDir/xdgappdir.pyc).

Is there a reason for this? It makes writing code, testing it, and then committing it slightly messier, because the *.pyc files change and are flagged as being "modified" by git.

**Comment by RazZziel** [comment]
Indeed I think there's some files that should be excluded, starting the the .pyc files and maybe following with some generated binaries, like the runtime.

**Comment by Manouchehri** [comment]
I believe I accidentally included some binaries in `AppDirAssistant.AppDir` when I checked it in a few months ago. Those can be safely ignored as well I think.
