### ISSUE TITLE
Scribus does not run on Centos 6.6

### ISSUE THREAD

**Issue by fanoI** [probonopd/AppImageKit#240]
This error is returned:

fuse: failed to exec fusermount: Permission denied
Could not mount AppImage
Please see https://github.com/probonopd/AppImageKit/wiki/FUSE

I should run it as root?

**Comment by probonopd** [comment]
Do you have a working FUSE setup as described on the page you linked above?
Root is not necessary once you have a working FUSE setup.

**Comment by fanoI** [comment]
I have not the root password in this machine I expected to click on the downloaded image and run it directly without the need to install anything else.

My distro has a kernel and libc so old that probably FUSE does not exist...

**Comment by probonopd** [comment]
In this case, you can extract the contents of the ISO AppImage with a tool like bsdtar.

**Comment by probonopd** [comment]
Please feel free to reopen if the problem persists.
