### ISSUE TITLE
chromium and atom doesn't work on elementary os loki 0.4

### ISSUE THREAD

**Issue by satrioaw** [probonopd/AppImageKit#241]
I guess elementary OS loki 0.4 is same with ubuntu 16.04 but in case running chromium and atom doesn't work  withi this message

```
satrio@laptop:~/appimage$ ./Atom-1.9.9-x86_64.AppImage 
/tmp/.mount_wUWosN/usr/bin/atom: error while loading shared libraries: libgconf-2.so.4: cannot open shared object file: No such file or directory

```

**Comment by probonopd** [comment]
Both Chromium and Atom run fine on Ubuntu 16.04 LTS (Xenial Xerus), which has `/usr/lib/x86_64-linux-gnu/libgconf-2.so.4` installed by default. Try installing the `libgconf-2-4` package from your distribution, as these AppImages assume it to be part of the target system.

**Comment by satrioaw** [comment]
working well with

`$ sudo apt-get install libgconf-2-4`

but perhaps can be included in future update

**Comment by probonopd** [comment]
According to https://github.com/electron/electron/issues/1518, after Chrome 42 libgconf has become a requirement for running on Linux. So far we have assumed that libgconf is part of the base system. It seems like this assumption needs to be challenged.

**Comment by satrioaw** [comment]
so may in some of distro's doesn't include this

**Comment by probonopd** [comment]
Changed https://github.com/probonopd/AppImages/blob/master/excludedeblist accordingly
