### ISSUE TITLE
Your own example doesn't work

### ISSUE THREAD

**Issue by usercz** [probonopd/AppImageKit#242]
```
$ export APP=leafpad && ./apt-appdir/apt-appdir $APP && ./AppImageAssistant.AppDir/package $APP.AppDir $APP.AppImage && ./$APP.AppImage
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Suggested packages:
  evince-gtk
The following NEW packages will be installed:
  leafpad
0 upgraded, 1 newly installed, 0 to remove and 118 not upgraded.
Need to get 90.9 kB of archives.
After this operation, 465 kB of additional disk space will be used.
Get:1 http://ftp.se.debian.org/debian testing/main amd64 leafpad amd64 0.8.18.1-5 [90.9 kB]
Fetched 90.9 kB in 5s (16.4 kB/s)   
Download complete and in download only mode
W: --force-yes is deprecated, use one of the options starting with --allow instead.
Error opening directory './usr/share/glib-2.0/schemas/': No such file or directory
No ./usr/share/glib-2.0/schemas/
/tmp/AppImageKit

./leafpad.AppDir created. Now run:
./AppImageAssistant --package ./leafpad.AppDir ./leafpad

Icon could not be found based on information in desktop file, aborting
```

**Comment by probonopd** [comment]
Thanks for pointing this out. 
Indeed this is no longer the recommended way to do this; I will update the wiki accordingly.
https://github.com/probonopd/AppImages/blob/master/recipes/leafpad/Recipe has the new method.

**Comment by usercz** [comment]
That doesn't work either.

```

2016-09-28 12:36:23 (972 KB/s) - "appimagetool" salvato [369817/369817]

WARNING: appstreamcli is missing, please install it if you want to use AppStream metadata
WARNING: appstream-util is missing, please install it if you want to use AppStream metadata
Desktop file: /home/salvo/aaaaa/qweborf/qweborf.AppDir/qweborf.desktop
Name: qweborf
Icon: network-wired
Exec: qweborf.wrapper
Comment: Shares files using the HTTP protocol
Type: Application
Categories: Network;
File used for determining architecture: /home/salvo/aaaaa/qweborf/qweborf.AppDir/lib/x86_64-linux-gnu/libexpat.so.1
Arch: 86_64
App name for filename: qweborf
dest_path: qweborf-x86_64.AppImage
DESTINATION not specified, so assuming qweborf-0.13.glibc2.15-x86_64.AppImage
/home/salvo/aaaaa/qweborf/qweborf.AppDir should be packaged as qweborf-0.13.glibc2.15-x86_64.AppImage
/home/salvo/aaaaa/qweborf/qweborf.AppDir/network-wired.png not present but defined in desktop file
mv: impossibile eseguire stat di '*.AppImage*': File o directory non esistente
```

I tried to run the linked script, just replacing the package name.

**Comment by probonopd** [comment]
Strange, VERY strange. network-wired? Something seems to be going really wrong there. Which distribution are you running this on?

**Comment by usercz** [comment]
I'm running this on debian sid, but should it matter?

**Comment by usercz** [comment]
Perhaps you have a problem in looking the icon up? `network-wired` is in the devices directory.

**Comment by probonopd** [comment]
Could. I recommend oldstable if you have a choice, and am testing on trusty mainly (because it is available on Travis CI). I notice you are not using Leafpad. I never tried with qweborf and never claimed it would work this way. See the probonopd/AppImages project for examples on how to package more complex software. Qweborf uses Pyhton which means that some paths probably need to be adjusted. The best way to get an AppImage is to ask the Qweborf authors to provide one.

**Comment by usercz** [comment]
Ah, but that would be me :D This is my "work" account, as I'm trying to use AppImageKit for something work related.

I assumed leafpad was just a random example and it would work with other packages as well.

**Comment by probonopd** [comment]
Can you make your app relocatable so that it can be moved around in the filesystem and still works?

**Comment by usercz** [comment]
It is relocatable already. I run it from my home when I test it, but it gets installed in /usr

**Comment by probonopd** [comment]
Where can I download the version that runs from home?

**Comment by usercz** [comment]
It's the same version, but needs to be invoked in a particular way because it's not in a default python path.

However, with the deb package it shouldn't happen since it goes in the default python search path.

**Comment by usercz** [comment]
I tried with a more simple c++ app (kcalc) but the script seems to work only for leafpad.

**Comment by probonopd** [comment]
kcalc is not a "simple c++ app". See https://github.com/probonopd/AppImages/ for examples on how to package complex (e.g., Qt, KDE) applications.

**Comment by probonopd** [comment]
> It's the same version, but needs to be invoked in a particular way because it's not in a default python path.
How exactly?

> However, with the deb package it shouldn't happen since it goes in the default python search path.
Yes, but not if it's converted to an AppImage....

**Comment by usercz** [comment]
You're telling me to see the build scripts of one of the projects that use it i guess, since the README only contains overly long things about why appimage is so great.

Normally, you run it with `python -m qweborf`, remember to compile the .ui file before, with `pyuic5 qweborf/main.ui > qweborf/main.py`
