### ISSUE TITLE
'UpperCase' name scheme purpose

### ISSUE THREAD

**Issue by Larpon** [probonopd/AppImageKit#248]
I've been wondering why the name scheme is mixed case for both the binaries related to the project and the proposed file endings? It seems very counter-intuitive in regards to the the linux world :)

**Comment by probonopd** [comment]
For the naming of AppImages, I am using `UpperCase` for GUI applications and `lowercase` for CLI tools.

**Comment by Larpon** [comment]
On linux - developers tend to use `lowercase` only on binaries - no matter if the application has a GUI or not. The beautification of the application names usually comes in the *.desktop file - not on the executable itself - and the use of *.desktop files automatically implies that the application has a GUI.

Examples:

Name in *.desktop | binary name
------------ | -------------
Okular | okular
Krita | krita
GIMP | gimp-2.8
Blender | blender
QjackCtl | qjackctl

If I do `ls /usr/bin/` on my distro I see only lowercase entries.

Same thing goes for the file ending or suffix:
Krita writes `.kra` files - GIMP writes `.xcf` files. `*.desktop` files are lowercase and not `.Desktop`

That's why I've been wondering :)

**Comment by probonopd** [comment]
Yes, I plan to move toward the spelling in the .desktop file for the AppImage.
