### ISSUE TITLE
apt-get install won't download already installed packages

### ISSUE THREAD

**Issue by rwese** [probonopd/AppImageKit#253]
```
APP=git
# sudo apt-get --no-upgrade -y --force-yes install "${APP}" --download-only
Reading package lists... Done
Building dependency tree
Reading state information... Done
Skipping git, it is already installed and upgrade is not set.
```

Alternative use apt-get download + apt-rdepends([StackExchange Discussion](http://stackoverflow.com/questions/13756800/how-to-download-all-dependencies-and-packages-to-directory)):
```
# apt-get download $(apt-rdepends git|grep -v "^ "|grep -v "libc-dev")
Reading package lists... Done
Building dependency tree
Reading state information... Done
Get:1 http://ftp.de.debian.org/debian/ jessie/main libacl1 i386 2.2.52-2 [29.1 kB]
... (snipp)
# ls -l
total 23704
-rw-r--r-- 1 root root 3019262 May  3 01:02 dpkg_1.17.27_i386.deb
-rw-r--r-- 1 root root  159668 Dec 27  2014 gcc-4.9-base_4.9.2-10_i386.deb
... (snipp)
``` 

I hope this helps, I would also like to provide a patch if this is deemed useful.

**Comment by probonopd** [comment]
Where exactly do you get this error?

**Comment by rwese** [comment]
debian 8.6

Even if I remove the package first, it then wouldn't download the deps which are installed, if I remove those I still will miss deps which are deps for other packages.

**Comment by probonopd** [comment]
Yes, but which script or command or app are you running that results in this?

**Comment by rwese** [comment]
ah, sorry, I was trying out appimage with this example:
`export APP=git && ./apt-appdir/apt-appdir $APP && ./AppImageAssistant.AppDir/package $APP.AppDir $APP.AppImage && ./$APP.AppImage`

apt-appdir didn't download the debs, so I tried to figure out why.

**Comment by probonopd** [comment]
Please use the examples from https://github.com/probonopd/AppImages/tree/master/recipes instead.
