### ISSUE TITLE
"  /usr/share/mime/ "

### ISSUE THREAD

**Issue by tele1** [probonopd/AppImageKit#254]
I download portable app 64bit  from
http://appimage.org/

and 

```
$ ./Subsurface-4.5.1.1445-x86_64.AppImage
/tmp/.mount_MfOG2M
/tmp/.mount_MfOG2M/usr/bin/subsurface.wrapper
/tmp/.mount_MfOG2M/subsurface.desktop
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
appimagekit-subsurface
find '/tmp/.mount MFO G2M / usr / share / mime /': No such file or directory
A breach of memory (memory dump)
```

I use Manjaro linux

This is error from download ?
Can you put checksum md5 for check downloaded file ?

Edit
I tried download new file and test and

```
./Subsurface-4.5.1.1445-x86_64.AppImage
/tmp/.mount_cc7BCF
/tmp/.mount CC7 BCF / usr / bin / subsurface.wrapper
/tmp/.mount_cc7BCF/subsurface.desktop
A breach of memory (memory dump)
```

I can't  find file /tmp/.mount_cc7BCF
Where is ?

**Comment by probonopd** [comment]
`/tmp/.mount_cc7BCF` is a temporary mount point which only exists while the application is running.

I checked the file and it is running on Ubuntu 16.04. So possibly the desktopintegration script contained in the AppImage has an issue on your system. Try running `DEBUG=1 ./Subsurface-4.5.1.1445-x86_64.AppImage` and check the output for scripting errors.

**Comment by probonopd** [comment]
Do you really see `'/tmp/.mount MFO G2M / usr / share / mime /'`and not `'/tmp/.mount MFOG2M/usr/share/mime/'`?

**Comment by probonopd** [comment]
@tele1 does this problem persist?

**Comment by tele1** [comment]
If you can please wait a few days to answer
- I'm a little busy
- last time I broke system ( I installed something and I don't know what )
I have new, but next time I will test on virtualbox.

**Comment by probonopd** [comment]
Thanks, I suspect the above was due to the broken system.

**Comment by probonopd** [comment]
Please reopen if you still have this issue.
