### ISSUE TITLE
[appimaged] gets loaded by systemd but not executed

### ISSUE THREAD

**Issue by probonopd** [probonopd/AppImageKit#259]
`$ systemctl --user start appimaged` launches it just fine, but it doesn't start automatically upon boot.

Using this service file:

```
$ cat /usr/lib/systemd/user/appimaged.service
[Unit]
Description=AppImage daemon
After=basic.target

[Service]
ExecStart=/usr/bin/appimaged
Restart=always

[Install]
WantedBy=graphical.target
```

The `appimaged` service gets loaded but not executed at boot time:
```
$ systemctl --user status appimaged
● appimaged.service - AppImage daemon
   Loaded: loaded (/var/run/Extensions/appimaged.ExtensionImage/usr/lib/systemd/
   Active: inactive (dead)
```

More information:

```
$ systemctl --user list-dependencies appimaged
appimaged.service
● ├─-.slice
● └─basic.target
●   ├─paths.target
●   ├─sockets.target
●   └─timers.target
```

Similar issues:
https://bbs.archlinux.org/viewtopic.php?id=170344

**Comment by probonopd** [comment]
For debugging, I will boot with 
```
systemd.log_level=debug systemd.log_target=kmsg log_buf_len=1M
```
and then:
```
dmesg > dmesg.txt
systemctl list-jobs
```

**Comment by probonopd** [comment]
https://lists.freedesktop.org/archives/systemd-devel/2015-July/033587.html

**Comment by probonopd** [comment]
In the end I gave up on getting systemd to launch it automatically and used a really lame hack, it's working:
https://github.com/probonopd/SystemImageKit/commit/7b74c964e1daed6c0ad5d160e50c64c86a62d2e5

**Comment by lucasfs7** [comment]
@probonopd I have a similar problem, in my case it is loaded but not active... and when I start it and download any appimage app it doesnt create the .desktop do I cant find the app on application launcher

I'm running Elementary OS Loki

**Comment by probonopd** [comment]
@lucasfs7 did you install it using the deb? What does
```
systemctl --user enable appimaged
systemctl --user start appimaged
systemctl --user status appimaged
```
show?

**Comment by lucasfs7** [comment]
@probonopd I installed the deb and when I run all commands it shows
```
ppimaged.service - AppImage daemon
   Loaded: loaded (/usr/lib/systemd/user/appimaged.service; enabled; vendor preset: enabled)
      Active: active (running) since Ter 2016-11-29 17:39:39 BRST; 1min 7s ago
       Main PID: 10345 (appimaged)
          CGroup: /user.slice/user-1000.slice/user@1000.service/appimaged.service
                     └─10345 /usr/bin/appimaged

                     Nov 29 17:39:39 lucasfs7-Lenovo-G400s systemd[1344]: Started AppImage daemon.
                     Nov 29 17:39:40 lucasfs7-Lenovo-G400s appimaged[10345]: -> REGISTER /home/lucasfs7/bin/Etcher-linux-x64.AppImage
                     Nov 29 17:39:40 lucasfs7-Lenovo-G400s appimaged[10345]: ISO9660 based type 1 AppImage
                     Nov 29 17:39:40 lucasfs7-Lenovo-G400s appimaged[10345]: -> REGISTER /home/lucasfs7/bin/krita-3.0.1.1-x86_64.appimage
                     Nov 29 17:39:40 lucasfs7-Lenovo-G400s appimaged[10345]: ISO9660 based type 1 AppImage
```

but still, my apps doesnt appear in the applications launcher

**Comment by probonopd** [comment]
That looks good. Please log out of your desktop and log in again, perhaps it starts working then.

**Comment by lucasfs7** [comment]
but when I restart the system or logout and login again the service is inactive, and when add new apps to `~/bin` it doesn't show on applications launcher

**Comment by lucasfs7** [comment]
when I add a new app the log says
```
Nov 29 18:25:10 lucasfs7-Lenovo-G400s appimaged[16159]: -> REGISTER /home/lucasfs7/Downloads/hyper-0.8.3-x86_64.AppImage
Nov 29 18:25:10 lucasfs7-Lenovo-G400s appimaged[16159]: ISO9660 based type 1 AppImage
```

but it still doesn't appear in the application launcher

**Comment by probonopd** [comment]
Are you running this on a Live system or an installed system?

**Comment by lucasfs7** [comment]
installed system

**Comment by probonopd** [comment]
When you start appimaged manually using the commands above, does it create a desktop entry in `$HOME/.local/share/applications`, and can you launch the app using it?

**Comment by lucasfs7** [comment]
nope, it doesn't

**Comment by probonopd** [comment]
OK, for debugging this please run 
```
mkdir -p $HOME/bin
systemctl --user stop appimaged
appimaged -v
```

Then copy an AppImage to `$HOME/bin`. Do you see any error messages?

Then run `find $HOME/.local/share/applications`. Do you see any files there?

**Comment by lucasfs7** [comment]
ok, did, and the output is:
```
/home/lucasfs7/Downloads/hyper-0.8.3-x86_64.AppImage MOVED_FROM

-> UNREGISTER /home/lucasfs7/Downloads/hyper-0.8.3-x86_64.AppImage
get_thumbnail_path: /home/lucasfs7/.cache/thumbnails/normal/e62de1758506567965070bd75efc7c7e.png
get_thumbnail_path: /home/lucasfs7/.cache/thumbnails/large/e62de1758506567965070bd75efc7c7e.png
/home/lucasfs7/bin/hyper-0.8.3-x86_64.AppImage MOVED_TO
AppImage type 1

-> REGISTER /home/lucasfs7/bin/hyper-0.8.3-x86_64.AppImage
get_thumbnail_path: /home/lucasfs7/.cache/thumbnails/normal/921ab66d8a133b64c98106a402063e37.png
ISO9660 based type 1 AppImage
md5 of URI RFC 2396: 921ab66d8a133b64c98106a402063e37
```
and the `$HOME/.local/share/applications` shows only chrome files

**Comment by probonopd** [comment]
Do you also get the same version?

```
me@host:~$ appimaged --version
Version: continuous-1-g19e8f0d
```

Seems like you are encountering a bug that is unrelated to issue #259

**Comment by lucasfs7** [comment]
yep, same version

**Comment by probonopd** [comment]
Would be interesting to see if it works with a type 2 AppImage, e.g., https://bintray.com/probono/AppImages/download_file?file_path=Leafpad-0.8.18.1.glibc2.4-x86_64.AppImage

**Comment by lucasfs7** [comment]
this app worked... the logs:
```
                     Nov 29 19:27:06 lucasfs7-Lenovo-G400s appimaged[3821]: Could not set /home/lucasfs7/Downloads/Leafpad-0.8.18.1.glibc2.4-x86_64.AppImage.crdownload executable: No such file or directory
                     Nov 29 19:27:06 lucasfs7-Lenovo-G400s appimaged[3821]: -> REGISTER /home/lucasfs7/Downloads/Leafpad-0.8.18.1.glibc2.4-x86_64.AppImage
                     Nov 29 19:27:06 lucasfs7-Lenovo-G400s appimaged[3821]: squashfs based type 2 AppImage
                     Nov 29 19:27:06 lucasfs7-Lenovo-G400s appimaged[3821]: Got root desktop: leafpad.desktop
                     Nov 29 19:27:06 lucasfs7-Lenovo-G400s appimaged[3821]: Installing desktop file
                     Nov 29 19:27:06 lucasfs7-Lenovo-G400s appimaged[3821]: -> UNREGISTER /home/lucasfs7/Downloads/Leafpad-0.8.18.1.glibc2.4-x86_64.AppImage.crdownload
                     Nov 29 19:27:06 lucasfs7-Lenovo-G400s appimaged[3821]: -> REGISTER /home/lucasfs7/Downloads/Leafpad-0.8.18.1.glibc2.4-x86_64.AppImage
                     Nov 29 19:27:06 lucasfs7-Lenovo-G400s appimaged[3821]: squashfs based type 2 AppImage
                     Nov 29 19:27:06 lucasfs7-Lenovo-G400s appimaged[3821]: Got root desktop: leafpad.desktop
                     Nov 29 19:27:06 lucasfs7-Lenovo-G400s appimaged[3821]: Installing desktop file
```

**Comment by lucasfs7** [comment]
the apps I was trying are hyper terminal, krita and etcher

**Comment by probonopd** [comment]
To further nail down the problem, uninstall the appimaged deb using apt-get and try the [appimaged-x86_64.AppImage](https://github.com/probonopd/AppImageKit/releases/download/continuous/appimaged-x86_64.AppImage) instead.

**Comment by lucasfs7** [comment]
nope, didnt work... how do I check if it is running?

**Comment by lucasfs7** [comment]
running `./.local/bin/appimaged -v` and trying the same apps again didn't worked too

**Comment by probonopd** [comment]
That is strange. Let's open anew issue for it: https://github.com/probonopd/AppImageKit/issues/305
Let's continue the discussion there.
