### ISSUE TITLE
Missing Icons

### ISSUE THREAD

**Issue by Aeirex** [probonopd/AppImageKit#263]
Icons do not show in WingPanel or Plank, I do not know if there's any icon support in AppImages. But it is pretty fugly to me, since I preferred using PPAs over AppImages due to this very flaw alone.

It may be good to integrate the icon inside the AppImage file, then have desktops environments use the icon inside Plank, Wing Panel, etc.

Could also have where it places icons inside here possibly? And other known places which require them. Each desktop environment would probably need to be considered, so compatibly is good across the board.
`/usr/share/icons/`

**Comment by PHPJosh** [comment]
Must be an issue with your Install. AppImage must certainly has and supports Icons. are you running  elementary os by chance? as @probonopd has had an issue with it also. I will be trying to reproduce his bugs in a VM when i get a chance, Guess i will try to reproduce yours too once i get around to installing the VM

**Comment by Aeirex** [comment]
elementaryOS yes. Snappy doesn't work that good in eOS, so I am forced to use appImage.

**Comment by probonopd** [comment]
The author of the AppImage can decide whether to put in desktop integration or not. Krita has decided that they don't since their users don't like it. but you can set up a .desktop file yourself. https://wiki.archlinux.org/index.php/Desktop_entries

In the (near) future, there will be [appimaged](https://www.youtube.com/watch?v=FqVAtHdK1N0).

**Comment by Aeirex** [comment]
@probonopd AppImage I don't really like from my experiences, I prefer Ubuntu's Snap. It just is less reliable than AppImage.

There's too much inconsistency with developers, I have to spend time learning and fixing the apps that are half finished. Stuff like icons missing and stuff most normal human beings will not want to mess with this kind of stuff.

**Comment by probonopd** [comment]
>  Krita is not saving the theme I set.

Please report that to the Krita developers.

> missing icons

Which icons are you talking about, can you post a screenshot?

**Comment by Aeirex** [comment]
The icons can be fixed by creating a desktop shortcut. I will contact KDE about the settings not saving, I figured it was a problem with the AppImageKit builder itself.

**Comment by probonopd** [comment]
Please reopen if you think this is an issue in AppImageKit.
