### ISSUE TITLE
appimagetool hangs

### ISSUE THREAD

**Issue by brotenet** [probonopd/AppImageKit#264]
When I run :
`appimagetool <Target AppDir>`
the tool hangs on the following message:
`The location of this application is: <path to the appimagetool directory>`
![selection_003](https://cloud.githubusercontent.com/assets/4510965/19601123/931e26ca-97b0-11e6-8261-8fe20f79ca67.png)

Both the _appimagetool_ and the target appimage directory are in the same parent directory
Now I'm not really sure if I'm using _appimagetool_ in a wrong way, or, if this is actually has a bug.. 

@probonopd  this relates to the 2 issues I have on my repo from our talk last week:
https://github.com/brotenet/AppImageTemplates/issues/4
https://github.com/brotenet/AppImageTemplates/issues/3

**Comment by probonopd** [comment]
Please run appimagetool from the outside of the directory in which the app you want to bundle is located. Also, please run with `-verbose=3`.

**Comment by probonopd** [comment]
Also, can you please give step-by-step instructions how to reproduce this, e.g., which repository to check out and what to do exactly.

**Comment by probonopd** [comment]
I recently had a similar situation where appiamgetool was hanging, turned out it wanted to write to a location where it couldn't. Can you please retry with
https://transfer.sh/q6J0e/appimagetool

**Comment by brotenet** [comment]
When I execute:
`./appimagetool -v KeystoreExplorer`
-or-
`./appimagetool KeystoreExplorer`
_appimagetool_ exits with the following message:
`kse.png{.png,.svg,.svgz,.xpm} not present but defined in desktop file`
but the .png icon file is already in the root of the AppDir
![selection_006](https://cloud.githubusercontent.com/assets/4510965/19627826/c3a77518-9958-11e6-9749-93447565c282.png)

**Comment by probonopd** [comment]
"Icon=kse.png" is wrong. It should be "Icon=kse".

**Comment by brotenet** [comment]
I know this is a minor thing but, when I use 'Icon=kse' in the .desktop file, I builds OK and also creates a menu shortcut correctly but if I view the AppImage file in a file manager the icon is not rendered on the AppImage file itself.
![selection_007](https://cloud.githubusercontent.com/assets/4510965/19628029/7ca8db7a-995d-11e6-97a9-cb2dfd76e903.png)

**Comment by probonopd** [comment]
This has nothing to do with `Icon=kse` but with the fact that I removed support for this feature in newer versions of the AppImage runtime. This will be handled by `appimaged` instead.

**Comment by brotenet** [comment]
so it is OK for the AppImage icon not to render in the file manager, yes?

**Comment by probonopd** [comment]
Yes!

**Comment by brotenet** [comment]
ok then :) 
I'll close the issue here and I'll be using the _appimagetool_ from further on 
:+1:  :+1:  :+1:

**Comment by eu21** [comment]
I tested thumbnailer from here, but it only extracts icons http://www.omgubuntu.co.uk/2010/08/appimage-thumbnailer-gets-ppa
I need to inject icon, but thumbnailer can't do this.
Am I wrong?

Is there any way to inject icon into AppImage file now a days?

**Comment by eu21** [comment]
Here is my dimmer.AppImage for Linux https://drive.google.com/open?id=0Bw-psMRi0Mgfclo0S1NnOXE1ZXM 
It can be helpful for your eyes, but it makes it hard to use with no icon in task panel.
Please make that hackish code back. I need this icon to be shown.

**Comment by probonopd** [comment]
@eu21 how did you create this AppImage? I get

```
Downloads/dimmer_no_icon_small.AppImage: error while loading shared libraries: libQt5Widgets.so.5: cannot open shared object file: No such file or directory
```

Regading icons, a thumbnailer cannot change the icon shown in the taskbar or the icons stored inside an AppImage, and is not needed for that. A thumbnailer can only make the app icon shown as the icon for the AppImage in the file manager itself.

**Comment by eu21** [comment]
About libQt5Widgets.so.5 error - I thought this lib is not important. I added it download from here https://drive.google.com/open?id=0Bw-psMRi0MgfZnEzaEVxOGNJc3M

> A thumbnailer can only make the app icon shown as the icon for the AppImage in the file manager itself.

No! Thumbnailer can't add icons - it can only extract them. I tried it. I am forced to distribute no_icon-AppImage

[https://github.com/eu21/dimmer_with_dialog](https://github.com/eu21/dimmer_with_dialog)

**Comment by probonopd** [comment]
> About libQt5Widgets.so.5 error - I thought this lib is not important. I added it, new download is here https://drive.google.com/open?id=0Bw-psMRi0MgfZnEzaEVxOGNJc3M

Unfortunately I am still getting

```
$ /home/me/Downloads/dimmer_dialog_x86_64_no_icon.AppImage 
/home/me/Downloads/dimmer_dialog_x86_64_no_icon.AppImage: error while loading shared libraries: libQt5Widgets.so.5: cannot open shared object file: No such file or directory
```

> No! Thumbnailer can't add icons - it can only extract them. I tried it. I am forced to distribute no_icon-AppImage

Can you please explain, I don't understand what you mean by "I am forced to distribute no_icon-AppImage". What does that mean?

**Comment by eu21** [comment]
Thanks for letting me know. How can it work on my computer? Is it possible that AppImage is picking libs from my OS? I thought it is completely separated from OS. I will try to rename QT libs dir and run it on my computer.

> Can you please explain, I don't understand what you mean by "I am forced to distribute no_icon-AppImage". What does that mean?

Sorry, I don't meant to offend you. I meant - please make icons work in your program again. And thank you very much for your AppImageKit. It's very helpful.

**Comment by probonopd** [comment]
> Thanks for letting me know. How can it work on my computer? Is it possible that AppImage is picking libs from my OS? I thought it is completely separated from OS. I will try to rename QT libs dir and run it on my computer.

If everything goes right, then the AppImage will give _preference_ to the libraries inside the AppImage and only load those from outside the AppImage (i.e., your base system) that are not part of the AppImage. This is intentional - otherwise you would need to bundle _all_ libraries down to system ones like glibc which is not desireable. But it means that you need to take care to bundle all libraries except [those you want to be used from the system](https://github.com/probonopd/AppImages/blob/master/excludelist).

See functions.sh and the examples on https://github.com/probonopd/AppImages, should hopefully be helpful. Also, check the work-in-progress [linuxdeployqt](https://github.com/probonopd/linuxdeployqt) tool which will eventually automate a lot of the work for you.

**Comment by supertriodo** [comment]
Hi.

First thx for the great work with this tool, it's amazing.

I'm having the same problem, I specify the icon name in the desktop file but the final AppImage file doesn't have an icon.

So if the user locate the AppImage file in the desktop it will still have no image.

You explained saying: "This will be handled by the optional appimaged daemon and/or a thumbnailer instead." but I don't really understand it. So my question is:

Is there any way to make this AppImage show an icon for a normal user who download it?

Thx

**Comment by probonopd** [comment]
Hi @supertriodo 
If you mean that the AppImage should show the application icon as the icon for the AppImage file itself then no, that is currently not possible. Sorry. Someone would need to write the code to do this. (My original earlier code was just a quick hack, so I removed it.)

**Comment by supertriodo** [comment]
Yes that exactly what I meant, thx. Then if you plan to create an AppImage for your application there's absolutely zero benefit in updating the .desktop file and choosing an icon, right?

**Comment by probonopd** [comment]
You should use a proper desktop file and icon, so that the optional `appimaged` daemon can properly integrate your app into the menu.
