### ISSUE TITLE
Make AppImageAssistant return exit code of sub-commands?

### ISSUE THREAD

**Issue by lurch** [probonopd/AppImageKit#266]
In https://github.com/probonopd/AppImageKit/blob/master/AppImageAssistant.AppDir/AppImageAssistant there's two occurrences of:
```python
    subprocess.call(command)
    exit(0)
```

Would it be better to change these to:
```python
    exit(subprocess.call(command))
```
so that if `command` fails, the error-code will get bubbled up the stack?
This would mean that in any bash scripts with `set -e` turned on, using AppImageAssistant would instantly bail out (as expected) if `command` fails, rather than just continuing regardless even though AppImageAssistant didn't complete successfully.

**Comment by probonopd** [comment]
We can do that but I doubt it's worthwhile since AppImageAssistant will be replaced by `appimagetool` soon. Will update the documentation accordingly.

Also, `appimagetool ` will be moved from https://github.com/probonopd/appimagetool to this repository once we think it's ready to roll.

**Comment by lurch** [comment]
Fair enough.

**Comment by lurch** [comment]
Any idea what sort of timescale "soon" is likely to be? Couple of weeks, several months, etc.?

**Comment by probonopd** [comment]
Once enough people deem it "ready". You can check it out today [here](https://github.com/probonopd/appimagetool).
