### ISSUE TITLE
[appimaged] Segfaults when compiled on Ubuntu 16.04

### ISSUE THREAD

**Issue by probonopd** [probonopd/AppImageKit#269]
The following was working:

```
git reset --hard
git checkout b6bf7e1e25a9b32c2cf2d9370368da4b32f952f8
./build.sh
./build/appimaged
```

Does not segfault. Subsequent commits do. But only when built on Ubuntu 16.04, not when built on CentOS 6. Probably something about libarchive ISO reading.

Strangely, the segfault does __not__ happen when invoked with `-v`.

**Comment by probonopd** [comment]
`libarchive` overall seems to be a burden for "just extracting ISOs" -- consider to use cmginfo instead.
https://github.com/probonopd/AppImageKit/issues/37

**Comment by orivej** [comment]
Can you provide a faulty `appimaged` (preferably unstripped) and an ISO appimage so that I could see why I can't reproduce this?

**Comment by probonopd** [comment]
Still seeing this on Ubuntu 16.04 in ed07cfb. Attaching unstripped `appiamged`.
[appimaged.zip](https://github.com/probonopd/AppImageKit/files/628997/appimaged.zip)

**Comment by orivej** [comment]
The issue with this appimaged is that `desktop_icon_value_original` is not initialized in `appimage_type1_register_in_system`. The test `if(desktop_icon_value_original)` may inadvertent succeed, and `g_str_has_prefix(filename, desktop_icon_value_original)` will be called with a garbage value.

**Comment by probonopd** [comment]
Thanks @orivej - how did you find this so quickly? Are there tools for identifying this sort of issue?

**Comment by orivej** [comment]
`valgring ./appimaged` reports the following. (In this case `desktop_icon_value_original` value turned out to be 0x3.)
```
==1206== Process terminating with default action of signal 11 (SIGSEGV)
==1206==  Access not within mapped region at address 0x3
==1206==    at 0x4C2C4E2: strlen (in /usr/lib64/valgrind/vgpreload_memcheck-amd64-linux.so)
==1206==    by 0x5150BBD: g_str_has_prefix (in /usr/lib64/libglib-2.0.so.0.4800.1)
==1206==    by 0x405CF0: appimage_type1_register_in_system (in /tmp/appimaged)
==1206==    by 0x406462: appimage_register_in_system (in /tmp/appimaged)
==1206==    by 0x40684E: thread_appimage_register_in_system (in /tmp/appimaged)
==1206==    by 0x5602709: start_thread (in /lib64/libpthread-2.22.so)
==1206==    by 0x5B15C6C: clone (in /lib64/libc-2.22.so)
```

However, I debugged appimaged solely with gdb:
```
$ gdb ./appimaged
>>> run
Thread 246 "appimaged" received signal SIGSEGV, Segmentation fault.
>>> bt
#0  strlen () at ../sysdeps/x86_64/strlen.S:106
#1  0x00007ffff787fbbe in g_str_has_prefix (str=0x7fffec03d500 "usr/share/applications/subsurface.desktop", prefix=0x3 <error: Cannot access memory at address 0x3>) at /usr/src/debug/dev-libs/glib-2.48.1-r1/glib-2.48.1/glib/gstrfuncs.c:2867
#2  0x0000000000405cf1 in appimage_type1_register_in_system ()
#3  0x0000000000406463 in appimage_register_in_system ()
#4  0x000000000040684f in thread_appimage_register_in_system ()
#5  0x00007ffff73fe70a in start_thread (arg=0x7ffff2f3a700) at pthread_create.c:334
#6  0x00007ffff6f2ec6d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
```
and, since appimaged turned out to be stripped after all, I disassembled `appimage_type1_register_in_system` and counted occurrences of `g_str_has_prefix` in the source code and in the disassembly to determine which call caused segfault, and then confirmed that `if(success)` branch was not taken:
```
>>> frame 2
#2  0x0000000000405cf1 in appimage_type1_register_in_system ()
>>> disas
...
>>> b *0x0000000000405b42
Breakpoint 1 at 0x405b42
>>> run
```
