### ISSUE TITLE
[App Request] Jekyll

### ISSUE THREAD

**Issue by kskarthik** [probonopd/AppImageKit#275]
Please provide AppImage for Jekyll. Its a hell installing dependencies for it. This helps making Jekyll newbie friendly

**Comment by probonopd** [comment]
Please ask the upstream authors of Jekyll to provide an AppImage. I am happy to help. (My recipes are just examples; the objective of AppImage is to enable upstream authors to provide their software directly to end users.)

**Comment by probonopd** [comment]
In the meantime, have a look at https://github.com/probonopd/AppImages/blob/master/recipes/meta/jekyll.yml and https://bintray.com/probono/AppImages/jekyll/_latestVersion#files

**Comment by kskarthik** [comment]
What I found is we cant add plugins to AppImage. Is there a hack around this to sync plugins from a folder outside the AppImage to _plugins dir inside AppImage ?

**Comment by probonopd** [comment]
Would a symlink from inside the AppImage to the outside (somewhere in`$HOME`) work?

**Comment by probonopd** [comment]
Feel free to reopen if further changes are needed.

**Comment by kskarthik** [comment]
I observed an issue. I couldn't change the source directory & output directory with command `jekyll -s $PATH` 

By default it is configured to use `./tmp`
