### ISSUE TITLE
Bundle Subsurface

### ISSUE THREAD

**Issue by probonopd** [probonopd/AppImageKit#28]
See the "DebConf 14_ QA with Linus Torvalds" video where Linus addresses some of the issues that AppImageKit tries to solve.

At 05:40 Linus highlights a core issue for Linux on the desktop, application packaging: "I'm talking about actual application writers that want to make a package of their application for Linux. And I've seen this firsthand with the other project I've been involved with, which is my divelog application. We make binaries for Windows and OS X. We basically don't make binaries for Linux. Why? Because binaries for Linux desktop applications is a major f*ing pain in the ass. Right. You don't make binaries for Linux. You make binaries for Fedora 19, Fedora 20, maybe there's even like RHEL 5 from ten years ago, you make binaries for debian stable, or actually you don't make binaries for debian stable because debian stable has libraries that are so old that anything that was built in the last century doesn't work. But you might make binaries for debian... whatever the codename is for unstable. And even that is a major pain because (...) debian has those rules that you are supposed to use shared libraries. Right. And if you don't use shared libraries, getting your package in, like, is just painful. But using shared libraries is not an option when the libraries are experimental and the libraries are used by two people and one of them is crazy, so every other day some ABI breaks. So you actually want to just compile one binary and have it work. Preferably forever. And preferably across all Linux distributions. And I actually think distributions have done a horribly, horribly bad job. One of the things that I do on the kernel - and I have to fight this every single release and I think it's sad - we have one rule in the kernel, one rule: we don't break userspace. (...) People break userspace, I get really, really angry. (...) And then all the distributions come in and they screw it all up. Because they  break binary compatibility left and right. They update glibc and everything breaks. (...) So that's my rant. And that's what I really fundamentally think needs to change for Linux to work on the desktop because you can't have applications writers to do fifteen billion different versions."

Hence, we should package the Subsurface app and make it run on the above-mentioned distributions (and others):
https://subsurface-divelog.org/de/download/

**Comment by probonopd** [comment]
Better yet: Nightlies built from git

**Comment by RazZziel** [comment]
Just made a quick package with my [pacman2appDir](https://github.com/RazZziel/PortableLinuxGames/blob/master/pacman2appDir) + [these tips](https://github.com/RazZziel/PortableLinuxGames/wiki/Qt-Apps), and after a very quick test with [runInChroot](https://github.com/RazZziel/PortableLinuxGames/blob/master/runInChroot) it seems to run on ubuntu-10.04.4-desktop-i386.iso, ubuntu-12.04-desktop-i386.iso and ubuntu-14.04-desktop-i386.iso. Won't be able to test it further though.

Will take a while to upload on my crappy internet, hope tomorrow is uploaded.

**Comment by RazZziel** [comment]
Uploaded: https://sourceforge.net/projects/pg4l/files/Subsurface%204.4.2-r1-archlinux-x86.run/download

**Comment by probonopd** [comment]
Thanks @RazZziel. Looks like a bit manual tuning will be needed since some paths are apparently not found. The following is on a `debian_7.0.0_wheezy_i386_20130705_binary.hybrid.iso` system:

```
me@host:~$ uname -a
Linux host 3.2.0-4-486 #1 Debian 3.2.46-1 i686 GNU/Linux
me@host:~$ '/home/me/Downloads/Subsurface 4.4.2-r1-archlinux-x86.run' 
fuse: failed to open /dev/fuse: Permission denied
open dir error: : No such file or directory
me@host:~$ gpasswd -a me fuse
gpasswd: Erlaubnis verweigert.
me@host:~$ sudo gpasswd -a me fuse
Benutzer me wird zur Gruppe fuse hinzugefügt.
me@host:~$ '/home/me/Downloads/Subsurface 4.4.2-r1-archlinux-x86.run' 
fuse: failed to open /dev/fuse: Permission denied
open dir error: : No such file or directory
me@host:~$ sudo su
root@host:/home/me# '/home/me/Downloads/Subsurface 4.4.2-r1-archlinux-x86.run' 
can't find Qt localization for locale "de" searching in "/usr/share/qt/translations"
can't find Subsurface localization for locale "de"
Fontconfig warning: "/etc/fonts/conf.d/65-droid-sans-fonts.conf", line 103: Having multiple values in <test> isn't supported and may not work as expected
Fontconfig warning: "/etc/fonts/conf.d/65-droid-sans-fonts.conf", line 138: Having multiple values in <test> isn't supported and may not work as expected
Map theme file does not exist: ""
QInotifyFileSystemWatcherEngine::addPaths: inotify_add_watch failed: No such file or directory
Map theme file does not exist: ""
Falling back to default theme: "earth/srtm/srtm.dgml"
Map theme file does not exist: ""
Couldn't find a valid DGML map.
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
QFSFileEngine::open: No file name specified
```

**Comment by probonopd** [comment]
I tried making one using

```
# ubuntu-14.04.1-desktop-amd64.iso

echo "deb http://ppa.launchpad.net/subsurface/subsurface/ubuntu trusty main" \
        | sudo tee /etc/apt/sources.list.d/subsurface.list
gpg --keyserver subkeys.pgp.net --recv-keys A8BC9756EE61D9C6
gpg -a --export A8BC9756EE61D9C6 | sudo apt-key add -

sudo apt-get update ; sudo apt-get -y install libfuse-dev libglib2.0-dev cmake git libc6-dev binutils fuse # debian, Ubuntu
yum install git cmake binutils fuse glibc-devel glib2-devel fuse-devel gcc zlib-devel libpng12 # Fedora, RHEL, CentOS
git clone https://github.com/probonopd/AppImageKit.git
cd AppImageKit
cmake .
make

export APP=subsurface
./apt-appdir/apt-appdir $APP 
rm subsurface.AppDir/gstreamer.desktop

ldd ./$APP.AppDir/usr/bin/$APP | grep "=> /" | awk '{print $3}' | xargs -I '{}' cp -v '{}' ./$APP.AppDir/usr/lib

./AppImageAssistant $APP.AppDir $APP.AppImage
./$APP.AppImage
```

**Comment by probonopd** [comment]
With the help of the friendly prople from #subsurface on freenode I am working on travis-ci continuous builds at https://github.com/probonopd/AppImages/blob/master/recipes/subsurface.sh

**Comment by probonopd** [comment]
> I'm talking about actual application writers that want to make a package of their application for Linux. And I've seen this firsthand with the other project I've been involved with, which is my divelog application.

Obviously Linus is talking about [Subsurface](https://subsurface-divelog.org). 

> We make binaries for Windows and OS X. 

[subsurface-4.5.exe](https://subsurface-divelog.org/downloads/subsurface-4.5.exe) for Windows is 83.5 MB large, [Subsurface-4.5.dmg](https://subsurface-divelog.org/downloads/Subsurface-4.5.dmg) for Mac weighs in at 38.3 MB.

Both bundle not only the application itself, but also the required Qt libraries that the application needs to run. Also included are dependency libraries like `libssh2.1.dylib`and `libzip.2.dylib`.

> We basically don't make binaries for Linux. Why? Because binaries for Linux desktop applications is a major f*ing pain in the ass. Right. You don't make binaries for Linux. You make binaries for Fedora 19, Fedora 20, maybe there's even like RHEL 5 from ten years ago, you make binaries for debian stable, or actually you don't make binaries for debian stable because debian stable has libraries that are so old that anything that was built in the last century doesn't work. But you might make binaries for debian... whatever the codename is for unstable. And even that is a major pain because (...) debian has those rules that you are supposed to use shared libraries. Right. 

So why not use the same approach as on Windows and OS X, namely, treat the base operating system as a platform on top of which we tun the application we care about. This means that we have to bundle the application with all their dependencies that are not part of the base operating system. Welcome [application bundles](https://blogs.gnome.org/tvb/2013/12/10/application-bundles-for-glade/).

> And if you don't use shared libraries, getting your package in, like, is just painful. 

"Getting your package in" means that the distribution accepts the package as part of the base operating system. For an application, that might not be desired at all. As long as we can package the application in a way that it seamlessly runs on top of the base operating system. 

> But using shared libraries is not an option when the libraries are experimental and the libraries are used by two people and one of them is crazy, so every other day some ABI breaks. 

One simple way to achieve this is to bundle private copies of the libraries in question with the application that uses them. Preferably in a way that does not interfere with anything else that is running on the base operating system. Note that this does not have to be true for all libraries; core libraries that are matured, have stable interfaces and can reasonably expected to be present in all distributions do not necessarily have to be bundled with the application.

> So you actually want to just compile one binary and have it work. Preferably forever. And preferably across all Linux distributions. 

That is actually possible, as long as you stay away from any distribution-specific packaging, and as long as you do not use a too recent build system. The same will probably be true for Windows and OS X - if you compile on OS X 10.11 then I would not expect the resulting build products to run on OS X 10.5.

> And I actually think distributions have done a horribly, horribly bad job. 

Distributions are all about building the base operating system. But I don't think distributions are a good way to get applications. Rather, I would prefer to get the latest versions of applications directly from the people who write them. And this is already a reality for software like Google Chrome, Eclipse, Arduino and other applications. Who uses the (mostly outdated and changed) versions that are part of the distributions? Probably most people don't.

> One of the things that I do on the kernel - and I have to fight this every single release and I think it's sad - we have one rule in the kernel, one rule: we don't break userspace. (...) People break userspace, I get really, really angry. (...) 

Excellent. Thank you for this policy! This is why I can still run the Mosaic browser from over a decade ago on modern Linux-based operating systems. (I tried and it works.)

> And then all the distributions come in and they screw it all up. Because they break binary compatibility left and right. 

Luckily, binaries built on older distributions tend to still work on newer distributions. At least that has been my experience over the last decade with building application bundles using AppImageKit, and before that, klik.

> They update glibc and everything breaks. (...) 

There is a [way around this](https://blogs.gnome.org/tvb/2013/12/14/application-bundles-revisited/), although not many people actually care to use the workaround (yet).

> So that's my rant. And that's what I really fundamentally think needs to change for Linux to work on the desktop because you can't have applications writers to do fifteen billion different versions.

AppImage to the rescue. The AppImage format is a standardized format for packaging applications in a way that allows them to run on target systems without further modification.

The AppImage format has been created with specific objectives in mind, which are explained in more detail in the [AppImageKit Documentation](http://portablelinuxapps.org/docs/1.0/AppImageKit.pdf):
1. Be Simple
2. Maintain binary compatibility 
3. Be distribution-agostic 
4. Remove the need for installation
5. Keep apps compressed all the time
6. Allow to put apps anywhere
7. Make applications read-only
8. Do not require recompilation (not always desired or possible)
9. Keep base operating system untouched
10. Do not require root

**Comment by probonopd** [comment]
openSUSE Tumbleweed (20151012) - openSUSE-Tumbleweed-GNOME-Live-x86_64-Current.iso

![opensuse](https://cloud.githubusercontent.com/assets/2480569/10559386/f4bdc906-74ef-11e5-87b7-98d9033d1252.png)

**Comment by probonopd** [comment]
An upstream-built AppImage is now available on [https://subsurface-divelog.org/download/](https://subsurface-divelog.org/download/). This is great because it ships the software as intended by the upstream project. Over the past few weeks, I have been working with the Subsurface team to build an AppImage and during course of this, we stumbled into many subtleties that I assume a third-party packager would have been struggling with for a long time, if ever discovered at all. For me this is a good example why binaries should be produced by upstream projects.

> A generic AppImage is available for download as [Subsurface-4.5.2-x86_64.AppImage](https://subsurface-divelog.org/downloads/Subsurface-4.5.2-x86_64.AppImage). You should be able to download this file, make it executable
> `chmod +x Subsurface-4.5.2-x86_64.AppImage`
> and then simply run this file. We are very interested in feedback regarding this way of distributing Linux binaries.

What is even more awesome is that the Subsurface project is producing [daily builds](http://subsurface-divelog.org/downloads/daily/) of the development branch as well.

**Comment by probonopd** [comment]
Moved to CentOS 6 as a build system because the AppImages can run on older systems this way, including debian oldstable (wheezy). Check out https://github.com/probonopd/AppImages/releases/tag/1

**Comment by probonopd** [comment]
https://subsurface-divelog.org/2015/11/announcing-subsurface-4-5-2/
