### ISSUE TITLE
Arch Linux and creating an AppImage from source

### ISSUE THREAD

**Issue by chrisnharvey** [probonopd/AppImageKit#29]
Hi there,

Are there any docs on creating AppImage's from pacman packages, or creating an AppImage from source?

**Comment by RazZziel** [comment]
I have some scripts to create AppImages from pacman/yaourt in the [PortableLinuxGames](https://github.com/RazZziel/PortableLinuxGames) project: [here](https://github.com/RazZziel/PortableLinuxGames/blob/master/pacman2appDir)'s the script and [here](https://github.com/RazZziel/PortableLinuxGames/wiki/Creating-appimages-from-archlinux-packages)'s a small tutorial.

**Comment by chrisnharvey** [comment]
Perfect, thats exactly what I was looking for.

Thanks.
