### ISSUE TITLE
GLib-GIO-Error

### ISSUE THREAD

**Issue by chrisnharvey** [probonopd/AppImageKit#30]
Hi,

I've been successful at packaging most basic apps using AppImageKit. However, I'm trying to package the "Cheese" app into an AppImage, but I'm getting the following error.

```GLib-GIO-Error **: Settings schema 'org.gnome.Cheese' is not installed```

Any ideas?

**Comment by probonopd** [comment]
Put a `cheese.schemas` into your AppDir `./usr/share/glib-2.0/schemas/`and then try running
```
glib-compile-schemas ./usr/share/glib-2.0/schemas/ || echo "No ./usr/share/glib-2.0/schemas/"
```
from within a custom AppRun script.

**Comment by chrisnharvey** [comment]
Got it, thanks. That is what I was trying, but I was adding the wrong path to the XDG_DATA_DIRS environment variable. All working fine now, thanks.

**Comment by probonopd** [comment]
Please document here what you have done, for others as a reference. Thanks.

**Comment by chrisnharvey** [comment]
Of course.

I compiled the glib schemas like you said, then added the location to the XDG_DATA_DIRS directory. Below is a copy of my AppRun script.

```bash
export APPDIR="$(dirname "$(readlink -f "$0")")"
export PATH="$APPDIR/usr/bin/:$PATH"
export LD_LIBRARY_PATH="$APPDIR/usr/lib:$PATH"
export XDG_DATA_DIRS="$APPDIR/usr/share/:/usr/share/:$XDG_DATA_DIRS"

$APPDIR/usr/bin/cheese

```

**Comment by probonopd** [comment]
Thank you.
