### ISSUE TITLE
gparted

### ISSUE THREAD

**Issue by milad0123** [probonopd/AppImageKit#300]
hi.
please make and add gparted.appimage to download.its very needed.thanks.

**Comment by probonopd** [comment]
Hi @milad0123. Thanks for your interest in AppImage. This project, AppImageKit, is a tool for upstream developers (e.g., the team that writes GParted) to produce AppImages.

Please open a feature request with the GParted team [here](http://gparted-forum.surf4.info/viewforum.php?id=5).

If there is interest from the GParted team, I am happy to assist them with anything they might need.
