### ISSUE TITLE
Merge AppRun with runtime

### ISSUE THREAD

**Issue by hyronx** [probonopd/AppImageKit#301]
To my mind AppRun isn't really needed. All environmental setup and .desktop parsing can already be done at the end of the runtime.

I have already tested it by copy-pasting AppRun into runtime and making some minor modifications and it works!
A PR is ready but I thought it's better to discuss this first.

**Comment by probonopd** [comment]
@hyronx the reason for the split is that what goes inside the AppImage is an [AppDir](https://www.skepticats.com/rox/appdirs.html), which should be possible to run also when unpacked (i.e., outside of an AppImage), which is useful e.g., during development, for very disk-IO heavy apps, and for users who cannot use FUSE.

If we would combine runtime and AppRun, then the unpacked AppImage would not be an AppDir anymore.

**Comment by hyronx** [comment]
Oh, I didn't know that. Maybe it should be considered to use a custom format because this one seems to be already quite old and hasn't got so much attention. (even Google hasn't much to say about it)
