### ISSUE TITLE
Add "Remove desktop integration" action to desktop menu entries

### ISSUE THREAD

**Issue by darealshinji** [probonopd/AppImageKit#302]
I know there's appimaged now, but I don't like the idea to require a program to be installed into your system to have your old desktop menu entries removed.
Can't there instead/additionally (maybe optionally) be a "Remove desktop integration" action added to the desktop menu entries? Adding _something_ like the following code to `desktopintegration` may do it:
``` bash
  HAS_ACTIONS="$(grep -e '^Actions=' "$DESTINATION_DIR_DESKTOP/$VENDORPREFIX-$DESKTOPFILE_NAME")"
  HAS_DESKTOPINTEGRATION="$(grep -e '^Actions=RemoveDesktopintegration;' "$DESTINATION_DIR_DESKTOP/$VENDORPREFIX-$DESKTOPFILE_NAME")"
  if [ -z "$HAS_DESKTOPINTEGRATION" ] ; then
    if [ -n "$HAS_ACTIONS" ] ; then
      sed -i -e 's|^Actions=|Actions=RemoveDesktopintegration;|' "$DESTINATION_DIR_DESKTOP/$VENDORPREFIX-$DESKTOPFILE_NAME"
    else
      printf "\n\nActions=RemoveDesktopintegration;\n" >> "$DESTINATION_DIR_DESKTOP/$VENDORPREFIX-$DESKTOPFILE_NAME"
    fi

    if [[ $EUID = 0 ]] ; then
      if type -p kdesudo >/dev/null ; then
        GKSU="kdesudo "
      else
        GKSU="gksu "
      fi
    fi

    cat <<EOL>> "$DESTINATION_DIR_DESKTOP/$VENDORPREFIX-$DESKTOPFILE_NAME"


[Desktop Action RemoveDesktopintegration]
Name=Remove desktop integration
Exec=${GKSU}removedesktopintegration \"${RESOURCE_NAME}\"
EOL
  fi
```

**Comment by probonopd** [comment]
`removedesktopintegration` being a script? Where would it live, inside the AppImage or outside?

**Comment by darealshinji** [comment]
This was just an example but I guess a script is better than a long one-liner. Preferably inside the AppImage.

**Comment by probonopd** [comment]
@darealshinji if you can do a fully working PR I am happy to merge it.

**Comment by darealshinji** [comment]
I give up. It doesn't seem to be impossible, but it's quite complicated and I can't get it to work properly, and it's probably not worth the effort anyway.

**Comment by darealshinji** [comment]
Distributors of AppImages could probably just provide shell scripts which will create desktop menu entries of their apps with such a "remove entry" option.
Here's a simple example: https://gist.github.com/darealshinji/09ab0bafebd75caeab637fb3f0d4a961
