### ISSUE TITLE
[appimaged] does not register type 1 AppImages on elementaryOS

### ISSUE THREAD

**Issue by probonopd** [probonopd/AppImageKit#305]
* elementaryOS Loki
* type 1 AppImages don't get registered
* type 2 AppImages work fine
* Same issue in the deb and in the appimaged AppImage
* Hence, not related to launchd (but possibly to libarchive?)

As per https://github.com/probonopd/AppImageKit/issues/259#issuecomment-263650225
(Let's continue the thread here)

**Comment by probonopd** [comment]
I can preproduce this issue on `maui-2.1-64bit.iso` with appimaged continuous-2-g6a7293f installed from the deb.

**Comment by probonopd** [comment]
```
sudo apt remove appimaged
./appimaged-x86_64.AppImage --install
# Log out of the desktop session and log in again
```

**Comment by lucasfs7** [comment]
I tried the new release, but with no success... the leadpad app works, but this time without the icon, and hyper and krita didn't worked

tried with version `continuous-2-g6a7293f`

**Comment by probonopd** [comment]
You are right, I can reproduce the issue but do not know the cause yet.

**Comment by lucasfs7** [comment]
let me know if you need any kind of test to help with it

**Comment by probonopd** [comment]
Should hopefully be fixed in ed07cfb, please let me know if it works for you now.

**Comment by lucasfs7** [comment]
@probonopd it worked now... thanks for the help :smile: the only thing I noticed is that when I download a `.AppImage` file the `appimaged` only works after I change the permission of the downloaded file, it would be great if it could recognize the file and change the permission automaticaly for me...

btw, great work with appimaged project, loving it

**Comment by probonopd** [comment]
Does it also not change the permission of the Leafpad (type 2) AppImage?

**Comment by lucasfs7** [comment]
the leafpad app works perfectly, I download and it shows up in the application launcher

**Comment by lucasfs7** [comment]
I noticed that some apps, like [rambox](http://rambox.pro/) when I download and change permission, it appears in the applications launcher but when I open it, it shows the icon in the dock but closes in seconds... when I run it from cli I get the this error:
```
$  ~ ./bin/Rambox-0.4.5-x64.AppImage 
/tmp/.mount_DTOATp
1767 1731
/tmp/.mount_DTOATp/AppRun: line 43: exec: : not found
```

**Comment by probonopd** [comment]
You are running into https://github.com/electron-userland/electron-builder/issues/827. File a request with the application author and ask them to update electron-builder and release a new AppImage using it.

**Comment by lucasfs7** [comment]
ah, ok... I will do that... thanks

**Comment by probonopd** [comment]
Fixed in https://github.com/probonopd/AppImageKit/commit/168d1e0c2ef564244d4828bd47acc236724ac9c8. Latest continuous build contains the fix.

**Comment by lucasfs7** [comment]
it's working perfectly now... thank you @probonopd
