### ISSUE TITLE
execv error: Exec format error

### ISSUE THREAD

**Issue by chrisnharvey** [probonopd/AppImageKit#31]
So I got Cheese to work correctly by running my AppRun script directly.

I packaged the AppImage using the ```package``` binary in AppImageAssistant.AppDir, but I'm getting the following error when running the AppImage.

```execv error: Exec format error```

**Comment by probonopd** [comment]
Can you upload what you have so that I can have a look?

**Comment by chrisnharvey** [comment]
Of course, please find my AppImage file from the following link:

https://www.dropbox.com/s/ahbv8gw8auae0pz/Cheese.app?dl=0

**Comment by chrisnharvey** [comment]
I'm guessing this is an issue with my compiled ```runtime``` binary, as I compiled AppImageKit manually because I can't seem to get AppImageAssistant to run on my 64 bit Arch Linux box.

I'm going to try running the pre-compiled AppImageExtract on AppImageAssistant (from Github releases) and see if that solves my issue.

**Comment by chrisnharvey** [comment]
That didn't work either. Same execv error.

**Comment by chrisnharvey** [comment]
I think this is an issue I'm having with ```runtime```. I created an AppImage with ```package``` which worked, but running it throws the execv error. But if I extract it with AppImageExtract, then run the AppRun script directly, then it works. So everything in the AppImage should work, it just can't be run as an image.

**Comment by probonopd** [comment]
what does `file ./runtime` say?

**Comment by chrisnharvey** [comment]
```file ./runtime``` gives the following output.

```
./runtime: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=03e8166ede343910d55448e6c3e132da6de55f72, stripped
```

**Comment by probonopd** [comment]
Looks correct for a x86_64 binary. Dropbox link not wokring

**Comment by chrisnharvey** [comment]
My apologies. I renamed it to an ISO file so I could see the contents. It should work now.

**Comment by probonopd** [comment]
Your AppRun file is missing a shebang. Do not forget to chmod a+x it.

```
#!/bin/bash

export APPDIR="$(dirname "$(readlink -f "$0")")"
export PATH="$APPDIR/usr/bin/:$PATH"
export LD_LIBRARY_PATH="$APPDIR/usr/lib:$PATH"
export XDG_DATA_DIRS="$APPDIR/usr/share/:/usr/share/:$XDG_DATA_DIRS"

"$APPDIR"/usr/bin/cheese $@
```

With the one above it works.

**Comment by probonopd** [comment]
By the way, your icon is wrong (Cheese has its own) and the desktop file should be `cheese.desktop` rather than `AppRun.desktop`

**Comment by chrisnharvey** [comment]
I can't believe I missed that, my bad.

Many thanks for your help with this. Very much appreciated.

**Comment by probonopd** [comment]
Futhermore, you can use the standard AppRun as it exports `XDG_DATA_DIRS` automatically. Just change your `cheese.desktop` to

```
[Desktop Entry]
Name=Cheese
Exec=cheese
Icon=cheese.png
StartupNotify=true
X-AppImage-Title=Cheese
X-AppImage-Version=3.16.1
X-AppImage-Release=1
X-AppImage-URL=http://www.gnome.org/projects/cheese/
X-AppImage-Developer=
X-AppImage-Licenses=GPL
X-AppImage-ID=cheese
X-AppImage-SourcePackages=cheese-3.16.1-2-x86_64.pkg.tar.xz;cheese-3.16.1-2-x86_64.pkg.tar.xz;xdg-utils-1.1.0.git20150323-1-any.pkg.tar.xz
X-AppImage-Tags=linker,archlinux
```

and rename the icon to cheese.png

**Comment by probonopd** [comment]
It also looks like your app is not finding its icons yet
