### ISSUE TITLE
Docs: "Creating AppImages" guide mentions AppRun as a file, but never explains what it is

### ISSUE THREAD

**Issue by JonasT** [probonopd/AppImageKit#314]
The guide "Creating AppImages" https://github.com/probonopd/AppImageKit/wiki/Creating-AppImages mentions AppRun as a file, but never explains what it is. I know this information is somewhere else (e.g. also in the specs), but the info about what it is and where to best get such a file should really be added to the "Manually creating an AppDir" section.

**Comment by probonopd** [comment]
Thanks @JonasT, added.
