### ISSUE TITLE
Docs: Explain where to get appimagetool

### ISSUE THREAD

**Issue by JonasT** [probonopd/AppImageKit#315]
The website https://appimage.org does a lot of very vague examples, and then as a first piece of useful information it links directly to "Creating AppImages" article, here: https://github.com/probonopd/AppImageKit/wiki/Creating-AppImages

This article tells user to use the appimagetool in the section "Manually creating an AppDir" (which at least I have found to be the natural first thing to read) - but nothing the user has read by following the links from the website so far has actually explained where to *get* that tool, and in that article it's also not linked/referenced to any place where to get it.

The most obvious way to fix it would be to link the mention of "appimagetool" to some small wiki page that explains where to get it. (e.g. similar to the main README.md of the project)

**Comment by probonopd** [comment]
Thanks for pointing this out @JonasT. Your input is very valuable. Good and easy documentation for beginners is really important to me, so please continue to let me know what you are struggling with as a newcomer to AppImage.
