### ISSUE TITLE
Question: Embedding another AppImage

### ISSUE THREAD

**Issue by hyronx** [probonopd/AppImageKit#316]
I've created a docker AppImage for a build toolchain (#298) for building AppImages on CentOS 6. Now I'm unsure what is the best (or recommended) way to make them work together. 
I think there are three options:

1. Embedded the docker AppImage:
The image is directly included in the toolchain and can easily be updated by simply replacing it.
Perhaps the compression isn't so good anymore.

2. Place the files into /var etc.:
Docker is also fully included and maybe better compressed. Updating isn't that easy anymore.

3. Download the docker image somewhere:
The toolchain could download the newest docker AppImage somewhere. Easy updating but some setup on first toolchain run needed.

In my opinion embedding may be not too bad and follow the purpose of AppImage but like already said I'm not sure.

**Comment by probonopd** [comment]
I don't know what is best, looks like some experimentation is needed here.

Some questions:
* How large (MB) is the whole thing?
* Is the Docker part needed at runtime or could we convert it to a simple chroot?
* Does one need to write to the chroot, e.g., if one wants to use an additional library?

Some considerations:
* AppImages are always read-only, wouldn't that hurt here?
* AppImages can have delta updates which may be handy

**Comment by hyronx** [comment]
I made it for test purposes from an Arch Linux package and the whole thing now has a size of 24.3MiB.
It contains docker and bridge-utils but I don't think a chroot works. The problem is the docker daemon which of course needs root rights...

The docker image might work as sysroot for Qt Creator but I haven't tested this so far.
But is an IDE really in this toolchain? There are so many programming languages and IDEs out there, most devs will want to use their favorite one. 

We should focus more on creating an standardized environment for building AppImages rather then applications I think.

**Comment by probonopd** [comment]
I didn't think about including Qt Creator or any other IDE in the toolchain, but rather the question is whether Qt Creator or any other IDE could use this toolchain.

With "toolchain", do we just mean the compiler or also the glibc and other basic libraries to compile against? Something like Yocto might possibly be interesting in this area.

**Comment by hyronx** [comment]
Well, in general this should be possible or at least one of our goals. 

It's too late for me now to have a really good idea here but probably some new C/C++ compilers (gcc-6/clang-3.9 etc.) linked against an old glibc..

**Comment by probonopd** [comment]
@hyronx is this still of concern or can it be closed?

**Comment by hyronx** [comment]
No, can be closed.
