### ISSUE TITLE
AppImageTool is missing a dependency

### ISSUE THREAD

**Issue by ParaplegicRacehorse** [probonopd/AppImageKit#321]
Okay, so I ran it without giving it an AppDir as a target, but I got this error.

> :~/Scripts$ ./appimagetool-x86_64.AppImage 
> WARNING: appstream-util is missing, please install it if you want to use AppStream metadata
> SOURCE is missing

The error went away after installing, via distro packaging, appstream-util but I thought the whole point of AppImages was to avoid all that?

**Comment by probonopd** [comment]
`appstream-util` is an optional dependency. It is recommended to be installed but `appimagetool` can also work without it.
