### ISSUE TITLE
Automatically Integrate With System

### ISSUE THREAD

**Issue by sabrehagen** [probonopd/AppImageKit#326]
Hi,

We need to run unattended setup of our application. We want our application to always be integrated with the system. The modal below shows on launch if the application hasn't been integrated with the system. Given we can't have any human interaction during setup, is there a flag we can use to skip this modal and automatically integrate with the system?

![image](https://cloud.githubusercontent.com/assets/1094600/21910612/e2bc2a9a-d970-11e6-905b-e3ff04dfd6e2.png)

Thanks

**Comment by probonopd** [comment]
Can you install the optional `appimaged` daemon on the systems? That integrates all AppImages automatically without asking the user.

**Comment by sabrehagen** [comment]
Given our current constraints, no, we can't have `appimaged` already on the systems.

**Comment by probonopd** [comment]
Currently there is no way to automatically register all AppImages with the system without showing this dialog. The dialog can be suppressed, but then the AppImages are not integrated into the system.

Or `appimaged` can be used with integrates all AppImages into the system without the need for making them executable or asking questions.
