### ISSUE TITLE
Suggestion: mention settings persistence on the landing page

### ISSUE THREAD

**Issue by dandv** [probonopd/AppImageKit#327]
As a user who was exposed for the first time to the AppImage concept (seems really cool! I'm downloading the DigiKam image), I'd like to see at http://appimage.org how application settings are handled. Are they presumably saved in the user's home directory? I think it would be worth adding this as one of the advantages (Easy / Trusted / Fast / Proven etc.). https://github.com/probonopd/AppImageKit/blob/master/README.md doesn't say anything about "settings" or "config" files.

PS: DigiKam is also worth being in the list of apps that provide appimages, next to "Krita, Subsurface, and MuseScore" (I have never heard of the last two in ~20 years of using various Unices).

**Comment by probonopd** [comment]
AppImage does not change or interfere with the way applications handle settings in any way. So it is up to the application.

Added digiKam and KDevelop to the landing page. A more exhaustive list is on https://github.com/probonopd/AppImageKit/wiki/AppImages. Help spread the word :-)
