### ISSUE TITLE
documentation for uninstalling appimaged

### ISSUE THREAD

**Issue by andrewbanchich** [probonopd/AppImageKit#330]
I can't seem to find it anywhere. What's the best practice for completely removing it after it's been installed?

**Comment by probonopd** [comment]
Depends on how you installed it:

* If you installed it using a distribution package (deb, rpm, etc.) then you use your package manager to uninstall it
* If you installed it using the `--install` option, then you use `appimaged --uninstall` to remove it. For safety reasons it will not actually uninstall but give you instructions how to do that. https://github.com/probonopd/AppImageKit/blob/666008585e6fb91014294aedbf0a75b087a8e3fe/appimaged.c#L227-L235

**Comment by probonopd** [comment]
@andrewbanchich does this clarify your question? Do you think something should be changed/improved?

**Comment by andrewbanchich** [comment]
@probonopd It would be nice to have that in the GitHub or website docs, but other than that I think the process is good!
