### ISSUE TITLE
Desktop integration script does not find icon when app name has different casing than icon PNG

### ISSUE THREAD

**Issue by phoerious** [probonopd/AppImageKit#341]
When building the AppImage for KeePassXC, I noticed that the desktop integration script didn't install the app icon(s) alongside the desktop file.

After some investigation I found the reason for this. The generated *.wrapper script matches icon file names like this:

```
ICONS=$(find "${APPDIR}/usr/share/icons/" -wholename "*/apps/${APP}.png" 2>/dev/null || true)
```

However, `$APP` is determined from the .desktop file's `Name` attribute like this:

```
APP_FULL=$(sed -n -e 's/^Name=//p' "${DESKTOPFILE}" | head -n 1)
APP=$(echo "$APP_FULL" | tr -c -d '[:alnum:]')
```

So when the casing of this name does not correspond to the casing of the icon file name, this will fail because the script then searches for `*/apps/KeePassXC.png` instead of `*/apps/keepassxc.png`.
Having filenames with uppercase characters in usr/share/icons/** is very rare, so I would suggest converting `$APP` to lowercase before searching for icons or at least support both.

For the time being, I hotpatched the .wrapper script like this:

```
sed -i 's/-wholename "\*\/apps\/\${APP}.png"/-wholename "*\/apps\/keepassxc.png"/' ./usr/bin/keepassxc_env.wrapper
```

**Comment by probonopd** [comment]
Would using `-iwholename` instead of `-wholename` solve this?

**Comment by phoerious** [comment]
Yes, that would work, too.

**Comment by phoerious** [comment]
That was fast. Thanks. :-)
