### ISSUE TITLE
Update description of AppImage components

### ISSUE THREAD

**Issue by ShalokShalom** [probonopd/AppImageKit#342]
https://github.com/probonopd/AppImageKit/blob/master/README.md#appimagekit

5 names, AppImageKit seems to be the name for the collection of the 4 below

then see the releases: https://github.com/probonopd/AppImageKit/releases/tag/knowngood

3 names, 2 of them are new

**Comment by probonopd** [comment]
The latest branch is https://github.com/probonopd/AppImageKit/blob/appimagetool/master/README.md. Hope this clarifies it.

**Comment by ShalokShalom** [comment]
To be honest, its even more confusing now to me, where is this compact view:

https://github.com/probonopd/AppImageKit/blob/master/README.md#appimagekit

**Comment by probonopd** [comment]
AppRun and runtime are still there, but AppImageAssistant has been replaced by `appimagetool` and `apt-appdir` has been replaced by https://github.com/probonopd/AppImages.

But I hear you, https://github.com/probonopd/AppImageKit/wiki/AppImageKit-components should be updated to describe the new components.

**Comment by ShalokShalom** [comment]
I simply like to understand which of the components is doing what - in one single sentence per tool, if possible.

**Comment by probonopd** [comment]
* `appimagetool` - convert an AppDir into an AppImage
* `runtime` - self-mounts an AppImage and runs the contained payload app. Gets embedded into each AppImage by `appimagetool`
* `AppRun` - a file with this name must be in each AppDir. It launches the main payload application
* `appimaged` - optional daemon that integrates AppImages into the system (e.g., menus, icons, file formats)

**Comment by ShalokShalom** [comment]
Oh fine, yeah great.
