### ISSUE TITLE
no version information available error while executing appimage file

### ISSUE THREAD

**Issue by keshavbhatt** [probonopd/AppImageKit#344]
./Ktube_Media_Downloader-x86_64.AppImage  ./Ktube_Media_Downloader-x86_64.AppImage: ./Ktube_Media_Downloader-x86_64.AppImage: no version information available (required by ./Ktube_Media_Downloader-x86_64.AppImage) ./Ktube_Media_Downloader-x86_64.AppImage: ./Ktube_Media_Downloader-x86_64.AppImage: no version information available (required by ./Ktube_Media_Downloader-x86_64.AppImage) ./Ktube_Media_Downloader-x86_64.AppImage: ./Ktube_Media_Downloader-x86_64.AppImage: no version information available (required by ./Ktube_Media_Downloader-x86_64.AppImage) ./Ktube_Media_Downloader-x86_64.AppImage: ./Ktube_Media_Downloader-x86_64.AppImage: no version information available (required by ./Ktube_Media_Downloader-x86_64.AppImage) ./Ktube_Media_Downloader-x86_64.AppImage: ./Ktube_Media_Downloader-x86_64.AppImage: no version information available (required by ./Ktube_Media_Downloader-x86_64.AppImage) ./Ktube_Media_Downloader-x86_64.AppImage: ./Ktube_Media_Downloader-x86_64.AppImage: no version information available (required by ./Ktube_Media_Downloader-x86_64.AppImage) ./Ktube_Media_Downloader-x86_64.AppImage: relocation error: ./Ktube_Media_Downloader-x86_64.AppImage: symbol , version  not defined in file  with link time reference

**Comment by keshavbhatt** [comment]
i resolved this , a lib was missing from the place which i mentioned in main project file.

**Comment by keshavbhatt** [comment]
for future reference the error (no version information available (required by ./Ktube_Media_Downloader-x86_64.AppImage))

is usually given by ldd its not a fault of appimagekit.

**Comment by probonopd** [comment]
Thanks @keshavbhatt
