### ISSUE TITLE
App look a bit odd after packaging with appimagekit

### ISSUE THREAD

**Issue by keshavbhatt** [probonopd/AppImageKit#345]
After packaging with AppImagekit the menu which were shown as global menus are attached to application window which looks odd , also the content shown in qwebview looks bit different those white lines you can see around that <table> in webpage.
 
![changed appearance of application](https://cloud.githubusercontent.com/assets/5965031/22502129/a5e68a40-e891-11e6-8cc6-1bc08fe54b71.png)

![this is the original one](https://cloud.githubusercontent.com/assets/5965031/22502514/2f31359c-e893-11e6-9da7-ff4a345fdf13.png)

**Comment by keshavbhatt** [comment]
Hi i fixed the menu thing by manually copying  **/usr/lib/x86_64-linux-gnu/qt5/plugins/platformthemes**
folder to ktube-media-downloader.AppDir/plugins/ but the webview white lines around <table> tag are still there.

**Comment by keshavbhatt** [comment]
i fixed the webview problem too , the issue was due to naming of application, app's qwebview is configured to use localstorage and since i didn't set up the QApplication::setApplicationName("Ktube");
in main file , i think things were messed up , cause appimages create their .local/appname.appimage/
directory so my app was not reasing that dir , so it was not reading the cached data and prepeared data for webview to load. now my ap perfectly working :) thanks :+1:

**Comment by keshavbhatt** [comment]
Thanks , i solved these problems , my project is live at 
[https://keshavbhatt.github.io/Ktube-media-downloader/](Ktube Media Downloader)

**Comment by probonopd** [comment]
That link goes to a 404 :-(

**Comment by keshavbhatt** [comment]
No it is working for me

**Comment by keshavbhatt** [comment]
Yeah :)
