### ISSUE TITLE
digikam.appimage problem at startup

### ISSUE THREAD

**Issue by marcoparavano** [probonopd/AppImageKit#356]
Hi!
When I launch digikam.appimage a checkbox for integrating to the system appears always even I have answered "Yes" the last time I've launched the application.
On my system I've installed first Xubuntu 16.04 LTS then KDE neon (now at 5.9.1 version).
I've created a quick launch icon in Xubuntu but all the times I launch digikam.appimage (5.5.0.1) the checkbox for integration of the appimage to the system appears let me choose "No" or "Yes".
Gilles Caulier wrote me that is a bug of the appimage and then I ask in this Forum for an answer, thank you.

**Comment by probonopd** [comment]
This sounds like a bug in the `desktopintegration`script shipped in the digiKam AppImage.

You could install the optional `appimaged` daemon, or create a new (empty) file in one of these locations:
* `$HOME/.local/share/appimagekit/no_desktopintegration`
* `/usr/share/appimagekit/no_desktopintegration`
* `/etc/appimagekit/no_desktopintegration`

This should stop the dialog from appearing.

**Comment by marcoparavano** [comment]
How can I install appimaged daemon?

**Comment by probonopd** [comment]
If you are running a deb-based system, download the deb from https://github.com/probonopd/AppImageKit/releases, install it using your package manager. It may be necessary to run `systemctl --user start appimaged`. Log out of your session and log in again.

**Comment by marcoparavano** [comment]
OK: solved with the creation of /etc/appimagekit/no_desktopintegration (empty file)...
