### ISSUE TITLE
Wiki - Similar projects: Singularity

### ISSUE THREAD

**Issue by whit2333** [probonopd/AppImageKit#358]
This is just a quick comment about the wiki. [Singularity](http://singularity.lbl.gov/) might be worth mentioning in the [Similar projects wiki page](https://github.com/probonopd/AppImageKit/wiki/Similar-projects).

Singularity has a "single file" behavior too. I suppose a major difference is that singularity needs to be installed on the machine. Other than this big difference they seem very similar but I am rather new to AppImages so I could be way wrong. I look forward to learning more. Cheers.

**Comment by probonopd** [comment]
Thanks @whit2333 for pointing this out. Didn't know. Looks like Singularity is more a chroot/container environment:

> So if the host system is running RHEL6 but your application runs in Ubuntu, you can create an Ubuntu image, install your applications into that image, copy the image to another host, and run your application on that host in it’s native Ubuntu environment!

Sounds like this is not intended for software distribution to end users.
