### ISSUE TITLE
libglib-2.0.so.0 missing when starting .AppImage, but mount + ./AppRun works

### ISSUE THREAD

**Issue by konradkonrad** [probonopd/AppImageKit#369]
Hi! I have an error that is most likely due to some misunderstanding(?):

I create an AppImage that bundles python. I build it with an ubuntu:12.04.5 docker container, roughly following what [0] and [1] are doing. [This is the recipe](https://github.com/konradkonrad/raiden/blob/bundling/docker/build.Dockerfile) followed by [this line](https://github.com/konradkonrad/raiden/blob/bundling/Makefile#L66) to actually generate the image (fuse not available while building the Dockerfile).

The program runs fine, if it is mounted via `mount -o loop my.AppImage /mnt/loop`. 

However, when launching directly in a ubuntu:16.10 container (with `fuse` installed), by calling `./my.AppImage`, it dies with
```
my.AppImage: error while loading shared libraries: libglib-2.0.so.0: cannot open shared object file: No such file or directory
```
l am quite puzzled, what I may be missing? 
[0] https://notabug.org/themightyglider/Python_and_pygame_AppImage_tutorial/src/master/howto_py_appimage.sh
[1] https://github.com/probonopd/AppImages/blob/master/recipes/pythongtk3hello/Recipe

For reference, here the steps to reproduce:
```
REPRODUCE=/tmp/reproduce
git clone --branch bundlingbug --depth=1 https://github.com/konradkonrad/raiden $REPRODUCE
cd $REPRODUCE
make bundle  # you will need to have `docker` installed

# testing on different distribution:
docker run --rm -it -v $REPRODUCE/dist:/data --privileged ubuntu:16.10
# now inside container
apt-get update && apt-get install -y fuse

# now run the AppImage (fails)
/data/raiden--x86_64.AppImage

# now, still inside container, run after mounting (works) 
# (well, there will be a problem with program specific environment, but launching works)
mkdir -p /mnt/loop
mount -o loop /data/raiden--x86_64.AppImage /mnt/loop
cd /mnt/loop
./AppRun
```

**Comment by konradkonrad** [comment]
One thing to add, why this is puzzling. It appears that nothing inside the AppImage is linked to `libglib`; this comes back empty:
```
root@02c76bac4390:/mnt/loop# find . -exec ldd {} \; |& grep glib
root@02c76bac4390:/mnt/loop#
```

**Comment by probonopd** [comment]
Can you please upload the AppImage for testing?

**Comment by konradkonrad** [comment]
> Can you please upload the AppImage for testing?

sure, here you go https://www.sendspace.com/file/f7jlrt

**Comment by probonopd** [comment]
Running this on Ubuntu 16.04, I get

```
me@host:~$ /home/me/Downloads/raiden--x86_64.AppImage 
AppRun started
/tmp/.mount_G5BEeh/usr/bin:/tmp/.mount_G5BEeh/usr/sbin:/tmp/.mount_G5BEeh/usr/games:/tmp/.mount_G5BEeh/bin:/tmp/.mount_G5BEeh/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
raiden
/tmp/.mount_G5BEeh/usr
/tmp/.mount_G5BEeh/usr/bin:/tmp/.mount_G5BEeh/usr/sbin:/tmp/.mount_G5BEeh/usr/games:/tmp/.mount_G5BEeh/bin:/tmp/.mount_G5BEeh/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
/tmp/.mount_G5BEeh/AppRun: 20: exec: raiden: not found
```

**Comment by konradkonrad** [comment]
Thank you for taking your time to look into this!

I guess I worded my question badly, but I believe I understood now: `libglib` is a runtime dependency for the AppImage launcher? Plus, it is probably rare to find a linux installation without it in the wild, so I guess my testcase (docker container) is somewhat artificial. So I take it, the minimum system runtime requirements are `fuse` (+permissions) and `libglib`? At least I can get the AppImage to launch after I installed both of these :hammer: 

> That file has `#!usr/bin/python` - is that a typo?

That's an artifact from desperately trying to make the bundled python work. But it is wrong obviously, thanks for pointing it out!

But there is something else: in order to get my bundled python to work, I have to point [`PYTHONHOME` to `${HERE}/usr`](https://github.com/konradkonrad/raiden/blob/41d9746632756fcfa861936048f3326260a95c66/docker/apprun.sh#L16) in `AppRun`, so it doesn't [default to `prefix/lib/pythonversion` anymore](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONHOME). Is there a way to add this to the [standard `AppRun` environment](https://github.com/probonopd/AppImageKit/blob/appimagetool/master/resources/AppRun) without rolling my own script?

> >RuntimeError: No Ethereum accounts found in the user's system

> There is no known way how an AppImage could pretend a certain user being installed in the system. Likely that code needs to be rewritten.

That error is fine for now -- my concern currently is getting the AppImage to launch correctly. As I commented earlier
> `(well, there will be a problem with program specific environment, but launching works)`

the program has some user-environment dependencies (it searches `$HOME` for a certain configuration), but those are not part of the AppImage. I would agree however, that the error handling needs to be rewritten to be more helpful :)

So one more question: what is the recommended version of AppImageKit to run? The recipes I build upon (see first post) use the latest [`functions.sh` script from the `master` branch](https://github.com/probonopd/AppImages/blob/28546c57976ae7ba8c5f2e1142db52421b0c8d30/recipes/pythongtk3hello/Recipe#L17). That seems somewhat brittle. Is there an (upcoming) release, that I should rely on?

**Comment by probonopd** [comment]
The runtime requirements for [`runtime.c`](https://github.com/probonopd/AppImageKit/blob/appimagetool/master/runtime.c) should be

- /lib64/ld-linux-x86-64.so.2
- libfuse.so.2
- libpthread.so.0
- libz.so.1
- libc.so.6
- libdl.so.2

Not sure where the `libglib` dependency of your AppImage is coming from.

> But there is something else: in order to get my bundled python to work, I have to point PYTHONHOME to ${HERE}/usr in AppRun, so it doesn't default to prefix/lib/pythonversion anymore. Is there a way to add this to the standard AppRun environment without rolling my own script?

You could use [`AppRun.c`](https://github.com/probonopd/AppImageKit/blob/appimagetool/master/AppRun.c) which [does this for you](https://github.com/probonopd/AppImageKit/blob/adaf3c5a2576da78d7268836c02f04c0106149d9/AppRun.c#L124-L126).

> So one more question: what is the recommended version of AppImageKit to run?

Please use the default branch, `appimagetool/master`.

> The recipes I build upon (see first post) use the latest `functions.sh` script from the master branch. That seems somewhat brittle. Is there an (upcoming) release, that I should rely on?

`functions.sh` is not part of AppImageKit at all. How to create a working AppDir is outside of the scope of AppImageKit.

`functions.sh` is a script internally used by the AppImages project, the repository I use to provide some example AppImages. The default branch of the AppImages project is `master`.

**Comment by konradkonrad** [comment]
> You could use AppRun.c which does this for you.

That also only sets `PYTHONPATH` and not `PYTHONHOME`

> `functions.sh` is not part of AppImageKit at all. How to create a working AppDir is outside of the scope of AppImageKit.

> `functions.sh` is a script internally used by the AppImages project, the repository I use to provide some example AppImages. The default branch of the AppImages project is master.

Okay, got it. thank you!

**Comment by probonopd** [comment]
> That also only sets PYTHONPATH and not PYTHONHOME

Can you give a minimal example where PYTHONHOME is needed?

**Comment by konradkonrad** [comment]
I can not reproduce the problem anymore, so I'll call it a false alarm. Thanks for your help!

**Comment by probonopd** [comment]
OK, thanks for the update.
