### ISSUE TITLE
Simple inotify script to monitor Downloads directory for newly-downloaded AppImages and make them executable

### ISSUE THREAD

**Issue by ericfont** [probonopd/AppImageKit#371]
[I made this simple script which you can put in .xinitrc so that you'll never have to manually chmod +x for newly-downloaded AppImages](https://gist.github.com/ericfont/5882366828ceef3f42a48da1b995cb7f)
```
#!/bin/bash
# monitor ~/Downloads for newly created .AppImage files, and make them executable

DOWNLOADS_FOLDER=~/Downloads

inotifywait -m $DOWNLOADS_FOLDER | 
while read a b file;
do 
  [[ $b == *CREATE* ]] && [[ $file == *.AppImage ]] && chmod +x "$DOWNLOADS_FOLDER/$file";
done
```

Make sure you install inotify-tools.

**Comment by ericfont** [comment]
I guess not really an issue, so you can close this, but maybe worth sharing in the wiki or somewhere else.

**Comment by probonopd** [comment]
Hi @ericfont, have you checked out the appimaged daemon? That works in a very similar way but also puts things into the menu.

**Comment by ericfont** [comment]
Oh gosh, that looks great!
