### ISSUE TITLE
How to create an appimage from a .yml?

### ISSUE THREAD

**Issue by Sod-Almighty** [probonopd/AppImageKit#375]
I'm trying to assemble an AppImage containing [sbcl](http://www.sbcl.org/) (and an sbcl script, although that's by-the-by). The most obvious way I can see is to write a `.yml` file to pull `sbcl` from the Debian repo and put it into an `.AppImage`.

Your [documentation](https://github.com/probonopd/AppImageKit/wiki/Creating-AppImages) —
> Convert existing binary packages. This option might be the easiest if you already have up-to-date packages in place, ideally a ppa for trusty or earlier or a debian repository for oldstable. In this case, you can write a small .yml file and **in many cases are done** with the package to AppImage conversion.

— seems to suggest that `appimagetool-x86_64.AppImage` can be used to create an `.AppImage` from a `.yml`; but that doesn't seem to be possible. Further research suggests that each `.yml` needs to be read by [its own batch file](https://github.com/probonopd/AppImages/blob/master/recipes/leafpad/Recipe), custom-written for the purpose. **If I have to write a new batch file for every project, why bother with the `.yml` file at all?**

Isn't there a standard way to create an `.AppImage` file just by writing a `.yml` and feeding it into a generic program? I thought that was the whole point.

I tried using the apparently generic batch file [here](https://github.com/probonopd/AppImages/blob/master/recipes/meta/Recipe), but it tried to use the sbcl `.deb` file without first `apt-get`ting it.

On a similar note, how would I insert extra files into the `.AppImage` during the process? Should I add something to a `script:` section of the `.yaml`?

**Comment by probonopd** [comment]
[This script](https://raw.githubusercontent.com/probonopd/AppImages/master/recipes/meta/Recipe) can run .yml files. You __don't__ have to write a new batch file for every project.

You can find many examples at
https://github.com/probonopd/AppImages/tree/master/recipes/meta
and documentation at https://github.com/probonopd/AppImages/blob/master/YML.md.

If you have questions, AppImage developers are on #AppImage on irc.freenode.net.
