### ISSUE TITLE
AppRun shouldn't `chdir` to `usr`

### ISSUE THREAD

**Issue by Sod-Almighty** [probonopd/AppImageKit#380]
`AppRun.c` contains code to _deliberately_ `chdir` to the `./usr` directory prior to executing the payload. I see no reason for this whatsoever.

It means that, to refer to files in the AppImage root, I'd have to do stuff like this:
```
Exec=ruby ../myscript.rb
```
Even if I put `myscript.rb` in a directory of some kind - e.g. './usr/share' - I'd still need to use `..` to reach it. What's the point?

Unless there's a good reason for it, the behaviour should be changed. I shall issue a pull request.

**Comment by Sod-Almighty** [comment]
Argh! I'm tearing my hair out here.

How do I bring my fork up to date with the current project? I'm getting errors no matter what I do:
```
# git merge -s recursive -X theirs origin/master
error: merge is not possible because you have unmerged files.
hint: Fix them up in the work tree, and then use 'git add/rm <file>'
hint: as appropriate to mark resolution and make a commit, or use
hint: 'git commit -a'.
fatal: Exiting because of an unresolved conflict.```
```
```
git checkout appimagetool/master
.gitignore: needs merge
.travis.yml: needs merge
AppRun.c: needs merge
README.md: needs merge
build.sh: needs merge
runtime.c: needs merge
error: you need to resolve your current index first
```
```
# git pull appimagetool/master
U	.gitignore
U	.travis.yml
U	AppRun.c
U	README.md
U	build.sh
U	runtime.c
Pull is not possible because you have unmerged files.
Please, fix them up in the work tree, and then use 'git add/rm <file>'
as appropriate to mark resolution, or use 'git commit -a'.
```
I haven't changed any of these other files!!! Why won't it just let me overwrite them from upstream!?
I changed `AppRun.c` and **nothing else**, despite what `git` seems to think.

I'm unfamiliar with `git`, and about ready to throw the computer out the window.

**Comment by probonopd** [comment]
> AppRun.c contains code to deliberately chdir to the ./usr directory prior to executing the payload. I see no reason for this whatsoever.

It is explained [here](https://github.com/probonopd/AppImageKit/wiki/Creating-AppImages/). `AppRun.c` does a `chdir()` do `$APPDIR/usr` prior to executing the payload so that binaries can be binary-patched to remove a hardcoded `/usr`.

> Your binary, myapp, must not contain any hardcoded paths that would prevent it from being relocateable. You can check this by running `strings MyApp.AppDir/usr/bin/myapp | grep /usr`. (...) If you prefer not to change the source code of your app and/or would not like to recompile your app, you can also patch the binary, for example using the command `sed -i -e 's|/usr|././|g' MyApp.AppDir/usr/bin/myapp`. This usually works as long as the application is not doing a `chdir()` which would break this workaround, because then `././` would not be pointing to `$APPDIR/usr` any more. You can run `strace -echdir -f ./AppRun` to see whether the application is doing a `chdir()` (99% of GUI applications don't).

If you don't like, or need, the `chdir()`, then you can either comment it out and recompile `AppRun.c`, or just write your own `AppRun`, e.g., in bash.

**Comment by probonopd** [comment]
> How do I bring my fork up to date with the current project? I'm getting errors no matter what I do

This is because the source code in this repository has changed since you pulled it. You need to do another git pull before you do, commit, and push your changes.

**Comment by Sod-Almighty** [comment]
> You need to do another git pull

I tried that. It all went to hell.
