### ISSUE TITLE
CMake Error:

### ISSUE THREAD

**Issue by jyapujuju** [probonopd/AppImageKit#386]
$ git clone https://github.com/probonopd/AppImageKit.git
$ cmake .
CMake Error: The source directory "/home/user/Documents/appimage/AppImageKit" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

**Comment by probonopd** [comment]
The current branch, `appimagetool/master`, does not use CMake. The compilation is documented in https://github.com/probonopd/AppImageKit#building.
