### ISSUE TITLE
How to make AppImagetool.AppImage from appimagetool.AppDir folder?

### ISSUE THREAD

**Issue by chdslv** [probonopd/AppImageKit#392]
After executing build.sh, I get the folder appimagetool.AppDir. How to create an appimagetool.AppImage from that folder manually?

**Comment by probonopd** [comment]
The AppImage project supplies binaries that application developers can use. These binaries are built using the CentOS 6 Docker on Travis CI build system in this repository. As an application developer, you do not have to use the build system. You only have to use the build systems when contributing to AppImageKit, when needing another architecture than x86_64, or when trying to reproduce our binaries.

if you want to compile yourself, the recommended way is to use
https://github.com/probonopd/AppImageKit/blob/appimagetool/master/.travis.yml
on CentOS 6 Docker on Travis CI.

**Comment by chdslv** [comment]
I've never used Cent OS. I am on Ubuntu. I am not an application developer. That build.sh created the appimagetool.AppDir. It didn't create the appimagetool.AppImage. So the question. I don't know how to use docker.  Is there a script to use on Ubuntu?

I can use downloaded precompiled Appimagetool-x86_64.AppImage to create the appimage. Or, use the old way to create the appimage. 

2nd question; I read here somewhere that to compile AppRun to do, gcc ../AppRun.c -o AppRun, so I thought it would work the same way with runtime.c, but when I do that, I get 
In file included from runtime.c:32:0:
squashfuse.h:28:17: fatal error: dir.h: No such file or directory
 #include "dir.h"
                 ^
How do I make executable runtime from runtime.c?
I also wrote you an email earlier.

**Comment by probonopd** [comment]
> I am not an application developer.

AppImageKit contains tools for application developers to distribute applications to end users. So please ask the developer of the application(s) you are interested in to provide an AppImage for download.

**Comment by chdslv** [comment]
Tell me how to create executable runtime from runtime.c?

**Comment by probonopd** [comment]
https://github.com/probonopd/AppImageKit#building

**Comment by chdslv** [comment]
OK, thanks
