### ISSUE TITLE
ImportError: libp11-kit.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by ndk-** [probonopd/AppImageKit#394]
OS: Current Gentoo with OpenRC
HW:  Intel Xeon v3
Problem package: OpenShot-v2.3.1-x86_64.AppImage
Issue: ImportError: libp11-kit.so.0: cannot open shared object file: No such file or directory

Similar issue arises with kdenlive AppImage, but it impacts a partial functionality only.
"Cannot load library $DIR/kdenlive/plugins/kf5/kfilemetadata/kfilemetadata_ffmpegextractor.so: (libp11-kit.so.0: cannot open shared object file: No such file or directory)"

**Comment by probonopd** [comment]
Please report this as a bug to the project(s) who have made the AppImage. This is not an issue in AppImageKit itself.

**Comment by ndk-** [comment]
My bad. I was assuming that this one is also yours:
https://github.com/probonopd/AppImages/blob/master/excludelist#L109

**Comment by probonopd** [comment]
True, it is, but it's the AppImages project. The AppImages project contains recipes for example AppImages I am doing. With these I am not targeting Gentoo. But other people making AppImages can decide that they may want to target Gentoo, and bundle libraries like libp11-kit.so.0.
