### ISSUE TITLE
64 bit link broken on github.io

### ISSUE THREAD

**Issue by SethDusek** [probonopd/AppImageKit#51]
https://github.com/probonopd/AppImages/releases/download/travis/Subsurface-4.5.1.278-x86_64.AppImage gives me a 404

Running the 32 bit with chmod +x gives me

>./Subsurface-4.5.1.251-i386.AppImage: error while loading shared libraries: libfuse.so.2: cannot open shared object file: No such file or directory

**Comment by hideout** [comment]
me too 404 ;/

2015-12-13 15:54 GMT+01:00 SethDusek <notifications@github.com>:

**Comment by probonopd** [comment]
Downloads have been moved to https://bintray.com/probono/AppImages - website needs to be updated accordingly.

**Comment by hideout** [comment]
thx ;)

2015-12-13 16:28 GMT+01:00 probonopd <notifications@github.com>:
