### ISSUE TITLE
[AppImageMonitor] CLI option for setting apps directory?

### ISSUE THREAD

**Issue by chrisnharvey** [probonopd/AppImageKit#56]
It would be great if AppImageMonitor had an option for setting the location of the apps directory via a CLI option.

```bash
./monitorAppImages.sh --appimage-dir /Apps
```

Some other features that would be cool:

1. Multiple app paths i.e. ```/Apps``` or ```~/Apps```.
2. Install .desktop file to ```~/.local/share/applications``` if the app image is in ```~/Apps``` or install the .desktop file to ```/usr/share/applications``` if the desktop file is in a global location (i.e. ```/Apps```)

Please let me know your thoughts. I'm happy to build this functionality and submit a pull request if this is something that would be useful for others.

**Comment by probonopd** [comment]
After playing a bit with vala, I think it would be best to implement a new version of `appimaged` in vala using libarchive or something like that to extract the desktop file from the AppImages. With nice `systemd` integration.

**Comment by RazZziel** [comment]
> It would be great if AppImageMonitor had an option for setting the location of the apps directory via a CLI option.

> Multiple app paths i.e. /Apps or ~/Apps.

That's already possible, you can specify as many directories as you want as parameters

```
./monitorAppImages.sh /Apps /media/usb/Apps /mnt/ssh/Apps
```
```
AppImageMonitor.AppImage /Apps /media/usb/Apps /mnt/ssh/Apps
```

> Install .desktop file to ~/.local/share/applications if the app image is in ~/Apps or install the .desktop file to /usr/share/applications if the desktop file is in a global location (i.e. /Apps)

That's only possible if the daemon is run as root, which I haven't thought about, but it may be interesting (and @probonopd has already implemented it in `desktopintegration`)

**Comment by probonopd** [comment]
Yes, I had started the latter, but am not sure if it's really working in `desktopintegration` yet.

**Comment by RazZziel** [comment]
Since specifying multiple AppImages is taken care of, and system-wide installation belongs to https://github.com/probonopd/AppImageKit/issues/62, I guess this task can be closed
