### ISSUE TITLE
AppImageAssistant 0.9.2 stopped working on ArchLinux

### ISSUE THREAD

**Issue by RazZziel** [probonopd/AppImageKit#6]
AppImageAssistant 0.9 runs perfectly fine, but AppImageAssistant 0.9.2 and 0.9.3 don't.

I receive this error in both:

```
Traceback (most recent call last):
  File "/tmp/.mount_xzkzoH/AppImageAssistant", line 54, in <module>
    import  gtk, vte
RuntimeError: could not find _PyGtk_API object
```

If I unpack the AppImage and run the AppRun, I get the same error, but if I run the AppImageAssistant instead, it works correctly.

If I place the AppRun from 0.9 into 0.9.3, it works, but as soon as I add this, it fails:

```
PYTHONPATH=./usr/share/pyshared:"$PYTHONPATH"
```

**Comment by CyberKiller40** [comment]
Affects also OpenSUSE 13.1 (64bit) and this distro uses python2 when called as 'python':
ck@molochv2:~> python --version
Python 2.7.6

(the same happens with AppDirAssistant 0.3.3)

**Comment by probonopd** [comment]
Since https://github.com/probonopd/AppImageKit/commit/a748c0f5dfcf6e941af43bac343abcf5af6e2e19 it should theoretically be python3 compatible, although I have not tried.

As for the segfault, that is really strange. Where did you get your binary from?

**Comment by CyberKiller40** [comment]
I got them from portablelinuxapps.org so I guess they're official.

AppImageAssistant from the releases throws the same error, both packaged and extracted. (I gave both python-gtk and python-vte installed)

(interesting - in AppDirAssistant, after uncompressing, AppRun was a binary, and here it's a script)

**Comment by probonopd** [comment]
Please check if 635c2705bfae48013ee726dc0902feeadf0a9958 solves this, since now python2 is used explicitly rather than python.

**Comment by Manouchehri** [comment]
Still cannot run.
```
/tmp > ./AppImageKit/AppImageAssistant
Traceback (most recent call last):
  File "/tmp/.mount_WMTzac/AppImageAssistant", line 54, in <module>
    import  gtk, vte
RuntimeError: could not find _PyGtk_API object
```

**Comment by ShadowCreator** [comment]
Even building with the build.sh script I'm getting this failure

**Comment by probonopd** [comment]
@ShadowCreator are you referring to a general error with AppImages or to a runtime error when trying to run AppImageAssistant?

**Comment by ShadowCreator** [comment]
Sorry I wasn't more specific, AppImageAssistant isn't working. AppImages
such as subsurface run flawlessly.

**Comment by probonopd** [comment]
Thanks ShadowCreator. I will not invest time in making AppImageAssistant work on Arch because I am not an Arch user but would welcome pull requests.

**Comment by ShadowCreator** [comment]
That's all right, I've been having a look myself.

For some reason it runs from the AppImageAssistant.AppDir folder but not
dirrectly from the app. I

**Comment by PHPJosh** [comment]
for anyone having this error on arch the reason is the bundled vte.so in the AppImageAssistant  simply deleting  /AppImageAssistant.AppDir/usr/share/pyshared/vte.so allows the AppImageAssistant to run on Arch

**Comment by probonopd** [comment]
AppImageAssistant hast been replaced by `appimagetool`. Use it instead.
