### ISSUE TITLE
[desktopintegration] Asks every time whether to install desktop file

### ISSUE THREAD

**Issue by probonopd** [probonopd/AppImageKit#61]
Scribus-1.5.1.svn.20670-x86_64.AppImage on ubuntu-15.10-desktop-amd64.iso has this issue.
Interestingly enough, Subsurface does not have this issue.

**Comment by RazZziel** [comment]
Screenshot please?

Is a popup raised every time xdg-desktop-icon is run?

**Comment by probonopd** [comment]
Yes, the popup is raised every time. Note that all the __[desktopintegration]__ bugs are regarding https://github.com/probonopd/AppImageKit/blob/master/desktopintegration and not regarding AppImageMonitor.

**Comment by probonopd** [comment]
It falls over this `'[' Exec=/home/me/scri == TryExec=/home/me/scri ']`, stupid.
