### ISSUE TITLE
GPL compatibility

### ISSUE THREAD

**Issue by SuperMatt** [probonopd/AppImageKit#79]
The GPL states that if you are to distribute software under the GPL, you must grant the end user the ability to view the source and the license. My question is: how does AppImage intend to ensure that this can happen, should a distribution or website decide to use AppImage for their sole means of distributing software?

**Comment by RazZziel** [comment]
An AppImage is just an open container, just like a .iso or a .tar.gz, and thus is transparent to its contents. The owner of the contents inside the container is the one in charge of complying with whatever license under which the contents are distributed.

**Comment by probonopd** [comment]
This project makes available the source code for AppImageKit but we do not see anything that would prevent someone from using the AppImage format to package proprietary software. If you think otherwise, feel free to reopen.
