### ISSUE TITLE
ERROR GTK ( ubuntu 15.10 )

### ISSUE THREAD

**Issue by lugarius** [probonopd/AppImageKit#85]
t.AppDir/AppImageAssistant' 
Traceback (most recent call last):
  File "/home/lugarius/AppImageKit/AppImageAssistant.AppDir/AppImageAssistant", line 87, in <module>
    import  gtk, vte
ImportError: No module named gtk

please halp ^^ want to help minetest.net

**Comment by probonopd** [comment]
@lugarius which distribution are you using? Are python2.7 and pygtk2 installed?

**Comment by lugarius** [comment]
First, ubuntu 15.10 no pygtk please include it soon.

Second, I know this site, I worked with Ismael together but its not working ....really...  did you tried to pack it?

**Comment by probonopd** [comment]
Duplicate #202
