### ISSUE TITLE
Migrate content from old website 

### ISSUE THREAD

**Issue by kskarthik** [probonopd/AppImageKit#86]
@probonopd Migrate & redirect the old website & the data from the  [old website](http://portablelinuxapps.org) to [appimage.org](http://appimage.org) to avoid confusion for the new visitors & avoiding decentralization of information. Thank you

**Comment by probonopd** [comment]
Thanks for the reminder. portablelinuxapps.org now redirects to http://appimage.org

**Comment by hideout** [comment]
maybe we should get appimage.com too? its still free


2016-02-21 13:21 GMT+01:00 probonopd <notifications@github.com>:

**Comment by hideout** [comment]
but looks like too expensive ;(

2016-02-21 14:05 GMT+01:00 Ferdinand Klinzer <klinzer@gmail.com>:

**Comment by shoogle** [comment]
Perhaps this is a good reason to set up a donation page to support AppImage development? It doesn't have to be a big thing - a simple PayPal link would probably do. Universal Linux compatibility is a worthy cause that is bound to save developers time and money, so I think you would probably get enough donations to keep the website running.
