### ISSUE TITLE
AppImageAssistant fails to find icons in obvious locations

### ISSUE THREAD

**Issue by RazZziel** [probonopd/AppImageKit#87]
The hack in https://github.com/probonopd/AppImages/blob/master/recipes/atom/Recipe#L25-L26 should not be needed, AppImageAssistant should be able to locate the icon with `Icon=./usr/share/pixmaps/atom.png` in the .desktop file, because from the point of view of a new user creating AppImages, the error when `Icon=./usr/share/pixmaps/atom.png` is used is very non-intuitive to solve, as it should intuitively work

**Comment by probonopd** [comment]
Indeed. 

According to https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html, "icons and themes are looked for in a set of directories. By default, apps should look in $HOME/.icons (for backwards compatibility), in $XDG_DATA_DIRS/icons and in /usr/share/pixmaps (in that order). Applications may further add their own icon directories to this list, and users may extend or change the list".

**Comment by probonopd** [comment]
AppImageAssistant hast been replaced by `appimagetool`. Use it instead.
