### ISSUE TITLE
Unable to compile AppImageKit on LinuxMint 17.1 32bit ### FIXED ! CLOSE THIS ISSUE ###

### ISSUE THREAD

**Issue by kskarthik** [probonopd/AppImageKit#90]
Followed the steps on wiki but unable to compile. I am attaching a ss of the problem.
![screenshot from 2016-02-23 11 44 24](https://cloud.githubusercontent.com/assets/11899221/13243255/03a87da6-da23-11e5-9539-9b23af28edc2.png)

**Comment by probonopd** [comment]
http://www.linuxmint.com/ is down at the moment; possibly because of [this](http://thehackernews.com/2016/02/linux-mint-hack.html). So I cannot test at the moment.

**Comment by RazZziel** [comment]
@kskarthik in the screenshot you forgot to specify cmake the `<path-to-source>`, as its help message says

The correct command would be `cmake .` instead of just `cmake`

**Comment by kskarthik** [comment]
yeah, just got it. thanks. Pls close this issue
