### ISSUE TITLE
add realpath to the dependency/install list for Ubuntu

### ISSUE THREAD

**Issue by iljabek** [probonopd/AppImageKit#94]
realpath was missing after executing the installation lines [here](https://github.com/probonopd/AppImageKit/wiki/Creating-AppImages#building-appimagekit)
Error:
> ./apt-appdir/apt-appdir: line 32: realpath: command not found
> mkdir: cannot create directory ‘’: No such file or directory

**Comment by probonopd** [comment]
`sudo apt-get install coreutils` should fix that; I was not aware that there are systems where this package is not installed. May I ask which distribution you are using and how you installed it?

**Comment by ckorn** [comment]
Had the same problem too with Ubuntu 14.04. The [realpath](http://packages.ubuntu.com/trusty/realpath) package has to be installed.

However [this line in apt-appdir](https://github.com/probonopd/AppImageKit/blob/master/apt-appdir/apt-appdir#L32) fails with:
```
$ ./apt-appdir/apt-appdir youtube-dl
./youtube-dl.AppDir: No such file or directory
```

Seems like realpath fails if the directory does not exist:
```
$ realpath "./youtube-dl.AppDir"
./youtube-dl.AppDir: No such file or directory
```

**Comment by probonopd** [comment]
Updated https://github.com/probonopd/AppImageKit/wiki/Creating-AppImages to include `realpath`

**Comment by RazZziel** [comment]
Is `realpath` any different from the `readlink -f` you use above?

```
DIRNAME=$(dirname $(readlink -f "${0}"))

APP="${1}"
APPDIR=$(realpath "./${APP}.AppDir")
```
Apparently it works the same for your use case, without the extra dependency
```
07:10:28 ~$ realpath ./MadeUpRelativePath.AppDir
/home/raziel/MadeUpRelativePath.AppDir

07:10:33 ~$ readlink -f ./MadeUpRelativePath.AppDir
/home/raziel/MadeUpRelativePath.AppDir
```

**Comment by probonopd** [comment]
Good catch @RazZziel. Thanks!
