### ISSUE TITLE
appimage.org is using the VLC logo as its logo

### ISSUE THREAD

**Issue by spookylukey** [probonopd/AppImageKit#95]
See the first image on http://appimage.org/

It's even using an image that has VLC clearly in the name: https://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/VLC_Icon.svg/529px-VLC_Icon.svg.png

This is very confusing and obviously problematic.

**Comment by probonopd** [comment]
The VLC icon there is just a placeholder, as we would like to showcase [AppImages of different apps there](https://bintray.com/probono/AppImages). It is not meant as an AppImage "logo". 

Pull requests welcome, the source is [here](https://github.com/probonopd/AppImageKit/tree/gh-pages).

**Comment by chris-kahn** [comment]
I would suggest that you host the image and not hotlink wikimedia, either. While I think they allow it, it's discouraged, and generally uncourteous.
